### ISSUE TITLE
Unterstützung für HMIP-WRC6

### ISSUE THREAD

**Issue by rexyiy** [danielperna84/pyhomematic#100]
Hey,
ich habe festgestellt, dass der HomeMatic IP Schalter HMIP-WRC2 unterstützt wird. 
Wäre es möglich auch den Schalter HMIP-WRC6 hinzuzufügen? Der funktioniert ja nach dem gleichen Prinzip - nur hat er 4 Tasten mehr ;)
Danke schonmal :)

**Comment by danielperna84** [comment]
Klar geht das. Am besten macht Du einen Fork von diesem Repository, an machst dann für den WRC6 das gleiche wie es für den WRC2 schon drin ist. Diese Änderungen fügst Du dann manuell in dein laufendes Home Assistant Setup ein um zu verifizieren dass es funktioniert. Und wenn das gegeben ist kannst Du mit Deinem Fork als Basis einen Pull Request öffnen den ich dann mergen kann. :)

**Comment by rexyiy** [comment]
Siehe Pull Request #101

**Comment by danielperna84** [comment]
Ist gemerged.
