### ISSUE TITLE
Ship tets on PyPI

### ISSUE THREAD

**Issue by dotlambda** [danielperna84/pyhomematic#118]
Please include `tests/` directory in PyPI tarball. This would make it easier to make package managers run tests.

**Comment by danielperna84** [comment]
Shouldn't collaborateurs rather fork pyhomematic? That way the tests are included.

Including them in the package would only make sense if consuming applications (like Home Assistant) should run their own tests to verify the package is working. Which in the long run may make sense. But currently the tests are in such a basic state that I don't see any benefit shipping the tests now.

I'm open though for different opinions on that. I just haven't seen many packages shipping their tests, even though they are available in their repositories.

**Comment by dotlambda** [comment]
For Linux distros like NixOS, forking obviously doesn't make sense.
In Nixpkgs, we try to test as many packages as possible, no matter how trivial the tests. That way, non-functional packages can be discovered at build time. Additionally, when updating dependencies, one will quickly see if that update breaks a dependent.

I think including the tests could also make sense for Home Assistant, so that a user is notified about a non-functional package right when installing it.

**Comment by danielperna84** [comment]
Uhm, I'm using TravisCI here, which triggers the build and performs the tests for every commit. The code is always tested before a new release is published. So the only way untested code makes it into the final package would be that I ignore failed builds. Which I don't.
Testing again while installing the package is just doing the same work twice. That is unnecessary in my opinion. To verify code integrity it would make more sense to use some GPG signing or whatever to ensure the client only installs valid packages. But aside from that a possibly failing test would only indicate, that the system the package is installed on is broken, not the package itself.

**Comment by dotlambda** [comment]
However, the TravisCI environment might differ in some quirky way from the one in e.g. NixOS. Also, the tests are not mainly run to test a package's functionality but rather to check whether the package is compatible with the current set of Python packages in NixOS.
I see that not everyone might want to run the tests as they also require time etc. But since NixOS has a binary cache, this is a non-issue for us.
I think it wouldn't harm to upload the tests to PyPI as nobody is forced to run them. However, if you don't want to do that we'll just fall back to using the GitHub tarball.

**Comment by danielperna84** [comment]
Vielleicht wechseln wir mal auf Deutsch.
Also pyhomematic hat keine weiteren Abhängigkeiten als die die von Python 3 direkt mitgeliefert werden. Darüber hinaus ist es im wesentlichen ein Wrapper für eine bestimmte Hardware. Tests lassen sich also ohnehin nur bis zu einem gewissen Grad in virtuellen Umgebungen ausführen. Das einzige was man wirklich testen kann ist, ob der Server-Prozess ordentlich startet und die Geräteklassen entsprechend der Demo-Daten erzeugt werden. Ob es wirklich funktioniert sieht man erst wenn man echte Hardware verwendet.
Da hier wie gesagt mit TravisCI getestet wird kann mit Sicherheit gesagt werden, dass pyhomematic, im Bezug auf die Hardware-unabhängigen Geräte, funktioniert. Ein Pypi-Paket kann quasi per Definition nur dann die Tests nicht bestehen, wenn auf dem Zielsystem der Python-Interpreter defekt ist (im Sinne dessen, dass die Standard-Library nicht vollständig installiert ist). Ziel solcher Tests ist es aber nicht zu prüfen ob das Zielsystem funktional ist, sondern das Paket selbst. Und wenn TravisCI VMs _quirky_ wären, dann gäbe das einen ziemlich großen Aufschrei.
Wie gesagt, wenn die Tests hier umfangreicher werden und es einen weg gibt ohne Hardware tiefer gehende Tests durchzuführen, dann können die Tests mit ausgeliefert werden. Das Dient dann aber eher dazu, dass man Tests für Home Assistant schreiben kann um zu verifizieren, dass das was dort programmiert wurde auch funktioniert. pyhomematic selbst muss nicht mehr getestet werden sobald es Paketiert wurde.

**Comment by dotlambda** [comment]
Alles klar, wahrscheinlich macht es im Fall von pyhomematic tatsächlich nicht so viel Sinn, die Tests laufen zu lassen. Ist aber trotzdem keine schlechte Angewohnheit, jedes Paket zu testen. Kostet ja nix :)
Ich schließe den Issue mal und hol mir die Tests eben von GitHub.
Dankeschön für pyhomematic übrigens!
