### ISSUE TITLE
some unsupported devices

### ISSUE THREAD

**Issue by martykiico** [danielperna84/pyhomematic#119]
HM-RC-4-3 (remotecontrol)
HM-PBI-4-FM (buttoninterface)
HM-PB-2-WM55-2 (2waybutton)

^^ are unsupported. Is it possible to help for asap integration?

**Comment by danielperna84** [comment]
They are all supported already. I assume you expect them to show up in the UI of Home Assistant. That's not how they work though. Have a look at the [documentation](https://home-assistant.io/components/homematic/#devices-with-buttons).
