### ISSUE TITLE
Trigger by event doesnt perform the configured Action

### ISSUE THREAD

**Issue by martykiico** [danielperna84/pyhomematic#120]
**AutomationRule without function**
I would like to send a message trough Telegram by event homematic.keypress. By CLI "hassio ha logs"
there are Informations like:
```log
2018-02-16 13:35:40 INFO (MainThread) [homeassistant.core] Bus:Handling <Event homematic.keypress[L]: name=Taster4Fach, param=PRESS_SHORT, channel=1>
```

The AutomationRule doesnt start the Action.  Used Device with Button is: HM-PBI-4-FM

**Problem-relevant `configuration.yaml` entries and steps to reproduce:**
```automation
- action:
  - data:
      message: Es hat geklingelt!
    service: telegram_bot.send_message
  alias: Klingelmeldung per Telegram
  condition: []
  id: '1518770983656'
  trigger:
  - event_data:
      channel: '1'
      name: Taster4Fach
      param: PRESS_SHORT
    event_type: homematic.keypress
    platform: event

**Comment by danielperna84** [comment]
That might be related to the "Übertragungsmodus" of the device. You can change the communication from "secure" to "standard" within your HM-interface to solve that issue (in "Einstellungen" - "Geräte" find your device and change "Übertragungsmodus" from secure to standard) - not recommended for devices that should have secure communication.

**Comment by martykiico** [comment]
already done. What would it change about the event message?

Am 16.02.2018 14:39 schrieb "Daniel Perna" <notifications@github.com>:

**Comment by danielperna84** [comment]
I myself never had such problems. I just know that some people having issues with events had to make changes to the Übertragungsmodus. So I don't know why it's a problem. Doesn't even make sense since events arrive at Home Assistant. But as I can't reproduce these problems I just communicate the workaround.

**Comment by martykiico** [comment]
> Edit:
> Looking at your automation the probem could also be, that you have the channel in quotes. The channel is a number, not a string. So you should not use quotes there.

you are simply the best *sing

Thanks thats it in my case. The change from secure to standard "Übertragungsmodus" was not the problem becaus the event was shown in logs but its recommended to save battery power! I dont know why this Secure (AES) Mode is enabled by default.
