### ISSUE TITLE
Support for low battery warning in HM-CC-RT-DN climate

### ISSUE THREAD

**Issue by m0wlheld** [danielperna84/pyhomematic#122]
**Description of problem:**
The HM-CC-RT-DN climate exposes a LOWBAT attribute at channel 0, at least if controlled by Homegear. However, this attribute is not exposed to the Homematic Cover component in Home Assistant.

Can this be improved?

Here's the partly output of "config print" for a HM-CC-RT-DN:

        Channel: 0
        {
                [DEVICE_IN_BOOTLOADER]: 00
                [CENTRAL_ADDRESS_SPOOFED]: 00
                [RSSI_PEER]: 00
                [INHIBIT]: 00
                [AES_KEY]: 00
                [CONFIG_PENDING]: 00
                [LAST_PACKET_RECEIVED]: 5a 9b cc 27
                [UNREACH]: 00
                [LOWBAT]: 00
                [UPDATE_PENDING]: 00
                [RSSI_DEVICE]: 3a
                [STICKY_UNREACH]: 00
        }

**Comment by m0wlheld** [comment]
Oh, I see that there is a more general issue #75 , maybe this issue can contribute for device HM-CC-RT-DN

**Comment by danielperna84** [comment]
For me the battery state is working. The HM-CC-RT-DN is different from other devices. It (officially) does not have a `LOWBAT` value. If Homegear has one, then it simulates it. The thermostat has a numeric value (`BATTERY_STATE` is what the device reports), which you have access to via the entities attributes (`battery`). Mine is at 2.6 currently, which is not low.
If you monitor this value and fire an alert if it drops below a certain threshold (you'll have to find out what value that would be) you get the same functionality. Or create a dedicated template binary sensor.
I however prefer to just monitor the service messages. If the device is running low, it will be reported there soon enough to take action. I have a simple automation that pushes a message via Telegram is the services messages are more than 0. If that's the case, I just have a look at the CCU and see what the error is. I forgot how to look at the messages with Homegear, but they are available there too.

**Comment by m0wlheld** [comment]
I see. Yes the battery level is available for the device with 3.0 being the max (2xAA batteries) and probably something below 1.5 becoming critical. Maybe Homegear has better thresholds and sets LOWBAT additionally. I go and ask over there.

This issue is obsolete for now.
