### ISSUE TITLE
Thread-safeness

### ISSUE THREAD

**Issue by danielperna84** [danielperna84/pyhomematic#13]
As reported by @bimbar at the HA community, thread-safeness may be an issue. How can this be resolved in an elegant way?
My initial thought would be to use the Queue-Class (https://docs.python.org/3/library/queue.html), which every device would push its actions to, instead of directly using HMDevice._proxy.
This way, if applications using pyhomematic stick to using the HMDevice-objects to perform actions, the issue would be resolved. Am I seeing this correct?
Details on how this should be implemented can be discussed if the solution actually does solve the issue.

**Comment by bimbar** [comment]
The code has to make sure the last response has been read before starting a new request. 
Obviously not an issue for the event driven part. 

Now in the current HA homematic component this is solved by using each xmlrpc connection only once. 
I'm sure this can be done more efficiently and without sacrificing too much performance, and I don't think it's very difficult, but the hardest thing is probably testing. 
That would in my opinion best be done with an actual ha component - in my experience problems but almost immediately in that scenario.

**Comment by danielperna84** [comment]
So an alternate approach would be, that each HMDevice gets its own proxy used to send per-device events to Homegear / CCU (flip a switch, set temperature etc.). If they don't do the init, only the proxy of the server-object receives the events emitted by the CCU and handles them (like it is now).

The pros:
- probably easy to implement
- thread-safe, so issue would be resolved

The cons:
- possible performance hog with a lot of devices (especially when running on something like RPi with limited memory etc.)
- If I understood correctly from reading the docs, the proxy keeps the TCP connection alive, resulting in a lot of established but mainly unused connections
- If the connection drops it has to be re-established

The last point could be circumvented by creating the proxy for each request (similar to the current HA platform). The downside would be, that this could introduce some (minor) lag.

It would be interesting to know the cost of having the proxies per device or per request. Using the queue should be the least memory-consuming solution. On the other hand, using the queue for one single proxy object could result in some lag too. And at least for me it would be the first time doing something like this, so the lack of experience might raise other issues.

What are your thoughts on this? And from a consuming application point of view (like HA), which implementation would provide a convenient library usage?
@jazzaj Your current progress and experience regarding the HA-implementation could be of help here as well.

**Comment by bimbar** [comment]
I think one ServerProxy per device is a good idea, but even then locking has to be done. I tried that in the present homematic component and it didn't work without locking.

**Comment by danielperna84** [comment]
If we still have to implement locking, to me it makes more sense to use a centralized ServerProxy-object all devices use, given it provides a working request-queue mechanism at some point in time. That way a single point of failure is given, which can be more easily debugged, and of course we'd use less resources.

**Comment by danielperna84** [comment]
I have placed a proxy-class with locking-capability in _server.py. Check out the Proxy-Locking branch, or view the changes directly: https://github.com/danielperna84/pyhomematic/compare/Proxy-Locking
This solution would retain the single proxy-object. So we don't get lag by creating new proxies for every action a device should perform or querying it's state.
What's you opinion on this solution @bimbar ?

**Comment by danielperna84** [comment]
Since there is no response and at least my single thermostat is working fine, I expect this to work properly.
