### ISSUE TITLE
WEEK_PROGRAM_POINTER support for HM-TC-IT-WM-W-EU

### ISSUE THREAD

**Issue by klada** [danielperna84/pyhomematic#139]
The wall-mounted Homematic thermostats support up to three different week programs („Wochenprogramme“). They are useful for people working in shifts to define different
heating profiles for different weeks/shifts.

The week programs can be changed through the CCU and through the XML-RPC API. It would be nice if pyhomematic could expose the week programs as attributes of the thermostat devices, so they could be set through Home Assistant.

For the HM-TC-IT-WM-W-EU this is the XMLRPC-API call which is required for changing the profiles:

```python
conn.putParamset("DEVICE_SERIAL_NUMBER", "MASTER", {'WEEK_PROGRAM_POINTER': 0})
conn.putParamset("DEVICE_SERIAL_NUMBER", "MASTER", {'WEEK_PROGRAM_POINTER': 1})
conn.putParamset("DEVICE_SERIAL_NUMBER", "MASTER", {'WEEK_PROGRAM_POINTER': 2})
```

The current week program can also be retrieved:
```python
result = conn.getParamset("DEVICE_SERIAL_NUMBER", "MASTER")
result["WEEK_PROGRAM_POINTER"] # will be 0, 1 or 2
```

**Comment by froogl** [comment]
+1  for this issue.

I am a shift-worker and during the heating period I usually need to log into my CCU once a week in order to set the right thermostat profile, which is very annoying. That's actually what home automation should be there for :)

I would love if this could be integrated into pyhomematic and Home Assistant.

**Comment by danielperna84** [comment]
The [climate platform](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/climate/__init__.py) itself doesn't have support for scheduling-programs. So this wouldn't be something that you could control through the UI because the widget doesn't have the UI elements for that.
Would it be ok if for every thermostat that supports this, an extra entity (like [input_select](https://www.home-assistant.io/components/input_select/)) would be created where you can set the mode? Alternatively, the easier route would be to expose the `putParamset` method as a service. That way we would have a generic solution that could be leveraged for all kinds of devices that can do useful stuff with the paramsets.

**Comment by klada** [comment]
I personally think we don't need extra entities for this. People will probably set the value from an automation and not through the GUI for every single thermostat device.

To be more consistent with the current API exposed to Home Assistant I'd suggest the following:

- Expose the attribute "week_program_pointer" in supporting thermostat devices (read-only)
- Allow `WEEK_PROGRAM_POINTER` to be set through `homematic.set_device_value` like this:
```yaml
  service: homematic.set_device_value
  data:
    address: LEQ1234567
    channel: MASTER
    paramset: WEEK_PROGRAM_POINTER
    value: 1
```

On the other hand a new service (`homematic.put_paramset`) might also be feasible, since you _could_ actually set multiple values through `putParamset`. However I don't know of any other HM device which requires control through `putParamset()` at all...

BTW: In order to save RPC calls you could probably update all attributes for HM-TC-IT-WM-W-EU with one single `getParamset()` call. If you need a full sample output for this device just ping me back.

**Comment by klada** [comment]
A good first step would be a `homematic.put_paramset` service. It would be cool if multiple values could be set at once in that case, maybe a little like this:

```yaml
  service: homematic.put_paramset
  data:
    address: LEQ1234567
    paramset_key: MASTER   # Maybe use "MASTER" as default value?
    set:
      - WEEK_PROGRAM_POINTER: 1
```

If you are thinking about polling the information together with the sys vars then I think that this is probably not going to work. AFAIK you get the CCU variables through JSONRPC and I just did a little testing and could not get the WEEK_PROGRAM_POINTER through the JSONRPC API.

Another approach would be to call getParamset() whenever the thermostat device changes. Especially if putParamset() triggers a device update (haven't tested that yet) this would be an instant update - no polling required. And the API would stay very clean for users. But yes, this would lead to one extra API call per thermostat device.

But in the end I'd say that _reading_ that value is not overly important. Especially if it's so hard to make this fit with the current design of pyhomematic. It might also be easier to leave the polling entirely up to the user, but I don't know if something like `homematic.get_paramset` would actually make sense though.

**Comment by danielperna84** [comment]
I had a look at this topic now. The pyhomematic object already have a [putParamset](https://github.com/danielperna84/pyhomematic/blob/a4b6f2536f86a308d1397a3d8035c8d7122ab618/pyhomematic/devicetypes/generic.py#L108) method. It already expects a dict. So if the service calls in HASS support nested objects, then multiple values could work.
All that would be needed to change is the component in HASS. The easiest would be to duplicate [_service_handle_device](https://github.com/home-assistant/home-assistant/blob/ee8a815e6b95f86ce45f8f7eb77047491284a94b/homeassistant/components/homematic/__init__.py#L405) and rename it to something like `_service_handle_device_paramset` and do whatever is needed in there. And of course don't forget to register the service below. And a small documentation in the services.yaml would be needed as well.

**Comment by danielperna84** [comment]
Ok, so the [homematic](https://github.com/home-assistant/home-assistant/blob/ae2ee8f00618a4081c1ac59fd512df444ec87588/homeassistant/components/homematic/__init__.py#L327) object in HASS' init.py now has the `putParamset` method (merged into dev, so probably in the next HASS release as well). [This](https://github.com/danielperna84/pyhomematic/blob/649224c9b4ae4f75d2b807c2d706bcdc22f341fa/pyhomematic/_hm.py#L848) is how its implemented in pyhomematic. So if anybody wants to give it a shot, now's the time.

**Comment by klada** [comment]
So what's missing now is a separate service (`put_paramset`), right? I can try to implement it. Or is there a particular reason why you did not include a new service yet?

**Comment by danielperna84** [comment]
> So what's missing now is a separate service (put_paramset), right?

Correct. I did not do it because I currently have other things to do, and getting this to work would take some time for testing, and I don't use thermostats that way so I first would have to get it running on the CCU. For you it's basically already working, so you know what you need the service to do.

**Comment by klada** [comment]
@danielperna84 I have implemented a new service for this, see my referenced commit. Does that look mergeable to you? What _would_ be cool though is if the thermostat device would expose an attribute/service for setting the `WEEK_PROGRAM_POINTER`. But right now it looks like this does not really fit into the current architecture.

I'll create a PR for this if it looks okay to you. I can also add a note about this feature in the documentation (`components/climate.homematic` would probably be the right place).

**Comment by danielperna84** [comment]
In general it's looking ok to me. One thing though is that it's not consistent with the other services regarding the interface. I kind of like that you detect it automatically, but this generates overhead on each execution of the service. So I think it would be better to handle it like the other services and just require the proper interface in the service call. Specifying the interface once in yaml isn't that much work in my opinion.

The `putParamset` service may make sense for other types of devices as well. So I think it makes more sense to put it to the other examples for setting values or variables.

**Comment by danielperna84** [comment]
PR in Home Assistant has been merged. Closing this issue.
