### ISSUE TITLE
Unknown Parameter for value key: LOW_BAT

### ISSUE THREAD

**Issue by janbrummer** [danielperna84/pyhomematic#151]
**Description of problem:**

Several log messages within Home Assistant:

HMGeneric.getValue: LOW_BAT on 000C98A991E4A6:0 Exception: <Fault -5: 'Unknown Parameter for value key: LOW_BAT'>

**Home Assistant version (if applicable):**
0.74.2

**Problem-relevant `configuration.yaml` entries and steps to reproduce:**

Standard homematic configuration for home assistant

Device is a HmIP-BWTH with 230V (without battery)

**Comment by danielperna84** [comment]
Thanks for mentioning it. Will be fixed in the next version.
