### ISSUE TITLE
Reported rssi values are wrong

### ISSUE THREAD

**Issue by klada** [danielperna84/pyhomematic#155]
**Description of problem:**

The `rssi` value reported by the devices through `get_rssi()` are always `-65535` in my environment (CCU2 with latest firmware). The reason for this is that all of the devices which I have access to provide their `rssi` value in the attribute `RSSI_PEER`, but _pyhomematic_ checks `RSSI_DEVICE`.

Is there a particular reason why `RSSI_DEVICE` is used instead of `RSSI_PEER`? Is rssi reporting working for other people?

I have prepared the necessary changes (see referenced commit), which work for me, but I am not sure about this yet.

If it looks good to you I can prepare a PR for pyhomematic and homeassistant (two PRs required), but please tell me what you think about this first.

**Comment by danielperna84** [comment]
It's been a while since I have looked at that topic. I think back then it was unlcear which value was the relevant one. Having a quick look at it now it seems as if you are right.
