### ISSUE TITLE
Adding support for HmIP-MOD-TM

### ISSUE THREAD

**Issue by martykiico** [danielperna84/pyhomematic#170]
Hi,

ich habe einen Garagentor-Antrieb mit einem HmIP device.
ELV Link: https://www.elv.at/tormatic-funk-garagentorantrieb-white-800-mit-2-funk-handsendern-und-homematic-ip-funkmodul.html

Ich setze RaspberryMatic Version 3.37.8.20180922 ein.

**Problem:**
Das HMIP Modul scheint noch nicht unterstützt zu sein. Es liefert zwei Kanäle über welche sich das Tor steuern lässt (Öffnen, Lüftungsstellung, Schließen) auf Channel: 1 
Channel: 2 ist für die Lichtsteuerung (An und Aus).

**Home Assistant 0.78.1 :**

**Ich denke nicht, dass es mit einer falschen Konfiguration zutun hat:**
```yaml
homematic:
  interfaces:
    rf_hhs_rpc:
      host: 192.168.2.28
      resolvenames: json
      username: Admin
      password: !secret hmccupass
    groups:
      host: 192.168.2.28
      port: 9292
      resolvenames: json
      username: Admin
      password: !secret hmccupass
      path: /groups
    ip:
      host: 192.168.2.28
      resolvenames: json
      username: Admin
      password: !secret hmccupass
      port: 2010
  hosts:
    rf_hhs_ccu:
      host: 192.168.2.28
      username: Admin
      password: !secret hmccupass
```
Ich bin bereit alles zutun um die Aufnahme des Moduls zu unterstützen und liefere Daten hierfür.

**Comment by danielperna84** [comment]
Das Gerät wird bisher nicht unterstützt. Für neue Geräte muss man explizit Support einbauen. Um das zu tun bräuchte ich die relevanten Daten die dieses Script liefert: [datapoints.py](https://github.com/danielperna84/pyhomematic/blob/master/datapoints.py)
Seriennummern usw. werden anonymisiert. Das Ergebnis am besten als [gist](https://gist.github.com/) speichern und hier den link posten.

**Comment by martykiico** [comment]
ich wusste es gibt einen Haken. Raspberrymatic ist eine eigenständige Distro.
Da ist kein python installiert. Ich habe auf die schnelle keine Idee wie ich es hinbekomme. Vielleicht gibt es ein Addon welches darauf aufbaut und sich als "Zusatzsoftware flashen lässt.

**Comment by danielperna84** [comment]
Da gibt's keinen Haken. Das Script muss nicht auf dem Pi ausgeführt werden. Man trägt oben IP/Port der CCU/RaspiMatic ein, und das Script verbinden sich dann dorthin. Dazu brauchst du nur Python 3. Das geht auch unter Windows.

**Comment by martykiico** [comment]
Hey, alles super, hatte noch ne Linux VM.
anbei der Link, hoffe das ist was du brauchst.
https://gist.github.com/martykiico/ba6b1fa04344cbfb5ec7225ff11a1e28

**Comment by danielperna84** [comment]
So habe mir das mal angeschaut. Wenn du möchtest kannst du folgendes _live_ in der Python Shell testen.

```python
# 00112233 ist der Platzhalter für die tatsächliche Adresse von dem Gerät
from xmlrpc.client import ServerProxy
p = ServerProxy("http://rasp-ip:2010")
# Das sollte dir True / False liefern, je nachdem ob das Licht ein- oder ausgeschaltet ist
p.getValue("00112233:2", "STATE")
# Das hier sollte das Licht einschalten
p.setValue("00112233:2", "STATE", True)
# Das hier sollte das Licht ausschalten
p.setValue("00112233:2", "STATE", False)
```

Wie man tatsächlich den Aktor steuert müsstest du selbst testen, da für mich gerade nicht ersichtlich ist wie das genau gehen soll. Folgende Möglichkeiten gibt es.

```python
# Den Import und die Verbindung wie oben machen
# Das könnte entweder nichts (das würde ich vermuten) oder einen der folgenden Werte zurückgeben: NOP, OPEN, STOP, CLOSE, PARTIAL_OPEN
p.getValue("00112233:1", "DOOR_COMMAND")
# Es kann aber sein, dass du damit steuern kannst. Z.B. zum öffnen
p.setValue("00112233:1", "DOOR_COMMAND", "OPEN")
# Selbes wie eben, nur folgende mögliche Werte: CLOSED, OPEN, VENTILATION_POSITION, POSITION_UNKNOWN
p.getValue("00112233:1", "DOOR_STATE")
# Und ggf. steuern mit
p.setValue("00112233:1", "DOOR_STATE", "OPEN")
# Auch interessant falls das Tor manuell bedient wurde und der Aktor nicht bescheid weiß, mögliche Werte: NORMAL, UNKNOWN
p.getValue("00112233:1", "SECTION_STATUS")
```

Im Prinzip kannst du selbst einfach probieren wann was passiert. Der Teil vom JSON wo ich das her habe:
```json
            "VALUES": {
                "PROCESS": {
                    "ID": "PROCESS",
                    "DEFAULT": "STABLE",
                    "VALUE_LIST": [
                        "STABLE",
                        "NOT_STABLE"
                    ],
                    "FLAGS": 1,
                    "MAX": "NOT_STABLE",
                    "TYPE": "ENUM",
                    "OPERATIONS": 5,
                    "MIN": "STABLE"
                },
                "DOOR_COMMAND": {
                    "ID": "DOOR_COMMAND",
                    "DEFAULT": "NOP",
                    "VALUE_LIST": [
                        "NOP",
                        "OPEN",
                        "STOP",
                        "CLOSE",
                        "PARTIAL_OPEN"
                    ],
                    "CONTROL": "DOOR_RECEIVER.DOOR_COMMAND",
                    "FLAGS": 1,
                    "MAX": "PARTIAL_OPEN",
                    "TYPE": "ENUM",
                    "OPERATIONS": 2,
                    "MIN": "NOP"
                },
                "ERROR_CODE": {
                    "ID": "ERROR_CODE",
                    "DEFAULT": 0,
                    "CONTROL": "DOOR_RECEIVER.ERROR_CODE",
                    "FLAGS": 9,
                    "MAX": 255,
                    "TYPE": "INTEGER",
                    "OPERATIONS": 5,
                    "MIN": 0
                },
                "SECTION": {
                    "ID": "SECTION",
                    "DEFAULT": 0,
                    "FLAGS": 1,
                    "MAX": 15,
                    "TYPE": "INTEGER",
                    "OPERATIONS": 5,
                    "MIN": 0
                },
                "DOOR_STATE": {
                    "ID": "DOOR_STATE",
                    "DEFAULT": "CLOSED",
                    "VALUE_LIST": [
                        "CLOSED",
                        "OPEN",
                        "VENTILATION_POSITION",
                        "POSITION_UNKNOWN"
                    ],
                    "CONTROL": "DOOR_RECEIVER.DOOR_STATE",
                    "FLAGS": 1,
                    "MAX": "POSITION_UNKNOWN",
                    "TYPE": "ENUM",
                    "OPERATIONS": 5,
                    "MIN": "CLOSED"
                },
                "SECTION_STATUS": {
                    "ID": "SECTION_STATUS",
                    "DEFAULT": "NORMAL",
                    "VALUE_LIST": [
                        "NORMAL",
                        "UNKNOWN"
                    ],
                    "FLAGS": 1,
                    "MAX": "UNKNOWN",
                    "TYPE": "ENUM",
                    "OPERATIONS": 5,
                    "MIN": "NORMAL"
                }
            }
```

Vielversprechend sehen auf jeden Fall aus: `DOOR_COMMAND`, `SECTION`, `DOOR_STATE`, `SECTION_STATUS`.

Das Licht zu implementieren wird gar kein Problem. Der Aktor schon eher, da es in Home Assistant kein UI-Element gibt was das so ohne Weiteres steuern kann. Es ist ja kein Ein/Ausschalter. Im Grunde ist es aus Sicht von Home Assistant ein [cover](https://github.com/home-assistant/home-assistant/tree/dev/homeassistant/components/cover) component. Das hat aber nur _Hoch_, _Runter_ und _Stop_, sowie einen prozentualen Wert wo es gerade ist. So sind auch die _alten_ HomeMatic Aktoren implementiert (man kann ein Garagentor mit einem Rolladen vergleichen).
Der einfachste Weg wäre es als ersten Schritt den Status einfach nur als Sensor anzeigen zu lassen, und das steuern dann über eine Automation und dem `homematic.set_device_value` Service zu machen. Aber dafür muss das Gerät erst mal grundsätzlich verfügbar sein. Das kann ich machen sobald du deine Testergebnisse lieferst. 😉

**Comment by martykiico** [comment]
vielen Dank schonmal für deine Zeit und Arbeit. Ich konnte folgendes herausfinden, musste auch erstmal herausfinden wie das läuft mit der python shell.

>  Das sollte dir True / False liefern, je nachdem ob das Licht ein- oder ausgeschaltet ist
> p.getValue("00112233:2", "STATE")

`False`

>  Das hier sollte das Licht einschalten
> p.setValue("00112233:2", "STATE", True)
>  Das hier sollte das Licht ausschalten
> p.setValue("00112233:2", "STATE", False)

**Fehler 1:**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Booki\AppData\Local\Programs\Python\Python37\lib\xmlrpc\client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "C:\Users\Booki\AppData\Local\Programs\Python\Python37\lib\xmlrpc\client.py", line 1452, in __request
    verbose=self.__verbose
  File "C:\Users\Booki\AppData\Local\Programs\Python\Python37\lib\xmlrpc\client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "C:\Users\Booki\AppData\Local\Programs\Python\Python37\lib\xmlrpc\client.py", line 1170, in single_request
    return self.parse_response(resp)
  File "C:\Users\Booki\AppData\Local\Programs\Python\Python37\lib\xmlrpc\client.py", line 1340, in parse_response
    p.close()
  File "C:\Users\Booki\AppData\Local\Programs\Python\Python37\lib\xmlrpc\client.py", line 448, in close
    parser.Parse(b"", True) # end of data
xml.parsers.expat.ExpatError: no element found: line 1, column 0

```

>  Das könnte entweder nichts (das würde ich vermuten) oder einen der folgenden Werte zurückgeben: NOP, OPEN, STOP, CLOSE, PARTIAL_OPEN
p.getValue("00112233:1", "DOOR_COMMAND")

`liefert Fehler 1`

>  Es kann aber sein, dass du damit steuern kannst. Z.B. zum öffnen
p.setValue("00112233:1", "DOOR_COMMAND", "OPEN")

`liefert Fehler 1`

> Selbes wie eben, nur folgende mögliche Werte: CLOSED, OPEN, VENTILATION_POSITION, POSITION_UNKNOWN
p.getValue("00112233:1", "DOOR_STATE")

`liefert: 0`

> Und ggf. steuern mit
p.setValue("00112233:1", "DOOR_STATE", "OPEN")

`liefert Fehler 1`

> Auch interessant falls das Tor manuell bedient wurde und der Aktor nicht bescheid weiß, mögliche Werte: NORMAL, UNKNOWN
p.getValue("00112233:1", "SECTION_STATUS")

`liefert: 0`

Was den Fehler angeht, vielleicht ist irgendetwas bei mir nicht richtig konfiguriert, für einen Tipp bin ich dankbar. Ich habe auch daran gedacht die Geräteadresse zu ersetzen gegen meine.
Anbei mal ein Screenshot welche Funktionen in der Zentrale sichtbar sind (zwecks Realisierung in Homesassistent).



![homematic](https://user-images.githubusercontent.com/34889193/46232503-b3323b80-c36f-11e8-8a57-f124284d2ce4.jpg)

**Comment by danielperna84** [comment]
Verstehe ich das richtig, dass du mit den von mir genannten Befehlen __NICHT__ das Licht ein- und ausschalten konntest? Oder hat das geklappt?

Da `p.getValue("00112233:1", "DOOR_STATE")` dir den Wert `0` liefert gehe ich davon aus, dass man so den aktuellen Status vom Aktor bekommt. `0` ist dann vermutlich _geschlossen_. Man könnte also schon mal einen Sensor für diesen Parameter erstellen. Meine Vermutung:

- 0 -> Geschlossen
- 1 -> Geöffnet
- 2 -> Lüftung
- 3 -> Unbekannt (weil manuell betätigt)

Kannst du das bitte bestätigen? Das würde bedeuten, dass die Werte die dort als Text stehen nummeriert sind (was zu `TYPE: "ENUM"` passen würde).

Mit diesem ENUM-Wissen im Hintergrund bitte mal folgendes probieren:

```python
# Keine Ahnung was NOP ist, fällt dir was auf?
p.setValue("00112233:1", "DOOR_COMMAND", 0)
# Öffnen
p.setValue("00112233:1", "DOOR_COMMAND", 1)
# Stop (während das Garagentor in Bewegung ist die Aktion unterbrechen)
p.setValue("00112233:1", "DOOR_COMMAND", 2)
# Schließen
p.setValue("00112233:1", "DOOR_COMMAND", 3)
# Lüften
p.setValue("00112233:1", "DOOR_COMMAND", 4)
```

Eine generelle Frage: üblicherweise ist es bei Rolladen-Aktoren so, dass man die Zeiten Konfiguriert die das Tor zum öffnen und schließen braucht. Ist das bei deinem Gerät auch so?

**Comment by martykiico** [comment]
Hallo,

soeben konnte ich alles testen. Das Licht funktioniert mit deinen genannten Befehlen. Hatte anstatt setValue leider getValue benutzt.

Der Wert **unbekannt (Wert 3)** tritt auf während sich das Tor bewegt oder wenn ein manueller Eingriff in Form von Fernbedienung bzw. Befehl `p.setValue("00112233:1", "DOOR_COMMAND", 2)` passiert und somit eine ihm unbekannte Halteposition vorliegt.
Physisch lässt sicht das Tor nicht bewegen, der Motor hält an den Positionen fest und gibt nicht prozentuale Werte oder Öffnungswinkel zurück.
Der Befehl `p.getValue("00112233:1", "DOOR_STATE")` liefert exakt diese Werte zurück:

-   0 -> Geschlossen
-   1 -> Geöffnet
-   2 -> Lüftung
-   3 -> Unbekannt (weil manuell betätigt)



Hier kann ich keine Verändeungen erkennen nachdem ich das ausführe, nichts fällt auf:
```
# Keine Ahnung was NOP ist, fällt dir was auf?
p.setValue("00112233:1", "DOOR_COMMAND", 0)
```

Diese Befehle funktionieren genau so wie du geschrieben hast:
```
# Öffnen
p.setValue("00112233:1", "DOOR_COMMAND", 1)
# Stop (während das Garagentor in Bewegung ist die Aktion unterbrechen)
p.setValue("00112233:1", "DOOR_COMMAND", 2)
# Schließen
p.setValue("00112233:1", "DOOR_COMMAND", 3)
# Lüften
p.setValue("00112233:1", "DOOR_COMMAND", 4)
```

> Eine generelle Frage: üblicherweise ist es bei Rolladen-Aktoren so, dass man die Zeiten Konfiguriert die das Tor zum öffnen und schließen braucht. Ist das bei deinem Gerät auch so?

Ich musste dem Garagenmotor manuell die Positionen setzen am Gerät selbst. Es wurden keine Zeiten programmiert sondern die Motorpositionen eingelernt. Der HmIP-MOD-TM scheint lediglich der Initiator für den Motor zu sein um die gespeicherten Werte/Positionen anzufahren.

**Comment by danielperna84** [comment]
Ok, das ist was wir wissen müssen um alles zum laufen zu bringen.
Idealerweise setzt du dir zum testen eine separate Home Assistant Instanz auf (kein hass.io), bei der du meine vorgeschlagenen Code-Änderungen anwenden kannst ohne den produktiven Betrieb zu beeinträchtigen. Ich werde vermutlich morgen Abend dazu kommen etwas hieran zu arbeiten.

**Comment by danielperna84** [comment]
Wie ich befürchtet habe wird es schwer hier ein einfaches entity zu erzeugen dass über die GUI gesteuert werden kann. Der Lichtschalter wird gehen, aber für den Status vom Tor gibt es nur einen Sensor, und steuern muss man über Services. Das Gerät ist zu anders um es ohne deutlichen Aufwand als Cover zu implementieren.
Hier die Änderungen in pyhomematic: d71e3c8b6cbf1a0530951d2a87cb513d790688ae

Zusätzlich musst du zum testen auch im Code von Home Assistant ein bisschen was anpassen. Und zwar musst du [hier](https://github.com/home-assistant/home-assistant/blob/750c96709e7dae579083b7a6258f0b443e70dbe7/homeassistant/components/homematic/__init__.py#L65) und [hier](https://github.com/home-assistant/home-assistant/blob/750c96709e7dae579083b7a6258f0b443e70dbe7/homeassistant/components/homematic/__init__.py#L70) die neue Geräteklasse (`IPGarage`) hinzufügen damit Home Assistant weiß was damit zu tun ist. Wenn du das in deiner Testumgebung gemacht hast solltest du einen Sensor (erst mal nur mit numerischen Werten, den Text mache ich wenn du bestätigst dass es funktioniert) und einen Schalter für das Licht bekommen.

Steuern würdest du den Aktor dann in einer Automation so (hier mit dem Wert `1` zum öffnen):
```yaml
action:
  service: homematic.set_device_value
  data:
    address: 00112233
    channel: 1
    param: DOOR_COMMAND
    value: 1
```

Oder über das dev-panel mit demselben Service, und das alles in JSON gepackt: `{"address":"00112233", "channel": 1, "param": "DOOR_COMMAND", "value":1}`.

Funktioniert das alles so wie ich es mir denke?

**Comment by martykiico** [comment]
Morgen steht meine Testumgebung, dann muss ich die o.g. Files bearbeiten. Habe das für Homeassistent noch nie gemacht. Wie komme ich unkompliziert an die zu bearbeitenden Dateien? Per SSH und dann mit vi?

**Comment by danielperna84** [comment]
Das kommt drauf an wie du es installierst. Wenn es eine dedizierte Linux Maschine ist würde ich einfach den Anweisungen der [Development Documentation](https://developers.home-assistant.io/docs/en/development_environment.html) folgen. In dem Virtualenv findest du dann dieselbe Struktur wie hier im Repo wohin ich verlinkt habe.

**Comment by martykiico** [comment]
komme leider erst am Wochenende dazu, hoffe es hängt jetzt nicht an mir ob es voran geht.

**Comment by danielperna84** [comment]
Ne, das geht alles parallel. Nur keine Hektik.

**Comment by martykiico** [comment]
ich wollte meine Umgebung auf nem RaspberryPI Zero einrichten, bekomme jedoch keine Verbindung zu dem Teil, aknn auch nicht über ein Bildschirm prüfen woran es liegt, da ich keinen MiniHDMI Adapter auf HDMI habe. Wann geht der Code ins nächste Update?

**Comment by danielperna84** [comment]
Der Code kommt erst ins Update wenn du ihn getestet hast. Wie wär's mit einer [VirtualBox](https://www.virtualbox.org/) VM? Eine einfache Debian Linux Installation sollte ausreichen. Der Einfachheit halber das Netzwerk-Interface als sogenannte _Bridge_ einstellen damit die VM eine IP in deinem regulären Netzwerk bekommt und problemfrei mit der CCU kommunizieren kann.
Für Linux muss [das hier](https://developers.home-assistant.io/docs/en/development_environment.html#developing-on-linux) gemacht werden. Und ansonsten halt auch der Dev-Doku folgen. Im Prinzip brauchst du nichts weiter als ein laufendes Home Assistant bei dem du Dateien ändern kannst. Zur Not geht das auch mit hassio oder Docker. Aber da ist es schwieriger an die Dateien zu kommen, und ich weiß nicht wie es da genau geht.

**Comment by martykiico** [comment]
Ich hab mich mal versucht, direkten Zugriff bekomme ich nicht, bzw sind nicht die Ordner vorhanden wie sie überall in den HowTos gezeigt werden. Wenn ich diese Dateien anpasse wie von dir beschrieben, dann gibts folgende Fehler.

`INFO:homeassistant.util.package:Attempting install of colorlog==3.1.4
Testing configuration at /config
ERROR:homeassistant.scripts.check_config:BURB
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/scripts/check_config.py", line 207, in check
    res['components'] = check_ha_config_file(hass)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/scripts/check_config.py", line 340, in check_ha_config_file
    component = loader.get_component(hass, domain)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/loader.py", line 92, in get_component
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/homematic/__init__.py", line 884, in <module>
    raise NotImplementedError
NotImplementedError
Fatal error while loading config: 
Failed config
  General Errors: 
    - 

Successful config (partial)`

ich habe die Datei in einen `custom_components\homematic\devicetypes\actors.py` Folder geschoben
in der Hoffnung dass diese benutzt werden anstatt der Standard-Dateien. Ich bekomme keinen zusätzlichen Sensor angezeigt. 
Gibts einen Chat in dem ich mich da mal mit jemandem austauschen kann, der mir sagt wie ich verfahren muss um zu testen. Ich sehe den Ordner `\\192.168.2.41\config\deps\lib\python3.6\site-packages`
darin sind aber nur Ordner die `hass_frontended, hass_frontend_es5 und home_assistant_frontend-20181017.0.dist-info`
ich kann ich nicht die besagten Dateien vorfinden. Muss ich lediglich IPGarage hinzufügen zur `__init__.py` oder auch diese actors.py verändern?

**Comment by danielperna84** [comment]
Das mit dem custom component dürfte nicht funktionieren.
Der Chat für Home Assistant ist hier: https://discord.gg/c5DvZ4e
Dort dürfte sicher jemand sein der dir helfen kann die Anpassungen vorzunehmen.

Du musst __2__ Sachen machen:
1. Alles was sich in pyhomematic geändert hat, so wie [hier](https://github.com/danielperna84/pyhomematic/commit/d71e3c8b6cbf1a0530951d2a87cb513d790688ae). Also in der `pyhomematic/devicetypes/actors.py`.
2. Im Home Assistant code [hier](https://github.com/home-assistant/home-assistant/blob/750c96709e7dae579083b7a6258f0b443e70dbe7/homeassistant/components/homematic/__init__.py#L65) und [hier](https://github.com/home-assistant/home-assistant/blob/750c96709e7dae579083b7a6258f0b443e70dbe7/homeassistant/components/homematic/__init__.py#L70) `IPGarage` hinzufügen. Also in `homeassistant/components/homematic/__init__.py`.

Wenn es richtig gemacht wurde sollte Home Assistant fehlerfrei starten und du solltest die Sensoren und Schalter bekommen.

**Comment by martykiico** [comment]
hey, komme immer selten hierzu.
Habe eine VM aufgesetzt und Hassio auf virtualenv laufen. Die Datei actors.py ist nicht auffindbar. Ich weiß irgendwie nicht weiter.

**Comment by martykiico** [comment]
Moin,
VM aufgesetzt, jedoch spinnt das hassio nach der Installation total, ich komme nicht voran. Die vmdk Datei lässt sich nicht benutzen virtualbox wirft Fehler aus, die ova Datei wurde abgesagt und steht nichtmehr zur Verfügung. Daniel gibt es eine andere Möglichkeit? Ich bekomme es nicht hin den ******** zu testen, da immer irgendein weiteres Problem hinzukommt, die Dateien die du mir nanntest konnte ich finden und anpasse, aber es scheitert daran dass er gar kein HM-Device findet, nur die ccu selbst.

**Comment by danielperna84** [comment]
Du sollst KEIN hassio installieren, sondern ein ganz normales Linux, und
dort dann der Anleitung der dev Doku folgen. Bei hassio kannst du nicht so
einfach die Dateien austauschen. Genau deshalb sollst du das ja mit der VM
machen damit du dich NICHT mit den Eigenheiten von hassio herumplagen
musst. ;-)

martykiico <notifications@github.com> schrieb am Fr., 26. Okt. 2018, 19:17:

**Comment by danielperna84** [comment]
Also Schritt für Schritt:

- [Debian 9](https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-9.5.0-amd64-netinst.iso) herunterladen
- Eine VM erstellen deren Netzwerkinterface im Bridge-Modus ist
- Das Debian ISO als CD einhängen und davon booten
- Die Installation durchführen (weiter, weiter, weiter, SSH muss da sein, Rest egal)
- Installation ist fertig und du kommst mit SSH drauf. Die VM sollte zu diesem Zeitpunkt eine IP aus deinem Netz haben (vermutlich 192.168.x.y, siehst du mit dem Befehl `ip addr shhow`)

Das ist deine Basis. Von dieser aus folgst du [dieser](https://developers.home-assistant.io/docs/en/development_environment.html#developing-on-linux) Anleitung der Dev-Doku.
Demnach also folgendes auf der Shell (nicht als root weil __sudo__ davor steht) eingeben:
```bash
sudo apt-get install python3-pip python3-dev python3-venv
sudo apt-get install autoconf libssl-dev libxml2-dev libxslt1-dev libjpeg-dev libffi-dev libudev-dev zlib1g-dev
git clone https://github.com/home-assistant/home-assistant.git
cd home-assistant
python3 -m venv .
source bin/activate
script/setup
hass
```
Jetzt sollte Home Assistant mit seiner default Konfiguration starten. In deinem User-Order (`/home/deinname/`) gibt es nun den Ordner `.homeassistant`, den du nur mit `ls -lA` siehst weil Ordner mit `.` vorne dran versteckt sind. Dort drin findest du deine `configuration.yaml` in der du HomeMatic so konfigurierst wie bei deiner produktiven Home Assistant Installation.
Aus dem Kopf weiß ich jetzt nicht ganz genau den Pfad, aber so pi mal Daumen in `/home/deinname/home-assistant/lib64/python3/site-packages` (vielleicht auch nur `lib`, weiß ich aus dem Kopf gerade nicht) findest du dann den `homeassistant` Ordner wo der Home Assistant Code drin ist, und auch den `pyhomematic` Ordner wo der pyhomematic code drin ist.

Damit `hass` zum starten von Home Assistant funktioniert muss immer das `virtualenv` aktiv sein. Aktiviert wird es durch die Befehle oben beginnend bei `cd home...` um in den richtigen Ordner zu wechseln, und `source bin/activate` zum aktivieren. `script/setup` macht man nur ein mal (dadurch werden die Pakete wie pyhomematic heruntergeladen).

Ich hoffe mit dieser Anleitung schaffst du es nun das ganze umzusetzen. 😃

**Comment by martykiico** [comment]
ok, das hat soweit hingehauen.
Im "Zustände-Menü" taucht nur ein Sensor auf  `

switch.garagenmotor | unavailable | friendly_name: Garagenmotor
-- | -- | --




Im LOG ist folgendes zu sehen
`Exception while linking 001E5932XXXAC4: unhashable type: 'list'



der Sensor ist nicht nutzbar.

**Comment by martykiico** [comment]
ok, das hat soweit hingehauen.
Im "Zustände-Menü" taucht nur ein Sensor auf  `

switch.garagenmotor | unavailable | friendly_name: Garagenmotor
-- | -- | --




Im LOG ist folgendes zu sehen
`Exception while linking 001E5932XXXAC4: unhashable type: 'list'



der Sensor ist nicht nutzbar.

**Comment by danielperna84** [comment]
Ich glaube ich weiß was der Fehler war. Ersetze bitte in der actors.py (Zeile 423):
`self.SENSORNODE.update({"DOOR_STATE": [self.ELEMENT]})` durch `self.SENSORNODE.update({"DOOR_STATE": self.ELEMENT})`
Also die eckigen Klammern weg. Dadurch müsste die Fehlermeldung im Log verschwinden.

**Comment by martykiico** [comment]
Soeben konnte ich etwas mit dem Tor spielen.
Die Positionen lassen sich nun wie oben beschrieben steuern:

> action:
  service: homematic.set_device_value
  data:
    address: 00112233
    channel: 1
    param: DOOR_COMMAND
    value: 1


der Switch für das Licht tut allerdings noch nichts. Das Tor schaletet das Licht automatisch ein bei jedem Befehl, der Switch für das Licht verändert sich jedoch nicht.

**Comment by danielperna84** [comment]
Nur noch mal zur Bestätigung: du hast in Home Assistant ein Sensor-Entity, dass dir korrekt 0-3 anzeigt je nach Zustand? Das ist ja im Grunde erst mal das Wichtigste.
Zum Licht: wenn ich das richtig sehe hat es [hier](https://github.com/danielperna84/pyhomematic/issues/170#issuecomment-425560356) ja auch schon nicht geklappt das Licht manuell zu bedienen. Kann man das Licht denn mit der CCU überhaupt ein- und ausschalten? Denn wenn du sagst das passiert automatisch wenn das Tor betätigt wird, dann könnte das ja auch einfach nur ein binary_sensor in Home Assistant werden (wie nützlich das ist weiß ich nicht).

**Comment by martykiico** [comment]
Ja 0-3 wird je nach Zustand angezeigt. Das licht lässt sich einschalten über die CCU wie oben im Screenshot, das Licht ließ sich [hier](https://github.com/danielperna84/pyhomematic/issues/170#issuecomment-425628626) bedienen.

**Comment by danielperna84** [comment]
Probier' mal ob es funktioniert wenn die neue Klasse so aussieht:

```python
class IPGarage(GenericSwitch, HMSensor):
    """
    HmIP-MOD-TM Garage actor
    """
    def __init__(self, device_description, proxy, resolveparamsets=False):
        super().__init__(device_description, proxy, resolveparamsets)

        # init metadata
        self.SENSORNODE.update({"DOOR_STATE": [1]})

    def move_up(self):
        """Opens the garage"""
        return self.setValue("DOOR_COMMAND", 1, channel=1),

    def stop(self):
        """Stop motion"""
        return self.setValue("DOOR_COMMAND", 2, channel=1)

    def move_down(self):
        """Close the garage"""
        return self.setValue("DOOR_COMMAND", 3, channel=1)

    def vent(self):
        """Go to ventilation position"""
        return self.setValue("DOOR_COMMAND", 4, channel=1)

    @property
    def ELEMENT(self):
        return [2]
```

**Comment by martykiico** [comment]
jawollo, es funktioniert nun alles. Super Sache!

**Comment by danielperna84** [comment]
Ok, dann bringe ich den code mal in den dev branch damit es dann im nächsten release von pyhomematic mit drin ist.

**Comment by martykiico** [comment]
Das Ganze hat bis jetzt funktioniert. Ich kann leider keinen Command mehr absetzen:
Der Status wird gelesen und mir auch angezeigt:
per Automation setze ich folgenden Befehl ab:

> homematic.set_device_value

`{
  "address": "001E59XXXAFAC4",
  "channel": 1,
  "param": "DOOR_COMMAND",
  "value": 1
}`

Fehler im LOG ist folgender:
> HMGeneric.setValue: DOOR_COMMAND on 001E59XXXAFAC4:1 Exception: <Fault -1: 'Generic error'>

die einzige Veränderung sind Updates von HASSIO. Bin auf V 0.95

Verwunderlich ist einfach dass alle Veränderungen (Positionen, Lichtstatus etc.) gelesen werden können.
