### ISSUE TITLE
HM-LC-Dim2T-SM only one channel available

### ISSUE THREAD

**Issue by Kalfany** [danielperna84/pyhomematic#171]
I've a 2 channel dimmable switch HM-LC-Dim2T-SM . Within Home Assistant only the first channel ist visible and switchable. 

Output xmlapi/devicelist.cgi: 
```xml
<device name="Dimmer-Holzhütte" address="LEQ1182624" ise_id="7166" interface="BidCos-RF" device_type="HM-LC-Dim2T-SM" ready_config="true">
<channel name="Licht-Holzhütte-Innen" type="27" address="LEQ1182624:1" ise_id="7186" direction="RECEIVER" parent_device="7166" index="1" group_partner="" aes_available="false" transmission_mode="DEFAULT" visible="true" ready_config="true" operate="true"/>
<channel name="Licht-Holzhütte-Aussen" type="27" address="LEQ1182624:2" ise_id="7208" direction="RECEIVER" parent_device="7166" index="2" group_partner="" aes_available="false" transmission_mode="DEFAULT" visible="true" ready_config="true" operate="true"/>
</device>
```
![0ae93c971071833e316feb8895dae4d01a241d35](https://user-images.githubusercontent.com/6972342/46136185-4c196780-c247-11e8-82c2-388618dd0fa9.png)

See also: https://community.home-assistant.io/t/homematic-hm-lc-dim2t-sm-second-channel-missing/70338

**Home Assistant version (if applicable):**
Running Homematic version 2.29.22 @ CCU2 and Home Assistant version 0.78.3 @ RPI 3B+ (via HassOS 1.10)

**Expected behavior**
Second channel shout be available and dim/switchable within Home Assistant

**Comment by danielperna84** [comment]
Could you please manually apply the changes from commit 80a956dc0fb845709564cc2c464f9520a59249a7 (the `or ...` part in actors.py - Line 104) and see if it fixes the problem?

**Comment by Kalfany** [comment]
I guess I've to do this on a manual installation of pyhomematic? If yes, then unfortunately it has to wait until next week. Or is there any way to do this inside HassOS / Homeassistant? (I didn't find anything inside the HassOS Docker container, not even the Home Assistant stuff, but I've to say I'm completely new to Docker & Home Assistant)

**Comment by danielperna84** [comment]
There is a way so get into the Home Assistant part on HassOS, but since I don't use that I don't know exactly how that is done. But it can wait until next week.

**Comment by Kalfany** [comment]
![2ohne titel](https://user-images.githubusercontent.com/6972342/46311853-b58cd380-c5c3-11e8-95b0-df9c12f496e5.jpeg)

After applying your changes, the second channel is available and switch/dimmable. 
Thanks!
