### ISSUE TITLE
HmIP-FSM - Switching error

### ISSUE THREAD

**Issue by Munsio** [danielperna84/pyhomematic#174]
**Home Assistant version (if applicable):**
0.79.3 - hass.io

Use the following configuration for debug-output of the related components:
```yaml
logs:
    i will update the debug log output later
```

Error from Homeassistant About Page:

```
HMGeneric.setValue: STATE on 000895699E775B:2 Exception: <Fault -1: 'Generic error (DUTY_CYCLE)'>
```

**Describe the bug**
Everytime during switching of the HmIP-FSM module i got the error from above and the device turns into an "unreachable state".
I also get an "Device communication disturbed" Service message in the RaspberryMatic-CCU

**To Reproduce**
1. Switch on/off an HmIP-FSM actor in homeassistant

**Expected behavior**
The switch toggles the state

**Comment by danielperna84** [comment]
Maybe this is somehow a similar problem as reported in #168 . What's your firmware version? I myself haven't seen such errors (only have one IP device which works fine).
In general this isn't something pyhomematic can do anything about. We're just calling the XML-RPC API. If using the API causes such errors, then it's a problem in the API, not in its usage (we've been doing it the same way for years).

**Comment by Munsio** [comment]
Firmware of RaspberryMatic: 3.37.8.20180929
Device Firmware: 1.6.2

Where there changes in the API between OCCU 2 and 3??

**Comment by danielperna84** [comment]
Not that I'm aware of. I haven't even updated my CCU2 to the latest version yet. But as with the other mentioned issue, these kind of problems only seem to appear with IP devices.

Did the HmIP-FSM work properly before? I never have tested it myself, so I'm not sure it ever worked correctly.

**Comment by Munsio** [comment]
Everything worked as normal before.

**Comment by danielperna84** [comment]
So then it obviously is caused by the updated Firmware for the CCU / RaspberryMatic. Here's an issue at the OCCU (what Raspverry Matic is based on) repository: https://github.com/eq-3/occu/issues/85 Maybe your observations are valuable input to get the issue fixed.

**Comment by danielperna84** [comment]
Could you please add the changes I have made [here](https://github.com/home-assistant/home-assistant/pull/17341) and see if your device still turns to unavailable (I could only test devices becoming available), and also if it becomes available again later on?

**Comment by a-wolter** [comment]
Hassbian with HA 0.83.1
CCU FW: 3.41.11
Device HmIP-FSM and HmIP-FSM16 with 1.6.2 FW

No warning or error in the log, no matter how oftenI switch the FSM on or off.

Is the duty cycle warning not related to the 36s/hour limit for the devices and ccu on the 868Mhz frequency? 

https://www.eq-3.com/service/faq.html?id=468

**Comment by danielperna84** [comment]
> No warning or error in the log, no matter how oftenI switch the FSM on or off.

So everything is working correctly. If there are errors, then it's a local issue for the user. So this issue can be closed?

> Is the duty cycle warning not related to the 36s/hour limit for the devices and ccu on the 868Mhz frequency?

Yes, duty cycle is what you are referring to. We just don't know yet why these messages appear in these specific HmIP cases.

**Comment by danielperna84** [comment]
Since there is no more feedback coming I assume this issue is resolved.
