### ISSUE TITLE
Add Support for HmIP-PDT 

### ISSUE THREAD

**Issue by thechrisde** [danielperna84/pyhomematic#181]
**Is your feature request related to a problem? Please describe.**
It's not related.

**Describe the solution you'd like**
I would like to control HmIP-PDT over pyhomatic

**Describe alternatives you've considered**
none

**Additional context**
Attached you find [outfile-hmip-pdt.txt](https://github.com/danielperna84/pyhomematic/files/2568909/outfile-hmip-pdt.txt)

Thank you!

**Comment by thechrisde** [comment]
It shows up. But isn't working.

In the HA log I get: 

`2018-11-14 00:01:32 ERROR (SyncWorker_27) [pyhomematic.devicetypes.generic] HMGeneric.getValue: WORKING on XXX:4 Exception: <Fault -5: 'Unknown Parameter for value key: WORKING'>
2018-11-14 00:01:32 ERROR (SyncWorker_22) [pyhomematic.devicetypes.generic] HMGeneric.getValue: WORKING on XXX:4 Exception: <Fault -5: 'Unknown Parameter for value key: WORKING'>`

**Comment by danielperna84** [comment]
The `WORKING` can be ignored. You probably only got that when starting Home Assistant. Some devices have that parameter, some don't, so we just always ask the CCU for the value. The error you se is the CCU saying _I don't know that parameter for that device_. Besides that though it should actually work. The device description is pretty much the same as other IP dimmers.

But you can try it out manually with the following code:

```python
# 00112233 is the address of your device
from xmlrpc.client import ServerProxy
p = ServerProxy("http://ccu-ip:2010")
# Should return True or False, depending on the state of the device
p.getValue("00112233:4", "LEVEL")
# Should turn the device on
p.setValue("00112233:4", "LEVEL", 1.0)
# Should turn the device off
p.setValue("00112233:4", "LEVEL", 0.0)
```

You can replace the `:4` with another channel and see if it react to the `LEVEL` parameter. The device has the channels 0-6, where 0 is just the maintenance channel. So 1-6 should be the ones where something can happen.

**Comment by thechrisde** [comment]
Seems like the channel is 3 not 4. When I'm using channel 3 it is working.

**Comment by danielperna84** [comment]
Ok. Please add the following class:

```python
class IPDimmer(GenericDimmer):
    """
    IP Dimmer switch that controls level of light brightness.
    """
    @property
    def ELEMENT(self):
        return [3]
```

And change `"HmIP-PDT": IPKeyDimmer,` to `"HmIP-PDT": IPDimmer,`. You then also have to make a little change in the [`__init__.py`](https://github.com/home-assistant/home-assistant/blob/8aa1283adc6eb9050e6c5b5594eb3bcf1cf7e01f/homeassistant/components/homematic/__init__.py#L68) of Home Assistant. Add `'IPDimmer'` to the list. After that restart Home Assistant, and you should be able to control the device.

**Comment by thechrisde** [comment]
Works like a charm. Thank you!
