### ISSUE TITLE
Unknown Parameter for value key: LOWBAT

### ISSUE THREAD

**Issue by FlavorFx** [danielperna84/pyhomematic#186]
Description of problem:
Error log messages during Home Assistant startup:

[pyhomematic.devicetypes.generic] HMGeneric.getValue: LOWBAT on 00109709A8F405:1 Exception: <Fault -5: 'Unknown Parameter for value key: LOWBAT‘>

Home Assistant version: 0.82.1

**Comment by danielperna84** [comment]
What type of device is this?

**Comment by FlavorFx** [comment]
It comes form Window / Door Sensor. Homematic IP Fenster- und Türkontakt - optisch HMIP-SWDO and HmIP-SWDO-I

**Comment by danielperna84** [comment]
Could you please check if your device is using the parameter `LOW_BAT` instead of `LOWBAT`?

This is how to do that:

```python
from xmlrpc.client import ServerProxy
p = ServerProxy("http://ccu-ip:2010")
# Should return True or False, depending on the battery state
p.getValue("00109709A8F405:1", "LOW_BAT")
```

**Comment by FlavorFx** [comment]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1092, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1432, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1134, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1150, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1322, in parse_response
    return u.close()
  File "/usr/lib/python3.5/xmlrpc/client.py", line 655, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -5: 'Unknown Parameter for value key: LOW_BAT'>

**Comment by danielperna84** [comment]
Ok, then please post the output of [datapoints.py](https://github.com/danielperna84/pyhomematic/blob/master/datapoints.py) as a [gist](https://gist.github.com/).

**Comment by FlavorFx** [comment]
https://gist.github.com/FlavorFx/9427fee3d5d57c802c61fc52b099d647 <https://gist.github.com/FlavorFx/9427fee3d5d57c802c61fc52b099d647>

ok, here we are.

**Comment by danielperna84** [comment]
I had a look at it now. This should get the result:

```python
from xmlrpc.client import ServerProxy
p = ServerProxy("http://ccu-ip:2010")
# Should return True or False, depending on the battery state
p.getValue("00109709A8F405:0", "LOW_BAT")
```

**Comment by FlavorFx** [comment]
Correct. It works! It returns FALSE because non if my devices are low of batterie. Are you going to fix this in the next release?
