### ISSUE TITLE
HM-Sen-RD-O not working correctly.

### ISSUE THREAD

**Issue by DieterChmod** [danielperna84/pyhomematic#193]
**Home Assistant version:**
0.83.1

**Problem-relevant `configuration.yaml` entries and steps to reproduce:**
Not relevant.

**Describe the bug**
The rain sensor has one sensor channel which indicates rain and a second channel to switch the heating on and off.
Activating or deactivating the heating switch on the homeassistant web interface results in activating or deactivating the displayed sensor state.
Switching the heating on results in sensor state on:
![on](https://user-images.githubusercontent.com/45570637/49469220-43c14800-f807-11e8-88b7-cef0fa69e735.png)
Switching it off results in the sensor state off:
![off](https://user-images.githubusercontent.com/45570637/49469216-40c65780-f807-11e8-9169-8e4258ae99c9.png)

**Expected behavior**
The sensor state indicator in hass should display the *real* state and not whether the heating is switched in or off.

**Screenshots**
see above

**Additional context**
This is a file with the respective debug output of homeassistant. The ID of the sensor/actor is OEQ1908022.
[OEQ1908022.txt](https://github.com/danielperna84/pyhomematic/files/2645874/OEQ1908022.txt)
This is the XML-API Addon output on the CCU-2.
[xml_api_out.txt](https://github.com/danielperna84/pyhomematic/files/2645930/xml_api_out.txt)

**Comment by danielperna84** [comment]
Does the switch itself work properly and turns the heating on and off? This device has only been implemented based on the documentation, so no real testing has been done.

**Comment by danielperna84** [comment]
And please provide a clean log. What you have posted seems to include multiple restarts and a lot of noise. It's really hard to know what to look for. Please only post the parts of the log shortly before you flip the switch until shortly after that.
Also be aware, that in the log you have posted an access token is included. You should revoke that token and create a new one for whatever the token is being used.

**Comment by DieterChmod** [comment]
Hi,
first of all... thanks a lot for looking into this and pointing me to the access token issue. :)
The switch itself works properly and rain sensor state only changes on homeassistant, not on the CCU.
Here is a snippet from the log switching on and off two times. Hope this one is better than the previous.

[OEQ1908022.txt](https://github.com/danielperna84/pyhomematic/files/2650716/OEQ1908022.txt)
Best,
Tobias

**Comment by danielperna84** [comment]
Please test the following:
In the [`__init__.py`](https://github.com/home-assistant/home-assistant/blob/26a38f1faeeb8c034ae6aa388281011b3662b655/homeassistant/components/homematic/__init__.py#L792) of the HomeMatic component in HomeAssistant modify the `_hm_event_callback` method.

Right now it looks like this:

```python
    def _hm_event_callback(self, device, caller, attribute, value):
        """Handle all pyhomematic device events."""
        _LOGGER.debug("%s received event '%s' value: %s", self._name,
                      attribute, value)
        has_changed = False
```

Add this if-clause to verify that the channel of the event matches the entity:
```python
    def _hm_event_callback(self, device, caller, attribute, value):
        """Handle all pyhomematic device events."""
        _LOGGER.debug("%s received event '%s' value: %s", self._name,
                      attribute, value)
        if int(device.split(':')[-1]) != self._channel:
            return
        has_changed = False
```

That should skip the update of the sensor. I assume because of the some parameter-name the sensor entity believes the state of the event is the value it should have, although it's actually targeted at the other channel.
If this fixes the issue, please also observe if this has any negative effects on your system. I have not yet tested this myself and I am unsure if this can break the state-updates of other devices.

**Comment by DieterChmod** [comment]
Thanks again for that quick reply. At a first glance that fixes the problem.
However, I will observe it a while and wait for rain, which likely will happen tomorrow.

Out of curiosity. Do you think that is the final fix to the problem? Can I do anything else for you and... for instance debug something?

Best,
Tobias

**Comment by danielperna84** [comment]
Yes, I do think this would be an appropriate fix. But it has the potential to break the functionality of other devices. Well, actually it shouldn't break it. This is - at least in my opinion - a real bug in the code. It just didn't have any negative impacts. So it could be, that other devices actually rely on this bug to work.
So for now you can't really test anything. The only devices affected would be ones that share a parameter across different channels. But also only if implemented in a certain way. So I'll add this to my setup over the weekend to at least have another opinion, and then probably open a PR to get this merged into Home Assistant.

**Comment by DieterChmod** [comment]
Great. I'm glad that I could help.
If I see anything strange in my configuration, I'll get back to you.
Cheers.

**Comment by danielperna84** [comment]
A quick update: this patch has not been included in the latest update of Home Assistant. Pascal realised, that this will probably break updates for attributes like RSSI or LOW_BAT. So if you update and favour the funcitonality of the patch over correctly updating attributes, then you have to re-add it again. It's a tricky bug, and for now we haven't found a solution that properly addresses the issue.

Could you please open the same issue in the Home Assistant repository? That way it won't be forgotten and is targeting the correct project.
