### ISSUE TITLE
Implementing HmIP-MOD-RC8

### ISSUE THREAD

**Issue by emkay82** [danielperna84/pyhomematic#210]
**Is your feature request related to a problem? Please describe.**
I would like to implement the support of HmIP-MOD-RC8. The operation mode of every channel can be set to "INACTIVE", "KEY_BEHAVIOR", "SWITCH_BEHAVIOR" or "BINARY_BEHAVIOR" in the device configuration.

While for example channels configured as "KEY_BEHAVIOR" should be handled in "misc.py", channels configured as "BINARY_BEHAVIOR" should be handled in "sensors.py".

I have changed the operation mode of some channels and then fetched the datapoints using "datapoints.py", but unfortunately I can't find the configured values in the result. Therefore it is not possible to consider the difference during development.

**Describe the solution you'd like**
The configured operation mode values of each channel should be readable.

**Describe alternatives you've considered**
The alternative would be to disallow the use of "BINARY_BEHAVIOR", which makes it impossible to use the devices channels as binary_sensors.

**Additional context**
Of course I can also provide the output of "datapoints.py" if needed.

**Comment by emkay82** [comment]
Sorry, I maybe missunderstood, which data the output contains. I will take a look again at it this weekend.

**Comment by danielperna84** [comment]
Another hint: what the implementation for the wired module above does is looking at the paramsets. The datapoints script only extracts the `VALUES` paramset. Configurational options usually are within the `MASTER` paramset. To look at a paramset you can use this code:

```python
from xmlrpc.client import ServerProxy
p = ServerProxy("http://1.2.3.4:2010")
p.getParamsetDescription("deviceaddress:channel", "MASTER")
```

**Comment by emkay82** [comment]
Hi Daniel,

I was trying unsuccessfully to find an entry today. For a while, I thought I understood how the class `HMWIOSwitch` works and adopted the concept.

Below my test class:
```python
class TestIPShutterContact(HMBinarySensor, HelperBinaryState, HelperLowBat):
    """ Test """
    def __init__(self, device_description, proxy, resolveparamsets=False):
        self._dic = []
    
        super().__init__(device_description, proxy, resolveparamsets)
        if "HmIP-MOD-RC8" in self._TYPE:
            channels = [1, 2, 3, 4, 5, 6, 7, 8]
            
            for chan in channels:
                print("%s:%i" % (self._ADDRESS, chan))
                print(str(self._proxy.getParamset("%s:%i" % (self._ADDRESS, chan), "MASTER").get("CHANNEL_OPERATION_MODE", None)))
                # if self._proxy.getParamset("%s:%i" % (self._ADDRESS, chan), "MASTER").get("CHANNEL_OPERATION_MODE", None) == 3:
                    # self._dic.append(chan)
                
    @property
    def ELEMENT(self):
        return self._dic
```

Unfortunately I get the following error messages, when calling `getParamset`:
```
CRITICAL:pyhomematic._hm:RPCFunctions.createDeviceObjects: Parent: <Fault -1: 'Generic error'>
CRITICAL:pyhomematic._hm:RPCFunctions.createDeviceObjects: Child: '0123456789ABCD'
CRITICAL:pyhomematic._hm:RPCFunctions.createDeviceObjects: Child: '0123456789ABCD'
CRITICAL:pyhomematic._hm:RPCFunctions.createDeviceObjects: Child: '0123456789ABCD'
CRITICAL:pyhomematic._hm:RPCFunctions.createDeviceObjects: Child: '0123456789ABCD'
CRITICAL:pyhomematic._hm:RPCFunctions.createDeviceObjects: Child: '0123456789ABCD'
CRITICAL:pyhomematic._hm:RPCFunctions.createDeviceObjects: Child: '0123456789ABCD'
CRITICAL:pyhomematic._hm:RPCFunctions.createDeviceObjects: Child: '0123456789ABCD'
CRITICAL:pyhomematic._hm:RPCFunctions.createDeviceObjects: Child: '0123456789ABCD'
CRITICAL:pyhomematic._hm:RPCFunctions.createDeviceObjects: Child: '0123456789ABCD'
```

Here is an excerpt from the result of `datapoints.py` (shortened PARAMSETS):
```JSON
[
    {
        "TYPE": "HmIP-MOD-RC8",
        "SUBTYPE": "MOD-RC8",
        "ADDRESS": "819",
        "RF_ADDRESS": 3466154,
        "CHILDREN": [
            "9:0",
            "9:1",
            "9:2",
            "9:3",
            "9:4",
            "9:5",
            "9:6",
            "9:7",
            "9:8"
        ],
        "PARENT": "",
        "PARENT_TYPE": "",
        "INDEX": 0,
        "AES_ACTIVE": 1,
        "PARAMSETS": {
        .
        .
        .
        },
        "FIRMWARE": "1.0.5",
        "AVAILABLE_FIRMWARE": "0.0.0",
        "UPDATABLE": true,
        "FIRMWARE_UPDATE_STATE": "UP_TO_DATE",
        "VERSION": 1,
        "FLAGS": 1,
        "LINK_SOURCE_ROLES": "",
        "LINK_TARGET_ROLES": "",
        "DIRECTION": 0,
        "GROUP": "",
        "TEAM": "",
        "TEAM_TAG": "",
        "TEAM_CHANNELS": [],
        "INTERFACE": "",
        "ROAMING": 0,
        "RX_MODE": 4
    },
    {
        "TYPE": "MAINTENANCE",
        "SUBTYPE": "",
        "ADDRESS": "9:0",
        "RF_ADDRESS": 1619,
        "CHILDREN": [],
        "PARENT": "819",
        "PARENT_TYPE": "HmIP-MOD-RC8",
        "INDEX": 0,
        "AES_ACTIVE": 1,
        "PARAMSETS": {
        .
        .
        .
        },
        "FIRMWARE": "",
        "AVAILABLE_FIRMWARE": "",
        "UPDATABLE": true,
        "FIRMWARE_UPDATE_STATE": "",
        "VERSION": 1,
        "FLAGS": 1,
        "LINK_SOURCE_ROLES": "",
        "LINK_TARGET_ROLES": "",
        "DIRECTION": 0,
        "GROUP": "",
        "TEAM": "",
        "TEAM_TAG": "",
        "TEAM_CHANNELS": [],
        "INTERFACE": "",
        "ROAMING": 0,
        "RX_MODE": 0
    },
    {
        "TYPE": "KEY_TRANSCEIVER",
        "SUBTYPE": "",
        "ADDRESS": "9:1",
        "RF_ADDRESS": 3212,
        "CHILDREN": [],
        "PARENT": "819",
        "PARENT_TYPE": "HmIP-MOD-RC8",
        "INDEX": 1,
        "AES_ACTIVE": 1,
        "PARAMSETS": {
            "MASTER": {
                .
                .
                .
                "CHANNEL_OPERATION_MODE": {
                    "MIN": "INACTIVE",
                    "OPERATIONS": 3,
                    "MAX": "BINARY_BEHAVIOR",
                    "FLAGS": 1,
                    "ID": "CHANNEL_OPERATION_MODE",
                    "TYPE": "ENUM",
                    "DEFAULT": "KEY_BEHAVIOR",
                    "VALUE_LIST": [
                        "INACTIVE",
                        "KEY_BEHAVIOR",
                        "SWITCH_BEHAVIOR",
                        "BINARY_BEHAVIOR"
                    ]
                }
                .
                .
                .
            }
            .
            .
            .
        },
        "FIRMWARE": "",
        "AVAILABLE_FIRMWARE": "",
        "UPDATABLE": true,
        "FIRMWARE_UPDATE_STATE": "",
        "VERSION": 1,
        "FLAGS": 1,
        "LINK_SOURCE_ROLES": "REMOTE_CONTROL",
        "LINK_TARGET_ROLES": "",
        "DIRECTION": 1,
        "GROUP": "",
        "TEAM": "",
        "TEAM_TAG": "",
        "TEAM_CHANNELS": [],
        "INTERFACE": "",
        "ROAMING": 0,
        "RX_MODE": 0
    }
]
```

Because I don't usually program with python and the pyhomematic project is relatively extensive, it is not yet easy for me to identify the causes of every occurring error. But I'm sure, a little hint here can bring me forward. :-)

**Comment by danielperna84** [comment]
First do it manually, roughly like I showed above. I used the wrong method there though. Try this instead:

```python
from xmlrpc.client import ServerProxy
p = ServerProxy("http://1.2.3.4:2010")
p.getParamset("deviceaddress:channel", "MASTER").get("CHANNEL_OPERATION_MODE")
```

That should return the value of the operation mode. And that's also what the code for the wired device im referring to does. I think your device is less complex though in terms of functionality. So your class should have less code. You should just define a list of channels for which you want to detect the operation mode, and with that information update the nodes.

**Comment by emkay82** [comment]
Thank you, I will try it manually tomorrow again.

Not sure, how to shorten my code above. My plan was to first define a list of channels of a specific device (in this case `HmIP-MOD-RC8`, which has 8 input channels). Then iterate the list and check the operation mode value. In `sensors.py` only channelsu configured as `BINARY_BEHAVIOUR`, will be written into `self._dic`, which then will be returned. In `misc.py`, another class will do the same thing, but will only return channels configured as `KEY_BEHAVIOR`. This way, we were able to use the device as a remote and as a binary sensor at the same time. And it would not be necessary to change the code, when operation mode of channels are changed in the CCU device config.

Not sure now, if my thinking is wrong.

**Comment by danielperna84** [comment]
> Not sure, how to shorten my code above.

Sorry, I overlooked yuor code and directly skipped to all the logs. What you have done in the code is pretty much what I have meant.

Why your code is not printing the channels isn't clear to me right now. So seeing if it works manually from the shell might help to narrow down the problem. Apparently there already is a problem before you get to the channels, since the first error is about the base-object (parent).

**Comment by emkay82** [comment]
A manual call returned the correct value, so I started further testing. Unfortunately now the CCU hangs and I can't reach it anymore. Because I'm working remotely, I can't cut off the CCU's power now. I have to wait until thursday :-(

**Comment by emkay82** [comment]
No chance. I cannot get the value `CHANNEL_OPERATION_MODE` within the class. If I uncomment the `getParamset` line, the correct addresses are printed out by `print("%s:%i" % (self._ADDRESS, chan))`. :-(

The manual call you suggested works just fine. Any ideas?

**Comment by emkay82** [comment]
Okay, I started some research and found, that this behavoiur happens to HmIP devices in specific circumstances. For example here: https://homematic-forum.de/forum/viewtopic.php?t=38372#p380181

I guess `self._proxy.getParamset` uses `BidCos` as interface instead of `HmIP-RF`. Because `HMW-IO-12-Sw14-DR` is `BidCos` of type, there were no problems. How could I go forward?

**Comment by danielperna84** [comment]
> I guess `self._proxy.getParamset` works slightly different in some way then `getParamset` of your manual call.

No it's not different. The fact that it works manually means, that it _should_ also work programmatically. I don't know why it does not work.

Did you try to wrap the relevant code into a try/except block to print possible exceptions? And maybe add some additional logging? There really isn't anything more I can tell you about this. If the manual approach works, then it should work in the script. If it does not, then it's not correctly done in the script. For whatever reason I can't name.

**Comment by emkay82** [comment]
Unfortunately, my knowledge in python is not good enough to solve the problem. I of course set various try/except blocks to narrow it down - with no success.

The only thing I could notice, is that there are no entries in `pyhomematic.devices` when running `example.py`. But that doesn't really help me locating the causing lines.

Giving up for now. Thanks anyway for your help and patience.

**Comment by danielperna84** [comment]
> The only thing I could notice, is that there are no entries in `pyhomematic.devices` when running `example.py`.

You did change the port from 2001 to 2010? For IP devices 2010 is the correct port. Just like it's configured in Home Assistant.

**Comment by emkay82** [comment]
I really wish the problem would be that simple. When I remove the line with `self._proxy.getParamset`, then `pyhomematic.devices` gets filled. I also took a closer look at `hm.py`. After a while I realized that I still had to learn a lot to solve the problem. I really would do that, but this would go beyond my available time :-(

**Comment by emkay82** [comment]
Aufgrund des Umfangs nachfolgend ausnahmsweise auf Deutsch :-)

Das Thema lässt mir einfach keine Ruhe, ich musste nochmal genauer schauen.

Ich habe testweise in der `_hm.py` an mehreren Stellen mit dem jeweiligen Proxy-Objekt `getParamset()` ausgeführt. Unter `createDeviceObjects` ist mir dann eine Unregelmäßigkeit aufgefallen. Hierfür habe ich einen globalen Zähler erstellt, der die Ausführungen von `createDeviceObjects` zählt. Innerhalb der `createDeviceObjects` rufe ich `self._proxies[interface_id].getParamset()` innerhalb eines try-Blocks auf und lasse das Ergebnis ausgeben. Zusätzlich einen String, der angibt, ob die Ausführung fehlerhaft war oder nicht.

`_hm.py` sieht jetzt so aus:
```python
.
.
.
CreateDeviceCounter = 0
.
.
.
    def createDeviceObjects(self, interface_id):
        """Transform the raw device descriptions into instances of devicetypes.generic.HMDevice or availabe subclass."""
        global working, CreateDeviceCounter
        working = True
        remote = interface_id.split('-')[-1]

        ##################
        ### TEST BEGIN ###
        ##################
        CreateDeviceCounter += 1
        print('>>> RUN ' + str(CreateDeviceCounter))
        print('>>> INTERFACE: ' + interface_id)
        try:
            print('>>> RESULT: ' + str(self._proxies[interface_id].getParamset('XXXXXXXXXXXXXX:4', 'MASTER').get('CHANNEL_OPERATION_MODE')))
            print('>>> SUCCESS')
        except:
            print('>>> ERROR')
        print('>>> CONTINUE')
        ##################
        ###  TEST END  ###
        ##################

        LOG.debug(
            "RPCFunctions.createDeviceObjects: iterating interface_id = %s" % (remote, ))
        # First create parent object
        for dev in self._devices_raw[remote]:
            if not dev['PARENT']:
                if dev['ADDRESS'] not in self.devices_all[remote]:
                    try:
                        if dev['TYPE'] in devicetypes.SUPPORTED:
                            deviceObject = devicetypes.SUPPORTED[dev['TYPE']](
                                dev, self._proxies[interface_id], self.resolveparamsets)
                            LOG.debug("RPCFunctions.createDeviceObjects: created %s  as SUPPORTED device for %s" % (
                                dev['ADDRESS'], dev['TYPE']))
                        else:
                            deviceObject = devicetypes.UNSUPPORTED(
                                dev, self._proxies[interface_id], self.resolveparamsets)
                            LOG.debug("RPCFunctions.createDeviceObjects: created %s  as UNSUPPORTED device for %s" % (
                                dev['ADDRESS'], dev['TYPE']))
                        LOG.debug(
                            "RPCFunctions.createDeviceObjects: adding to self.devices_all")
                        self.devices_all[remote][dev['ADDRESS']] = deviceObject
                        LOG.debug(
                            "RPCFunctions.createDeviceObjects: adding to self.devices")
                        self.devices[remote][dev['ADDRESS']] = deviceObject
                    except Exception as err:
                        LOG.critical(
                            "RPCFunctions.createDeviceObjects: Parent: %s", str(err))
        # Then create all children for parent
        for dev in self._devices_raw[remote]:
            if dev['PARENT']:
                try:
                    if dev['ADDRESS'] not in self.devices_all[remote]:
                        deviceObject = HMChannel(
                            dev, self._proxies[interface_id], self.resolveparamsets)
                        self.devices_all[remote][dev['ADDRESS']] = deviceObject
                        self.devices[remote][dev['PARENT']].CHANNELS[
                            dev['INDEX']] = deviceObject
                except Exception as err:
                    LOG.critical(
                        "RPCFunctions.createDeviceObjects: Child: %s", str(err))
        if self.devices_all[remote] and self.remotes[remote].get('resolvenames', False):
            self.addDeviceNames(remote)
        working = False
        if self.systemcallback:
            self.systemcallback('createDeviceObjects')

        ##################
        ### TEST BEGIN ###
        ##################
        print('\r\n' + str(self.devices))
        ##################
        ###  TEST END  ###
        ##################

        return True
.
.
.
```

Meine `exmaple.py` so:
```python
#!/usr/bin/python3
import time
import sys
import logging
#logging.basicConfig(level=logging.DEBUG)

def syscb(src, *args):
    print(src)
    for arg in args:
        print('')
        #print(arg)

from pyhomematic import HMConnection

pyhomematic = HMConnection(remote="192.168.10.30", remoteport=2010, systemcallback=syscb)
pyhomematic.start()
time.sleep(0.2)

print('DEVICES: ' + str(pyhomematic.devices))

pyhomematic.stop()

sys.exit(0)
```

Wenn ich die example.py nun ausführe, erhalte ich folgende Ausgabe:
```
>>> RUN 1
>>> INTERFACE: pyhomematic-default
>>> RESULT: 3
>>> SUCCESS
>>> CONTINUE
createDeviceObjects

{'default': {}}
listDevices

>>> RUN 2
>>> INTERFACE: pyhomematic-default
DEVICES: {'default': {}}
>>> ERROR
>>> CONTINUE
createDeviceObjects

{'default': {'XXXXXXXXXXXXXX': <pyhomematic.devicetypes.sensors.TestIPShutterContact object at 0x038B5170>, 'XXXXXXXXXXXXXX': <pyhomematic.devicetypes.thermostats.IPThermostatWall object at 0x038B5070>}}
newDevices
```

Hier fallen zwei Dinge sofort auf:
1. `getParamset()` funktioniert beim ersten Durchlauf einwandfrei, schlägt beim zweiten Mal aber fehl
2. Der PRINT-Befehl aus `example.py` (`DEVICES: ...`) wird ausgeführt, bevor der zweite Durchlauf beendet ist

Der Aufruf von `getParamset()` im zweiten Durchlauf benötigt einige Sekunden, bevor eine Exception ausgelöst wird.

Anders als von mir zuvor vermutet, wird `self.devices` trotz Fehler befüllt.


Entferne ich die Zeile mit `getParamset` innerhalb `createDeviceObjects`, sieht die Ausgabe unauffällig aus und auch der PRINT-Befehl aus der `example.py` (`DEVICES: ...`) wird erst nach dem zweiten Durchlauf ausgeführt:
```
>>> RUN 1
>>> INTERFACE: pyhomematic-default
>>> SUCCESS
>>> CONTINUE
createDeviceObjects

{'default': {}}
listDevices

>>> RUN 2
>>> INTERFACE: pyhomematic-default
>>> SUCCESS
>>> CONTINUE
createDeviceObjects

{'default': {'XXXXXXXXXXXXXX': <pyhomematic.devicetypes.sensors.TestIPShutterContact object at 0x04378250>, 'XXXXXXXXXXXXXX': <pyhomematic.devicetypes.thermostats.IPThermostatWall object at 0x04378290>}}
newDevices


DEVICES: {'default': {'XXXXXXXXXXXXXX': <pyhomematic.devicetypes.sensors.TestIPShutterContact object at 0x04378250>, 'XXXXXXXXXXXXXX': <pyhomematic.devicetypes.thermostats.IPThermostatWall object at 0x04378290>}}
```

Kannst du mit diesen Infos eine Vermutung anstellen? Ich kann das Problem immernoch nicht so recht greifen. Ist das ein Problem mit der RPC-Schnittstelle? Ein Timeout-Problem? Oder ein Timing-Problem im Script?

Falls der Fehler an der RPC-Schnittstelle liegt: Wie kommt man an die Exception der Schnittstelle selbst?

**Comment by emkay82** [comment]
Ach, und da fällt mir ein...

Mir ist hier etwas aufgefallen:
```python
def build_api_url(host=REMOTES['default']['ip'],
                  port=REMOTES['default']['port'],
                  path=REMOTES['default']['port'],
                  username=None,
                  password=None,
                  ssl=False):
    """Build API URL from components."""
    credentials = make_http_credentials(username, password)
    scheme = 'http'
    if not path:
        path = ''
    if path and not path.startswith('/'):
        path = "/%s" % path
    if ssl:
        scheme += 's'
    return "%s://%s%s:%i%s" % (scheme, credentials, host, port, path)
```

Die Zeile `path=REMOTES['default']['port']` sollte `path=REMOTES['default']['path']` heißen, oder? Hab jetzt die nachfolgenden Verwendungen von `path` nicht geprüft, ist mir einfach nur ins Auge gesprungen.

**Comment by danielperna84** [comment]
Ich glaube so wie du das testest ist es nicht zielführend. Wobei du damit Recht haben könntest, dass das ein Timing-Problem ist.

Was bei deinem Test passiert ist, dass die Verbindung zur CCU aufgebaut wird, und direkt `createDeviceObjects` ausgeführt wird. Das wird deshalb gemacht, weil theoretisch die ganzen Device-Daten in einer Datei gecached werden können. Machen wir in der Praxis aber nicht. Dennoch wird deshalb direkt beim Start die Methode aufgerufen. Die Liste der bekannten Devices ist an dieser Stelle aber noch leer. Welche es gibt teilt die CCU erst später mittels callback mit. Da wird dann die `newDevices` Methode aufgerufen, welche nochmals das `createDeviceObjects` ausführt.
Weil du nun deinen Test-Code an einer Stelle stehen hast die ausgeführt wird bevor geschaut wird ob es überhaupt schon Devices gibt, gibt es bei dir 2 "Durchläufe". Wobei der Durchlauf hier eigentlich nur die Abfrage des Paramsets ist.

An dieser Stelle hast du dann vermutlich auch Recht was das Timing angeht. Grundsätzlich ist es so, dass die CCU (im Sinne der XML-RPC API) nur sehr schlecht mit parallelen Aufgaben klar kommt. Wenn da also noch von vorher eine Anfrage in der Luft hängt und gleichzeitig das `getParamset` aufgerufen wird, dann entsteht daraus ggf. ein Konflikt.

Ich hatte ja zum Vergleich das Wired Gerät gezeigt. Das habe ich selbst nie getestet, sondern jemandem der es hat dabei geholfen. Seiner aussage nach war alles in Ordnung. Es kann aber durchaus sein, dass er seine Kanäle nie anders konfiguriert hat, und somit ein fehlgeschlagenes Auslesen vom Paramset keine Auswirkung gezeigt hat.

Kurzfristig kann ich hier erst mal keine Lösung anbieten. Da muss wahrscheinlich irgendein Locking-Mechanismus rein damit dich zu viel gleichzeitig passiert. An sich ist die ausgehende Kommunikation schon mit dem `LockingServerProxy` abgesichert. Aber das greift vermutlich nicht, wenn Daten von der CCU bei pyhomematic ankommen.

Generell noch ein Tip:
```python
try:
    a = int("a")
except Exception as err:
    print(err)
```

So siehst du immer die genauen Fehler die passieren. Damit bekomme ich `ERROR: <Fault -1: 'Generic error'>` bei deinem Testscript.

Zu deiner Anmerkung mit dem `path`: Stimmt! Danke.

**Comment by emkay82** [comment]
> Ich glaube so wie du das testest ist es nicht zielführend.

Hahaha, den Eindruck habe ich ehrlich gesagt auch...zumindest sehr mühsam. Ich erwähnte ja bereits, dass ich mit Python nicht so viel am Hut habe. Wenn ich mal etwas schreibe - und das passiert jetzt nicht sooo häufig - dann mache ich dass i.d.R. in Visual Studio und auch nicht in Python. Was eine geeignete IDE für Python angeht, habe ich irgendwie keinen Einstieg gefunden und quäle mich seither mit Kommandozeile und Notepad++ herum. Ja, Python wird mittlerweile auch von Visual Studio unterstützt, aber das läuft irgendwie nicht sauber...mit nahezu 100%iger Wahrscheinlichkeit, sitzt das Problem hier vor dem Monitor. Vielleicht verrätst du mir ja, wie deine IDE zusammengesetzt ist?


> So siehst du immer die genauen Fehler die passieren.

Hatte ich bei meinen Tests drin. Da es sich um den gleichen Fehler handelt, wie bei [meinem eigentlichen Problem](https://github.com/danielperna84/pyhomematic/issues/210#issuecomment-459783881), und ich in der Ausgabe primär den Ablauf visualisieren wollte, habe ich es rausgenommen.


> Zu deiner Anmerkung mit dem `path`: Stimmt! Danke.

Super! Wenigstens ein kleines Erfolgserlebnis :-D


> Für dich interessant wäre in diesem Fall wohl `hmserver.log`

Top! Vielen Dank! Genau das habe ich gesucht. `<Fault -1: 'Generic error'>` ist einfach nichtssagend.


Danke nochmal für deine Mühe!

**Comment by danielperna84** [comment]
> Vielleicht verrätst du mir ja, wie deine IDE zusammengesetzt ist?

Ich benutze [Visual Studio Code](https://code.visualstudio.com/). Ist kostenlos, und es gibt eine Python Extension dafür die beim speichern den Code auch nach Fehlern überprüft.

Mitllerweile gibt es noch ein ähnliches Issue: https://github.com/danielperna84/pyhomematic/issues/219
Das scheint ein generelles Problem mit HmIP zu sein. In dem anderen Issue habe ich noch was dazu geschrieben was ggf. hilft der Ursache auf die Spur zu kommen (Stichwort: `strace`). Ich bin fast so weit zu behaupten, dass das ein Bug im Code der CCU ist.
