### ISSUE TITLE
HMIP-SMO does not have SABOTAGE

### ISSUE THREAD

**Issue by dagobert** [danielperna84/pyhomematic#212]
**Home Assistant version (if applicable):**
0.86.4

**Problem-relevant `configuration.yaml` entries and steps to reproduce:**
none

Use the following configuration for debug-output of the related components:

`HMGeneric.getValue: SABOTAGE on xxxxxxxxxxxxxxxx:0 Exception: <Fault -5: 'Unknown Parameter for value key: SABOTAGE'>`

**Describe the bug**
Home Assistant produces this error on startup.

**Additional context**
I guess this Sensor does not have a saboage alarm.

**Comment by danielperna84** [comment]
You're right. I have fixed it.

**Comment by dagobert** [comment]
Thanks
