### ISSUE TITLE
HMIP-eTRV writenode for actual_temperature and window state open/close

### ISSUE THREAD

**Issue by dl9msr** [danielperna84/pyhomematic#220]
Hello,
HMIP-eTRV and HMIP-eTRV-2 devices are connected to SmarthomeNG via homematic plugin based on pyhomematic.
I can receive data from the devices and send SET_POINT_TEMPERATURE

To send current temperature from another room sensor I need a writenode variable for a receive channel also for a window open/close state

Is there a solution for this?

Greetings
Michael

**Comment by danielperna84** [comment]
If I understand you correctly, then you have to implement this with the logic SmarthomeNG provides. pyhomematic is only a wrapper to allow communication. It's not possible to override the `current_temperature` of thermostats, as it would revert back to the sensor-value every time it gets updated. So you have to take care of this manually.
