### ISSUE TITLE
Get battery state of push button device

### ISSUE THREAD

**Issue by sander76** [danielperna84/pyhomematic#231]
Button-like devices like [this one](https://www.homematic-ip.com/en/products/detail/homematic-ip-wall-mount-remote-control-6-buttons.html) don't appear as devices in hass. They do emit events like described [here](https://www.home-assistant.io/components/homematic/#devices-with-buttons) .

I am not sure but it seems the above does not allow to monitor battery level of such a device (and thus notify a user when empty). Which could be a very much wanted feature (as hass will now be the only user interface to HMIP and HmIP devices almost all being battery operated.)

Great work btw!

**Comment by danielperna84** [comment]
You are right, attributes like the battery or RSSI can't be monitored this way. I guess we'd need some kind of dummy entity type for those devices. 🤔

**Comment by sander76** [comment]
Something like that. Or always fire an empty battery event into the hass system together with device info/identity (regardless of which hmip product). This could then be used as a trigger on an automation notifying the user. Which I think you -as a user- would almost always want as empty batteries suck...

**Comment by sander76** [comment]
@danielperna84 What do you think about my last suggestion? I am happy to do a PR on this.

**Comment by danielperna84** [comment]
Sounds reasonable. That way we could actually get rid of the attribute altogether in a later release and just use the events for low batteries. Just make sure you include all known variants (`LOWBAT`, `LOW_BAT` etc.).
I do think though, that the battery level some devices report should remain the way it is. The value also gets reported with fresh batteries. So in this case an additional sensor to parse the value is still needed.

I assume this is only done in the Home Assistant code, so tag me in your PR so I can have a look at it. And please include a demo automation for those lowbat events.

**Comment by sander76** [comment]
@danielperna84 I was thinking something like this:

https://github.com/sander76/home-assistant/blob/hm_low_bat/homeassistant/components/homematic/__init__.py#L589

**Comment by danielperna84** [comment]
Yeah, that looks like a smart solution. Feel free to open the PR.

**Comment by sander76** [comment]
@danielperna84 Have a look below for the changed docs:

https://github.com/sander76/home-assistant.github.io/commit/17632357190f4f7858575db55868fc0aa48661b3

**Comment by sander76** [comment]
@danielperna84 
For your info:

https://github.com/home-assistant/home-assistant/pull/22594
https://github.com/home-assistant/home-assistant.io/pull/9083

**Comment by sander76** [comment]
@danielperna84 Second try. Now by adding battery binary sensors for hm battery operated devices.
Tried to do it with the least amount of messing around with you code.

https://github.com/home-assistant/home-assistant/compare/dev...sander76:hm_battery_device

**Comment by danielperna84** [comment]
I assume this can be closed now that the battery sensors are implemented?
