### ISSUE TITLE
Autodetection of temperature sensor for classes 'Thermostat' and 'IPThermostat'.

### ISSUE THREAD

**Issue by DieterChmod** [danielperna84/pyhomematic#234]
**Is your feature request related to a problem? Please describe.**
For the device classes Thermostat and IPThermostat the temperature sensor is not autodetected.

**Describe the solution you'd like**
Simply add 'Thermostat' and 'IPThermostat' to DISCOVER_SENSORS and HM_IGNORE_DISCOVERY_NODE_EXCEPTIONS in `__init__.py` of homematic component in homeassistant.

**Describe alternatives you've considered**
Not necessary. This is already working perfectly on my machine.

**Additional context**
I tried to do this via a pull request to homeassistant dev branch, but I'm not yet familiar with TOX. So I thought, you're the right person to push for it.
Thanks a lot for the effort.

**Comment by danielperna84** [comment]
Climate entities provides a `current_temperature` attribute by default. At least my HomeMatic Thermostats have these as well. Are they missing for yours? We shouldn't generate additional entities for information that's already available.

**Comment by DieterChmod** [comment]
Nice to hear from you. Sure, temperature is available as an attribute.
I just wanted to align the behavior across all thermostats. Currently it is a mixture.
ThermostatWall, IPThermostatWall and IPThermostatWall2 also have temperature as attribute, but they also instantiate a temperature sensor via autodetection, Thermostat and IPThermostat don't.
If you don't have a wall thermostat in every room it is strange if there is no temperature sensor.

I know, you can always create your own sensor, but I find it very convenient to have temperature sensors to be autodetected. Maybe it is only a personal preference.

Hope I could convince you. :)

**Comment by danielperna84** [comment]
This would actually be an architectual question for Home Assistant. In my opinion it's incorrect that some thermostats generate those entities. It is different with thermostats that also include humidity sensors. Climate entities don't have humidity by default, hence in these cases we generate the entity. But for the current temperature it shouldn't be like that in my opinion.
Look at it this way: not everybody requires extra entities for the temperature. But everybody that does has the possibility of creating the sensor. Technically this generates less overhead Home Assistant has to work with than by default generating the entities, even if they are not needed.

**Comment by DieterChmod** [comment]
Ah... got it. I wasn't aware, that this was especially meant for the humidity sensors. Makes sense.

However, it is still mixed in this case. Then I would propose to remove `IPThermostatWall` and `IPThermostatWall2` from HM_IGNORE_DISCOVERY_NODE_EXCEPTIONS, since it automatically creates temperature sensors for the IP wall thermostats but it doesn't for non-IP ones.

What do you think?

**Comment by danielperna84** [comment]
Honestly, I actually don't want to touch this if it can be avoided. Yes, currently it is inconsistent. But removing the sensors for devices where they currently are present would result in a breaking change for those users. The way it is now a few users just are _lucky_ to have those extra sensors.
We could generate warnings while the entities are created, telling the users that these sensors will be removed in a future release, and then after a couple of releases remove the sensors. But I don't recall entirely why those node exceptions where introduced in the first place. And I don't want to break that as well. That's why I'm hesitant in touching something that in general is working.

**Comment by DieterChmod** [comment]
Alright. No worries. :)
