### ISSUE TITLE
Adding support for HmIP-PCBS-BAT

### ISSUE THREAD

**Issue by martykiico** [danielperna84/pyhomematic#235]
Ich bitte um Unterstützung für HmIP-PCBS-BAT. Unter supported devices ist der HmIP-PCBS als unterstützt angegeben, jedoch wird der "-BAT" somit nicht erkannt.

Gist: [https://gist.github.com/martykiico/cac179256d35ba1e2ec63a39d089056c](url)

![grafik](https://user-images.githubusercontent.com/34889193/54588956-aa6c1980-4a24-11e9-8d05-8fa8badef9ca.png)

**Comment by danielperna84** [comment]
Ich bin die nächsten Wochen privat sehr beschäftigt. Ich kann das also leider kurzfristig nicht bearbeiten. Aber vielleicht nimmt sich jemand die Zeit für die Implementierung. Falls nicht, dann werde ich etwa ab Mai die Zeit dazu finden.

**Comment by danielperna84** [comment]
Have you tried copying this line:
https://github.com/danielperna84/pyhomematic/blob/8b91f3e84c83f05d289c740d507293a0d6759d8e/pyhomematic/devicetypes/actors.py#L705
and adding the name of your device? Apart from that week-mode thing it should work.

**Comment by martykiico** [comment]
bekomme ich das mit custom_components/pyhomematic/devicetypes/actors.py auch hin? Habe keine Testumgebung aktuell.

**Comment by danielperna84** [comment]
Nein, ein custom component bringt hier nichts. Die Änderung ist ja nicht im component, sondern in der pyhomematic library. Bei hassio kann man da nix machen. Wenn du manuell installiert hast, dann kannst du schauen wohin die library installiert wurde und die Änderung dort machen.

**Comment by derfloh** [comment]
I've added 
"HmIP-PCBS-BAT": IPSwitch, 
to actors.py and as far as I can tell, everything works as expected.
