### ISSUE TITLE
Party/holiday (away) mode of HmIP WTH-2 & eTRV-2 & Home Assistant

### ISSUE THREAD

**Issue by dfigus** [danielperna84/pyhomematic#243]
**Home Assistant version (if applicable):**
0.92.1

I'm running pivCCU3 3.45.7-23 and Home Assistant 0.92.1 with the homematic integration. When I set the party/holiday mode in the CCU3, it's not correctly reflected in HA. 

I'm running HmIP-WTH-2 and HmIP-eTRV-2 - standalone and as part of a HmIP group in CCU3. When I set the party/holiday mode in CCU3, the holiday mode icon is shown correctly on the HmIP-WTH-2. However in Home Assistant the card shows "away", but I cannot select the "away" mode in the drop down

Example of a group:
![HA_climate_card](https://user-images.githubusercontent.com/10271668/56952158-eae9a780-6b39-11e9-8e7b-4d3d9a505295.PNG)

Entity in Home Assistant:
`{
  "temperature": 15,
  "current_temperature": 20.7,
  "operation_mode": "away",
  "operation_list": [
    "manual",
    "auto",
    "boost"
  ],
  "id": "INT0000002",
  "voltage": "",
  "max_temp": 30.5,
  "interface": "groups",
  "mode": null,
  "min_temp": 4.5,
  "valve": 4,
  "level": 0,
  "battery": "High",
  "supported_features": 129,
  "friendly_name": "Arbeitszimmer"
}`
![HA_climate](https://user-images.githubusercontent.com/10271668/56952378-85e28180-6b3a-11e9-962c-f4be6cd7891c.PNG)

So somehow the HmIP devices support the party/holiday (away) mode, but it seems to work only partially.

**Comment by pvizeli** [comment]
We can support the party/away mode but that is very complex to handle on API itself. I never found out how we can do that. Currently, it's simpler to create automation on Home Assistant

**Comment by danielperna84** [comment]
This probably is fixed with the [new integration](https://github.com/danielperna84/custom_homematic).
