### ISSUE TITLE
HmIP-MOD-TM Befehl absetzen scheitert

### ISSUE THREAD

**Issue by martykiico** [danielperna84/pyhomematic#247]
Das Ganze hat bis jetzt funktioniert. Ich kann leider keinen Command mehr absetzen:
Der Status wird gelesen und mir auch angezeigt:
per Automation setze ich folgenden Befehl ab:

> homematic.set_device_value

`{
  "address": "001E59XXXAFAC4",
  "channel": 1,
  "param": "DOOR_COMMAND",
  "value": 1
}`

Fehler im LOG ist folgender:
> HMGeneric.setValue: DOOR_COMMAND on 001E59XXXAFAC4:1 Exception: <Fault -1: 'Generic error'>

die einzige Veränderung sind Updates von HASSIO. Bin auf V 0.95

Verwunderlich ist einfach dass alle Veränderungen (Positionen, Lichtstatus etc.) gelesen werden können.

**Comment by danielperna84** [comment]
Vielleicht hängt es mit dieser Änderung zusammen: https://github.com/home-assistant/home-assistant/commit/ca2a68217da48634bf7216a985c777454ab9921f
Versuch' also mal ob es klappt, wenn du `"value_type":"int"` mit in den Service-Aufruf packst.

Bitte bescheid geben, wenn das die Lösung für das Problem ist. Eigentlich müsste die [services.yaml](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/homematic/services.yaml) noch aktualisiert werden damit das klar wird. Und eigentlich hätte das dann als breaking change markiert werden müssen. :-/

**Comment by martykiico** [comment]
Test mit folgenden Daten:

`{
  "address": "001E59XXXAFAC4",
  "channel": 1,
  "param": "DOOR_COMMAND",
  "value_type": "int",
  "value": 4
}`

hier passiert leider nichts

Fehler weiterhin:

> HMGeneric.setValue: DOOR_COMMAND on 001E5932FAFAC4:1 Exception: <Fault -1: 'Generic error'>

**Comment by danielperna84** [comment]
Hhmm, keine Ahnung was hier das Problem sein könnte. Versuch' mal manuell in einer Python 3 Shell:

```python
from xmlrpc.client import ServerProxy
p = ServerProxy("http://1.2.3.4:2010") # 1.2.3.4 ist die IP von deiner CCU
p.setValue("001E59XXXXFAC4:1", "DOOR_COMMAND", 4)
```
Das ist das, was pyhomematic, angefordert durch den `set_device_value`service, macht. Wenn das auch in der Python Shell nicht klappt, dann hast du irgendein anderes Problem.

**Comment by martykiico** [comment]
Die Ausgabe sieht komisch aus:

> ================= RESTART: C:\Users\star\Desktop\bla.py =================
Traceback (most recent call last):
  File "C:\Users\star\Desktop\bla.py", line 3, in <module>
    p.setValue("001E593XXXXAC4:1", "DOOR_COMMAND", 4)
  File "C:\Users\star\AppData\Local\Programs\Python\Python37-32\lib\xmlrpc\client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "C:\Users\star\AppData\Local\Programs\Python\Python37-32\lib\xmlrpc\client.py", line 1452, in __request
    verbose=self.__verbose
  File "C:\Users\star\AppData\Local\Programs\Python\Python37-32\lib\xmlrpc\client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "C:\Users\star\AppData\Local\Programs\Python\Python37-32\lib\xmlrpc\client.py", line 1170, in single_request
    return self.parse_response(resp)
  File "C:\Users\star\AppData\Local\Programs\Python\Python37-32\lib\xmlrpc\client.py", line 1342, in parse_response
    return u.close()
  File "C:\Users\star\AppData\Local\Programs\Python\Python37-32\lib\xmlrpc\client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -1: 'Generic error'>
>>> 


hab ich die Befehle falsch ausgeführt?

**Comment by martykiico** [comment]
CCU neugestartet, upgedated und geht wieder. Danke

**Comment by danielperna84** [comment]
Der Befehl war übrigens richtig. In der letzten Zeile ist ja dieselbe Fehlermeldung. Im Kontext von Home Assistant / pyhomematic wird der ganze Kram drum herum "ausgeblendet".
