### ISSUE TITLE
Inconsistent battery reporting (LOWBAT vs. BATTERY_STATE)

### ISSUE THREAD

**Issue by klada** [danielperna84/pyhomematic#248]
**Home Assistant version (if applicable):**

0.95.4

**Describe the bug**

On some devices the HASS `battery` attribute is a string (High/Low) and on some devices it's a float representing the current voltage. This makes dealing with these values kind of ugly in automations.

**Expected behavior**

The actual type of the value (float vs. string) should not change across HM devices.

**Ideas**

The problem is that both the `LOWBAT` and the `BATTERY_STATE` are mapped to `battery` in Home Assistant. Maybe it would be better to separate the two attributes. Some possible options:

   - Make a backwards-incompatible change and split up the two attributes into `low_batt` and `battery_state` (just like the rssi_peer/rssi_device thing from a while ago) → breaks all setups.
   - Keep current behavior for `battery` attribute and introduce two new attributes: `low_batt` and `battery_state` → current setups keep working, but introduces redundancy.
   - Only map `low_batt` to `battery` and introduce `battery_state` as a new attribute → some setups keep working, some will break.

What do you think?

**Comment by danielperna84** [comment]
This would actually be a change in Home Assistant, not pyhomematic. pyhomematic is just a wrapper library that doesn't apply any logic. The parameters you mention internally use different names as well. So the source of the problem are the devices themselves.  

That being said, there recently has been a change where additional binary sensors for the battery state are now created. It just doesn't cover the whole pallette of battery operated devices. But it makes the inconsistent attributes irrelevant. So in my opinion the correct solution would be to improve this approach to include more devices. But again, that would be a change in Home Assistant, and I wasn't really involved in this process.

Personally, I don't really like the new binary sensors. I would favour a solution that makes use of the service messages that we receive from the CCU / Homegear and create a dedicated notification. At least I don't _monitor_ battery states at all. I just check if I have service messages (send a notification to my phone), and if so, look at them in the CCU, and if it's a low battery I change it.

**Comment by klada** [comment]
You are right that this is pretty much a HASS-only issue. However I always thought that this project was also the place where some HASS-related Homematic things were discussed. I am kind of surprised that you were not involved in the battery binary sensor thing... :thinking: 

Anyway, you may close this issue. Let's see how HASS behaves if some devices have both battery attributes exposed through pyhomematic (see #249), because that's when things get messy.

**Comment by danielperna84** [comment]
Yes, typically that's right. But I'm not that deeply involved in how Home Assistant progresses. So the feedback of core HA-devs is necessary to implement such changes efficiently. Here none of the HA-devs see what's going on.

Here's the PR for Home Assistant that made the battery-entities available: https://github.com/home-assistant/home-assistant/pull/23793

At first glance it seems as if this will only support binary sensors. Ideally the `HMBatterySensor` class in the binary sensor platform code should be available for all device types. So it probably needs to be moved to the component-code, and then imported by each platform.
