### ISSUE TITLE
Linking devices from Home Assistant

### ISSUE THREAD

**Issue by Martwall** [danielperna84/pyhomematic#251]
**Is your feature request related to a problem? Please describe.**
I would like to handle linking (and unlinking) devices from Home Assistant and also see if devices are linked to each other in Home Assistant. One of the benefits with having a heat control system is the ability for wall thermostats to control the radiator thermostats depending on the measured temperature in the room. I do not believe there is any option for that but please let me know if I have missed some option for setting links.

**Describe the solution you'd like**
A service in Home Assistant for each of the methods; `addLink` and `removeLink` or a combined service for the two where the action could be specified as a param. Perhaps also an attribute like "children" and "parent" to see a list of linked devices for a specific device. This would probably have to include a `getLinks` method in Pyhomematic. 

**Describe alternatives you've considered**
The set_temperature for a RTV could be set based on the current temperature measured by the wall thermostat. The problem with this approach would be that the control algorithms that Homematic uses when a link has been established would be lost and that it could be troublesome keep track of all devices and controls in the automation. 

The link could of course be set on the CCU but then it can not be used in automations and there would be no information in Home Assistant that the link is established. There is also the aspect of trying to use the CCU as little as possible to only having to use Home Assistant for heat control.   

I would definitely help out/do the implementation if it is decided that it is a requested feature!

**Comment by danielperna84** [comment]
Are you aware, that you get the linked devices into Home Assistant by adding an additional interface? It's mentioned [here](https://www.home-assistant.io/components/homematic#port).

Would look something like that:
```
homematic:
  interfaces:
    groups:
      host: 1.2.3.4
      port: 9292
      path: /groups
```

The climate entities you get are the _virtual_ thermostat groups you see in the CCU.

The process of linking the devices won't be integrated into Home Assistant for sure. Doing that with service calls is way to complicated, whereas it's just a few clicks on the CCU (or other GUI for Homegear / hassio). I'm always open for adding new features that help with automating. But the topic your talking about is setting up the infrastructure. You only do that once. As soon as it's configured you never touch it again. And you probably won't ever add or remove links on the fly within automations. So even though for theoretical completeness it might make sense, it's not worth the effort in my opinion. It can be done already, just not in the same UI. But that's the same with a lot of other products.

**Comment by Martwall** [comment]
Alright, I did not know about the group option so I will try that for getting the linked devices, thanks. 

When you say it's just a few clicks on other GUI you mention "hassio" what do you mean by that? 

I do agree that it would not change often. I was planning on using it to auto link RTVs that are assigned to the same room as a WT using automation or the like in Home Assistant. But as you say perhaps it is to much work for such a thing.

**Comment by danielperna84** [comment]
> When you say it's just a few clicks on other GUI you mention "hassio" what do you mean by that?

If you use hassio instead of a standalone installation, then there's an add-on which can use the rf-modules you can put on raspberry pies. In such a setup you don't need a CCU anymore because hassio acts as one. But to do administration you also need a configuration-program that handles pairing of devices etc.. So even in this case with deeper integration into Home Assistant we still rely on 3rd party software to set up the devices.

Your plan to use an automation would only make sense if you would move a device into different rooms from time to time. But besides having to (re)link devices whenever that happens, that would also always break automations that depend on these devices. A _stable_ setup would be to have a dedicated thermostat for each relevant room and leave it there.

**Comment by Martwall** [comment]
Alright yes I did try the setup with the rf-modules but it is not really a straight forward experience with the third party software so was thinking a Home Assistant/Pyhomematic integration could help out with that. 

Yes that is true but it would make for the possibility to not interact with the ccu/third party software which would be nice.

Thanks for your responses and commenting on the issue!
