### ISSUE TITLE
Add support for integrated LEDs in HmIP-BSL device

### ISSUE THREAD

**Issue by guillempages** [danielperna84/pyhomematic#255]
I have one of the Homematic IP Switches with embeded LEDs, that I ca control now via HASS (thanks to Issue #200).

I would also like to be able to control the lights on the device itself as well, for example to use it as a night light depending on the sun's state.

From the discussion in issue #200, seems that the problem is that the device does not support RGB setting for the color, just some fixed values. Could it be possible to use the standard interfaces (i.e. RGB) and have some sort of mapping table/conversion function for the fixed colors? 

I've tried looking at the code myself, but python is not my most fluent language, and my time to look into this is unfortunately also very limited.

**Comment by danielperna84** [comment]
If I understand you correctly, then theoretically it would be possible. But that would be a lot of effort for a very limited use case. Usually automations would be used to change light, which I believe is possible with device already by using the [device_set_value](https://www.home-assistant.io/components/homematic/#services) service. Introducing the color mapping would only be useful for setting the color via the UI. Some people might do that. But I think the majority will depend on the automations.

If you really want to do it via UI you could also just create an [input_select](https://www.home-assistant.io/components/input_select/) with all the colors mapped to the service-calls.

**Comment by guillempages** [comment]
OK, maybe it was my misunderstanding. I was expecting to have some entity in home-assistant, that I can control like a normal light. I'll try the set_device_value service; I just thought it would be nice for the LED (actually the two of them) to be usable like other homeassistant devices.

Is there a way of reading the value? For e.g. showing it some UI?

**Comment by guillempages** [comment]
Thanks for the tip with set_device_value. After som etrial-and-error, I managed to set the color and the dim value.
Nevertheless, it would be nice if at some point, the two leds would appear as lights in homeassistant; even if the color cannot be set. I don't know how to add them in the (pyhomematic?) code so that this shows up; if there would be a special kind of device that does that, I could try adding the color mapping part.

**Comment by danielperna84** [comment]
Could you please share the working commands and what they do? Also include how to turn on/off in general, and what happens if you set a color when it is off. According to another post there is actually _BLACK_ as a coloroption. Does that turn the light off? And how does controlling brightness work?

As mentioned in the other thread: There are only 8 colors available in an integer ENUM field (BLACK, BLUE, GREEN, TURQUOISE, RED, PURPLE, YELLOW, WHITE)

I assume _turquoise_ and _purple_ are actually badly named should be _cyan_ and _magenta_. All the other colors match RGB and CMYK. So for a mapping I came up with this short snippet:

```python
def hs_to_colorname(h, s):
    if s == 0:
        return 'WHITE'
    if h in range(30,89):
        return 'YELLOW'
    elif h in range(90,149):
        return 'GREEN'
    elif h in range(150,209):
        return 'TURQUOISE' # actually cyan
    elif h in range(210,269):
        return 'BLUE'
    elif h in range(270,329):
        return 'PURPLE' # actually magenta
    else:
        return 'RED'
```

**Comment by guillempages** [comment]
I've tested the "LEVEL" command (to set the brightness) and "COLOR" command to set the color.

If you only set the color when it is off, it doesn't turn it on; it stores the color for the next time that you set a brightness. To turn it on and off, I used the brightness ("LEVEL"); between 0 and 1. That was something I struggled a bit, until I found out that it must be a float.

The color BLACK actually turns the LED off, but keeps the previous brightness level, in case you set another color again.

The real colors are not 100% perfect (from homematic side), e.g. IMHO "YELLOW" is more like "lime green". Or maybe I got one where the LEDs are not well calibrated. But yes, "TURQUOISE" is cyan, and "PURPLE" is magenta.

Regarding your code, you might want to use a range for the saturation; e.g `if s <=0.05: return 'WHITE'`, otherwise it might be difficult to get the exact point in the color wheel. (assuming the saturation is a float between 0 and 1). Just a suggestion; I'm not sure that 0.05 is the right value for that.

The channels to set the LEDs are 8 and 12 (the corresponding sensors for reading the status are channels 7 and 11, but maybe the 8 and 12 can be read as well).

From my automation yaml file (in homeassistant):
``` yaml
  - service: homematic.set_device_value
    data:
      address: "001A5Axxxxxxxx"
      channel: 8
      param: "LEVEL"
      value: 0.2
  - service: homematic.set_device_value
    data:
      address: "001A5Axxxxxxxx"
      channel: 8
      param: "COLOR"
      value: "WHITE"
```

**Comment by danielperna84** [comment]
Please add the changes in [this](https://github.com/danielperna84/pyhomematic/pull/259) PR to your installation and add `IPKeySwitchLevel` to [this](https://github.com/home-assistant/home-assistant/blob/89ebc17fb139c4ded65fc717a094d8a9038f052c/homeassistant/components/homematic/__init__.py#L92) list. If everything works as intended, you should get two light entities in Home Assistant for which you can control brightness. Once we have this working we can see how to control the color in the future.

**Comment by guillempages** [comment]
Unfortunately, it did not work. Further comments in the [PR](https://github.com/danielperna84/pyhomematic/pull/259).

**Comment by guillempages** [comment]
I've done a (rudimentary) implementation of the color setting and got it working in HA (with all changes mentioned in the [PR](https://github.com/danielperna84/pyhomematic/pull/259). 
I have the problem, that the "get_hs_color" and "set_hs_color" methods do not give me the channel as parameter, so I don't know how to get which HA entity was currently selected. I hard-coded it to channel 8 for my tests, and was able to write and read the colors.

I tried doing a new PR, but I still don't have the rights (or I'm not doing it the right way). Should I paste my code here?

**Comment by danielperna84** [comment]
> I tried doing a new PR, but I still don't have the rights (or I'm not doing it the right way). Should I paste my code here?

Usually you just fork this repo into your account, clone __your__ fork, create a new branch with your changes, commit and push to __your__ fork, then create a PR from your fork to this repo. 👍
