### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by danielperna84** [danielperna84/pyhomematic#266]
To solve the issue we came across [here](https://github.com/home-assistant/home-assistant/pull/27307) we need to make some changes in pyhomematic. This issue serves as a platform for disussions on a robust solution.

While at it, we also need to implement caching of paramsets to increase startup-performance. Maybe even values of nodes to put even less stress on the CCU during startup.

**Comment by danielperna84** [comment]
I have started a new project to handle the refactoring: [hahomematic](https://github.com/danielperna84/hahomematic)

Most of the work is already done. As soon as I have figured out how to implement custom devices, I will need help by those who have already implemented devices for pyhomematic.

I also need help regarding the Home Assistant integration. [Here's](https://community.home-assistant.io/t/help-needed-for-new-homematic-integration/297151) my post in the community asking for support. Please have a look at it and report back if you are able to help!

If you want to help, head over to [this](https://github.com/danielperna84/hahomematic/issues/1) issue and tell me how you can contribute.

Tagging some pyhomematic contributors to get some attention. Feel free to ignore this if you won't be able to help.
@pvizeli @dagobert @klada @hanzoh @chr1st1ank @Munsio @DieterChmod @mcdeck @noxhirsch @ch-world @pascalhahn @bimbar @cyclingengineer @SukramJ @dickesW @i-am-steve-oh @PH89 @tringler @gethash @janbrummer @emkay82

**Comment by macrojames** [comment]
Somehow i missed that you already started the refactoring. I searched for this issue as I just looked into https://github.com/Koenkk/zigbee-herdsman-converters to analyze how they did implement a common interface for a myriad of different vendors and devices and I liked that concept.

Looking into hahomematic my first impression was you were focussing on the integration into HA, entity and device creation?
I am soon getting another yet unsupported HmIP device and wanted to try a new device definition.
If you could have a look into https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/devices/tuya.js
The interesting part for me was the device definitions with the properties `fingerprint`, `fromZigbee`,  `toZigbee` and `exposes`.
Those look really clean to me and would match many devices. They still have the option to perform customization per device and per property if there is no predefined match or a workaround ist needed.

I'd like to hear your opinion on that! I can't guarantee a contribution with hahomematic as it is tightly integrated with HA and I don't know a lot about their APIs but wanted to give the device mapping a try.

**Comment by danielperna84** [comment]
@macrojames 

I think you're mixing up protocols. HomeMatic does not use Zigbee. It's a proprietary protocol.

The way I have build hahomematic, it is fetching the paramset-descriptions (they contain all of the available parameters and their type for each channel), and then automatically creates default entities. [Here](https://github.com/danielperna84/hahomematic/blob/devel/hahomematic/device.py#L62) is where that's done.

For special devices where the default entities won't suffice I have chosen to provide the most possible flexibility on how the resulting entity should be created. I have already done that for thermostats [here](https://github.com/danielperna84/hahomematic/blob/devel/hahomematic/devices/climate.py). For other types the requirements could be different, and I believe that callback-approach mitigates any limits which could cause problems later on.

Essentially my goal is to provide _simple_ entities for every available, usable parameter, which would in theory allow control of all HomeMatic devices, even if there has been no device-specific integration. It would be a very _manual_ usage, but nonetheless better than it is now. And if required, a special entity (like _cover_ or _light_) can be created through the customization if someone implements it.

**Comment by danielperna84** [comment]
Closing this issue, as [hahomematic](https://github.com/danielperna84/hahomematic) now is under active development.
