### ISSUE TITLE
Keyerror when trying to access device data

### ISSUE THREAD

**Issue by mstuebner** [danielperna84/pyhomematic#268]
I just installed pyhomematic and tried to run the examples, i.e. the one at https://github.com/danielperna84/pyhomematic, but when I want to access one device I get an KeyError:

    pyhomematic = HMConnection(local="192.168.178.174", localport=7080,
                               remote="192.168.178.14", remoteport=2010,
                               systemcallback=syscb)  # Create server thread

    pyhomematic.devices['0010D8A990A3B7'].getValue("STATE")

    pyhomematic.devices['0010D8A990A3B7'].getValue("STATE")
    KeyError: '0010D8A990A3B7'

The address is correct as it is delivered by the script itself:

    newDevices
    pyhomematic-default
    [{'TYPE': 'HmIP-STHO-A', 'SUBTYPE': 'STHO', 'ADDRESS': '0010D8A990A3B7', ....

Running Python 3.8 & 3.7 with the same result.
What do I wrong?

**Comment by danielperna84** [comment]
Have a closer look at the [example](https://github.com/danielperna84/pyhomematic/blob/e3a6fa93de16f41a583666f00fe8eca458ed45e5/example.py#L61). There's always a channel appended to the device address. `:1` in the example. This is with using the `devices_all` attribute though. When using just the `devices` attribute the available methods you can use depend on how they are implemented for each device. [Here](https://github.com/danielperna84/pyhomematic/blob/e3a6fa93de16f41a583666f00fe8eca458ed45e5/pyhomematic/devicetypes/actors.py#L166) it's the `on` method that's available for switches.

Which channels and parameters can be used is different for every device. For HmIP devices you can have a look at [this](http://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/HmIP_Device_Documentation.pdf) documentation.

Please be aware, that pyhomematic is primarily intended for use with Home Assistant. So if you plan on using the module for personal projects, things might break for you unexpectedly.

**Comment by mstuebner** [comment]
Thanx for your hint regarding the channel.

    def systemcallback(src, *args):
        print(f'-----------------\nFunction: {src}')
        for arg in args:
            print(f'Arg: {arg}')

    try:
        pyhomematic = HMConnection(interface_id="myserver",
                                   local="192.168.178.174",
                                   localport=7080,
                                   remotes={'hmrf': {'ip': '192.168.178.14',
                                                     'port': 2001},
                                            'hmip': {'ip': '192.168.178.14',
                                                     'port': 2010}},
                                   autostart=True,
                                   systemcallback=systemcallback)

    except Exception:
        sys.exit(1)

    DEVICE3 = 'LEQ0776011'

    print(pyhomematic.devices_all[DEVICE3 + ':1'].getValue("STATE"))

This returns:

    Function: listDevices
    Arg: myserver-hmrf
    Traceback (most recent call last):
      File "D:/pydev/source/home_control/demos/pyhomematic-test.py", line 30, in <module>
        print(pyhomematic.devices_all[DEVICE3 + ':1'].getValue("STATE"))
    KeyError: 'LEQ0776011:1'

The message remains the same, including the channel number.
How to get this corrected?

**Comment by danielperna84** [comment]
Uhm, I think the example is outdated. Didn't notice that at first. Try `pyhomematic["hmrf"].devices_all[DEVICE3 + ':1'].getValue("STATE")`. The example is from the time where we didn't support multiple hosts. That's why it has to be included now.

**Comment by mstuebner** [comment]
When I set a breakpoint and inspect the dict I see that it looks like following

    {'hmrf':
        'LEQ0776011':...

Means that there is no channel number in the nested dict.

When I then try:

    print(pyhomematic.devices_all['hmrf'][DEVICE3].getValue("STATE"))

it fails if I just run it, it fails with the same KeyError, but:

    time.sleep(1)
    print(pyhomematic.devices_all['hmrf'][DEVICE3].getValue("STATE"))

returns a False (regardless if with or without a channel number. So does it require the massive use of sleep() and why does it return the same with or without channel?

**Comment by danielperna84** [comment]
It does require the sleep because depending on how many devices you have it can take a while to create all the device objects.

Apart from that I'll have to ask you to just have a look at the code to figure it out. I haven't used pyhomematic on that level in ages, so I'd have to lookup everything as well.  
I recommend to do what the example does in an interactive shell. There you can use the [dir](https://docs.python.org/3/library/functions.html#dir) function of python to inspect all the objects at runtime and try out different things without having to re-run the test-script all the time (which puts a lot of load on your CCU btw.).
