### ISSUE TITLE
Handle Homgears listMethods-implementation?

### ISSUE THREAD

**Issue by danielperna84** [danielperna84/pyhomematic#27]
When calling ListMethod, Homegear supplies an additional paramter, which the official XML-API does not. Should we implement or ignore this? The CCU won't send that extra parameter, so supporting HGs implementation could break the CCU. And since CCU is the official, I'm in favour of the current approach.

**Comment by Koshu** [comment]
Ignore it, because it will be fixed with the next version ;)
https://github.com/Homegear/Homegear/issues/256
