### ISSUE TITLE
IPThermostatWall230V Class for HmIP-BWTH outdated

### ISSUE THREAD

**Issue by dickesW** [danielperna84/pyhomematic#270]
Hi @danielperna84 ,

the IPThermostatWall230V class for the HmIP-BWTH seems to be outdated. I can see the temperature & humidity and change the temperature but not the modes.

If I change the class for the HmIP-BWTH to IPThermostatWall2
`"HmIP-BWTH": IPThermostatWall2` 
it works fine. Obviously there are errors for the OPERATING_VOLTAGE and LOW_BAT as there is none.

Is there a nice way to use the IPThermostatWall2 class and just remove the HelperLowBatIP.

thanks for your work and support!

**Comment by danielperna84** [comment]
As far as I can see only the `HmIP-BWTH` and `HmIP-BWTH24` are using the `IPThermostatWall230V`. So you could simply add to that class what is missing. Probably add `IPAreaThermostat` to the inheritance chain, and rebuild mode-related stuff to match how `IPThermostatWall2` does it.
