### ISSUE TITLE
Problem witch HMIP Devices on CCU3 with FW 3.51.6

### ISSUE THREAD

**Issue by Benni08** [danielperna84/pyhomematic#306]
Sorry for that Bad Question and my Bad English,

i've tried to get the pyhomematic working with a CCU3 and the Firmware Version 3.51.6. I'ved Installed the pyhomematic and tried to list all HMIP-Devices.

So I've just used the example and tried to get Connection on Port 2010.

I've got an empty Response from the CCU3.

On Port 2001 its working, but theres no Devices installed.

Is there an known Issue, because it seams like, the CCU3 are not working on Port2010. (Firewall granted everything. The Ports are even opened).

Kurz noch mal in Deutsch:
Ich habe richtige Probleme und bekomme auf Port 2010 eine leere Antwort, während auf Port 2001 mir die BidCos-RF devices angezeigt werden.
Als unterstützte HMIP devices sind zur Zeit mehrere HmIP-WTH-2 angeschlossen. Die HMIPw devices wollte ich später selber anlegen, aber es scheitert ja schon an der Verbindung.

Muss ich noch irgendetwas spezielles an der CCU3 einstellen, damit es funktioniert?

**Comment by danielperna84** [comment]
Auf Deutsch ist auch ok. ;-)
Ich selbst hab noch nicht auf 3.51.6 geupdated, kann also nicht sagen, ob es damit Probleme gibt. Ich gehe jedoch davon aus, dass schon längst jemand was gesagt hätte, wenn es prinzipiell Probleme mit der Version gäbe.

Verstehe ich das richtig, dass es nicht um eine Verbindung aus Home Assistant heraus geht, sondern dass du pyhomematic _manuell_ benutzt?
Grundsätzlich ist der HmIP-Server auf der CCU etwas zickig. Vor allem wenn er mehrere Verbindungen bearbeiten muss. Da kommt es manchmal vor, dass man die CCU neu starten muss damit das wieder sauber läuft. Das wäre also mein erster Vorschlag.
Da du HmIPW einbinden willst könnte dir das generell _um die Ohren_ fliegen. Du hast glaube ich das andere Issue zum HmIPW Support gesehen. Da ging es auch um das Problem, dass beim starten die Paramsets nicht mehr geholt werden konnten wenn man sich schon für die Events angemeldet hat. Solche Spielereien um zu sehen was ein Gerät kann funktionieren mit der aktuellen Architektur (für HmIP und HmIPW) schlichtweg leider nicht.

Wie dem auch sei, wenn du die CCU neu gestartet hast und das example-Skript immer noch nicht geht, dann könnte es z.B. auch an einem evtl. aktivierten SSL-Zertifikat liegen. Dann wäre der Port 42010 glaube ich.

Und eigentlich die wichtigste Frage: auf welche Anfrage bekommst du eine leere Antwort? `listDevices`?

**Comment by Benni08** [comment]
Ich habe bei mir ein SmarthomeNG mit Smartvisu aufgesetzt. Auch SmarthomeNG nutzt im Background pyhomematic um mit dem Homematic System zu kommunizieren. Ich bekam dort keine Devices angezeigt, daher habe ich mich mehr mit pyhomematic beschäftigt und vorerst hier kontrolliert, woran die fehlende Kommunikation liegen kann.

Bei meinen Tests bekam ich vorerst gar keine Ergebnisse, daher habe ich mich weiter mit der API-Schnittstelle beschäftigt und auch mal selber einen Clienten zur XML-API Abfrage in C# implementiert. Dabei konnte ich feststellen, dass ich am Port 2001 eine XML zurückbekomme, am Port 2010 kommt gar nichts zurück. Mein Testprogramm liefert mir einen leeren String, so dass vermutlich das Problem an der CCU3 oder meinen Einstellungen an der CCU3 liegt.

Ich habe mehrfach die CCU3 neugestartet, aber leider immer mit dem Ergebnis, dass eine HTTP-Anfrage mit der übergebenen Funktion listDevices eine leere Anfrage liefert. (C# Testprogram, als auch die example.py).

Testweise habe ich in den Sicherheitseinstellungen die Authorisierung für die API deaktiviert. Die Firewall ist geöffnet an der CCU3, die Ports habe ich trotzdem noch mal in den zu öffnenden Ports eingetragen.

Muss ich sonst noch eine Konfiguration an der CCU3 einstellen? Ich müsste doch zu mindestens am Port 2010 bei der Methode listDevices meine Wandthermostate angezeigt bzw. aufgelistet bekommen? SSL ist nicht aktiviert. Auch ein Test auf dem Port war negativ. 

Bin gerade ein bisschen hilflos, und ärgere mich, dass es bestimmt nur eine Kleinigkeit ist.

**Comment by danielperna84** [comment]
Wie das aus C# heraus geht weiß ich nicht. Generell ist aber zu beachten, dass das kein nacktes HTTP, sondern XML-RPC. Das ist also HTTP + bisschen was drum herum.

Der einfachste Test den du machen kannst (mit meinen Fähigkeiten als Grundlage) ist folgendes in einer Python 3 Shell einzugeben:
```python
from xmlrpc.client import ServerProxy
p = ServerProxy("http://1.2.3.4:2010")
p.listDevices()
```
Genau das macht pyhomematic, und wenn du stattdessen port `2000` nimmst solltest du auch die regulären Geräte sehen. Wenn du da bei Port `2010` weiterhin kein nützliches Ergebnis bekommst, dann weiß ich spontan auch nicht weiter. Ich würde in dem Fall mal im HomeMatic Forum fragen. Da gibt's im Entwicklerbereich auch einen Bereich, in dem es um XML-RPC geht. Vielleicht kann dort jemand mehr zu dem Problem sagen.

**Comment by Benni08** [comment]
Okay, das hat geholfen und so bekomme ich eine Ausgabe. 

Ich bekomme in der Rückgabe nun auch meine Raumthermostate angezeigt. 

Entweder verstehe ich nun die Example Datei falsch, oder durch die installierte Version werden die neuen Raumthermostate noch nicht unterstützt.

`print(pyhomematic.devices)`

Diese Zeile würde ich bei der example.py so verstehen, dass in der Consolenausgabe nun meine Raumthermostate angezeigt werden. Das ist aber leider so nicht der Fall.

Pyhomematic habe ich auf meiner VM so installiert:

`sudo pip3 install -U pyhomematic`

Kann ich bei dieser Installation irgendwie nachvollziehen, welche Version gezogen wurde und welche Devices unterstützt werden? (HmIP-WTH-2)

VG
Benjamin

**Comment by danielperna84** [comment]
> Kann ich bei dieser Installation irgendwie nachvollziehen, welche Version gezogen wurde und welche Devices unterstützt werden? (HmIP-WTH-2)

Im Prinzip schon. Schau mal ob es den Ordner `/usr/lib/python3.?/site-packages` gibt. Könnte auch `/usr/local/lib...` sein. Oder was ganz anderes wenn du ein `venv` benutzt hast. Wie dem auch sei, in diesem Ordner solltest du einmal den Modul-Ordner `pyhomematic` finden, sowie einen für Metadaten des Paketes der etwa so heißen würde: `pyhomematic-0.1.65.dist-info`. Das wäre die Versionsnummer. In dem anderen Ordner findest du die Struktur wie sie auch hier im Repo ist. Welche Thermostate unterstütz werden siehst du dann in `devicetypes/thermostats.py`.

**Comment by Benni08** [comment]
Sorry, hat ein bisschen länger gedauert.

Also... ganz komisch.
Die WRT sind vorhanden in den devicetypes. Die CCU liefert die Daten auf dem Port 2010. Trotzdem ist die Ausgabe von:

print(pyhomematic.devices)

bleibt leer, bzw. es kommt ein leeres Array mir rf.

**Comment by danielperna84** [comment]
> bzw. es kommt ein leeres Array mir rf.

So sollte es sein. Die Geräte sind je nach Host/Protokoll verteilt. Mit `print(pyhomematic.devices['rf'])` solltest du sie dann auch sehen. So kann man hinterher noch differenzieren, zu welcher Protokollfamilie ein bestimmtes Gerät gehört.

**Comment by danielperna84** [comment]
Ich nehme mal an dass alle Fragen geklärt sind, und es sich hierbei nicht um eine Fehlfunktion handelt. Insofern schließe ich das Issue.
