### ISSUE TITLE
Implement setting and getting system variables

### ISSUE THREAD

**Issue by danielperna84** [danielperna84/pyhomematic#31]
It might become useful to get or set system variables.

Homegear allows to do this via XML-RPC (getSystemVariable etc.): [XML RPC Method Reference](https://www.homegear.eu/index.php/XML_RPC_Method_Reference)
Unfortunately, the CCU does not provide this functionality, since it is not default XML-RPC. But here we can use JSON-RPC, The available methods are:
- SysVar.createBool
- SysVar.createFloat
- SysVar.deleteSysVarByName
- SysVar.get
- SysVar.getAll
- SysVar.getValueByName
- SysVar.setBool
- SysVar.setFloat

This requires user-level access. So the guest-account we use for resolving names is insufficient for this.

Possible problems:
- We don't know if we're talting to a CCU or homegear. Can we find out, or should this be a flag we provide when starting pyhoematic?
- When using JSON-RPC we need to take care of the session. For resolving names we create it, and when done close it again. To make use of the system variables we need to keep the sessoin alive, since opening and closing isn't efficient.

**Comment by danielperna84** [comment]
For now I chose to use JSON-RPC when a rpcusername and rpcpassword is configured. If not I try the Homegear method.
Furthermore I open and close the session for each interaction.

Use the _server-Attribute of the pyhomematic-object. Available methods are:

- getAllSystemVariables
- getSystemVariable(name)
- deleteSystemVariable(name)
- setSystemVariable(name, value)

With Homegear the variables can be pretty much anything JSON can transport, although you probably should stick to strings, booleans, integers and floats.
The CCU only supports variable modification via JSON-RPC for bool and float. And they have to be created within the CCU. pyhomematic only modifies existing variables and does not create them.

**Comment by danielperna84** [comment]
Would be nice if users with CCU could test this, since I only have Homegear running.

**Comment by TheFitzZZ** [comment]
As you asked I tried to test it, but my limited knowledge hinders me. 

I understand that I need to use JSON and set a user/pw for it. This already stopped me. I tried this:

`try:
    pyhomematic = HMConnection(interface_id="myserver",
                               local="192.168.0.145",
                               localport=7080,
                               remote="192.168.0.97",
                               remoteport=2001,
                               autostart=True,
                               systemcallback=systemcallback,
                               rpc_username="myuser",
                               rpc_password="mypw")
`

But that seems wrong. I you could hook me up with a quick example. maybe also for what I should test , I'll get back to you asap. 

Cheers

**Comment by danielperna84** [comment]
What exactly doesn't work? The only thing I can think of is a missing systemcallback function, which you don't need in this case anyway.

If you use the example from the README (which is what you see [here](https://github.com/danielperna84/pyhomematic) ) you should have everything you need. Although you can leave away the callbacks.

**Comment by danielperna84** [comment]
Probably done with de243c5.

**Comment by TheFitzZZ** [comment]
Sorry for the big delay - I now understood how to use it properly. 

Can confirm the functionality of all 4 methods against my CCU2, as well as the limitation to set only bool & float values.

As a documentation for others trying, this is my test-connection:
`    pyhomematic = HMConnection(interface_id="myserver",
                               local="192.168.yyy.yyy",
                               localport=7080,
                               remote="192.168.xxx.xxx",
                               remoteport=2001,
                               autostart=True,
                               systemcallback=systemcallback,
                               rpcusername="myuser",
                               rpcpassword="mypassword")
`

and this my test lines:

`
print(pyhomematic._server.getAllSystemVariables())
print(pyhomematic._server.getSystemVariable("Test 1"))
print(pyhomematic._server.setSystemVariable("Test 1", 1.67647))
print(pyhomematic._server.getSystemVariable("Test 1"))
print(pyhomematic._server.deleteSystemVariable("Test"))
print(pyhomematic._server.getSystemVariable("Test 1"))
`

@danielperna84 : as you may see now, I used rpc_username instead of rpcusername, that was my mistake. The lack of documentation is quite a hurdle for someone not as "knee deep" in the code - no offense of course. I hope my verification is still of value for you.

Kind regards

**Comment by danielperna84** [comment]
Verification always is a good thing. Different setups may lead to different results, so feedback is always welcome.
This functionality already is in the latest pyhomematic release, and HA-integration is in the works. So expect results soon.

**Comment by michaelotto** [comment]
I'm trying to use the getSystemVariable function, but unfortunately, it casts every value to either floats or booleans. I'm trying to read strings back from system variables. That isn't possible at the moment. Is there any reason for this limitation?

Best regards

**Comment by danielperna84** [comment]
@michaelotto 

As mentioned in the first post of this issue, the CCU only has methods to set boolean and float variables. Homegear has a method for strings I believe, but we didn't implemented this because the functionality pyhomematic provides should be available no matter which HomeMatic backend is being used.
Of course the CCU internally somehow works with string variables too. But they are not exposed via the JSON-RPC API. So there's at least no obvious way to tap into that.

**Comment by michaelotto** [comment]
Well, reading works without problems, I changed the code so at least getSystemVariable handle string sysvars.

But if setting a string-system variable isn't possible, this is of no use for me anyway.

I wonder how the XML RPC API manages to set string system variables (yes, it can do that).

**Comment by danielperna84** [comment]
> I wonder how the XML RPC API manages to set string system variables (yes, it can do that).

It's not documented in the API-reference. If it was, we would have implemented it.

**Comment by walsera** [comment]
Just a quick comment regarding string-type system variables:

The setSystemVariable method actually already works for setting string-type system variables on my CCU. Internally it uses SysVar.setFloat, which seems just to work with other data types as well.
