### ISSUE TITLE
HmIP-SWSD on piVCCU3: Siren control via hassio

### ISSUE THREAD

**Issue by cyablo** [danielperna84/pyhomematic#316]
Hi! I'm just migrating from FHEM to hass.io. For testing purposes I set up piVCCU3 with an HmIP-RFUSB and one paired HmIP-SWSD. Is there a way to forward the HmIP-SWSD's siren to hass.io as a switch device to turn it on and off from within hass.io?

Another thing: I get a few warnings in hass.io:

> Setup of homematic is taking over 10 seconds.
> <Fault -5: 'Unknown Parameter value for value key: LOW_BAT'>
> <Fault -5: 'Unknown Parameter value for value key: RSSI_DEVICE'>
> <Fault -5: 'Unknown Parameter value for value key: SMOKE_DETECTOR_ALARM_STATUS'>

Is this something to worry about?

**Comment by danielperna84** [comment]
The correct way to manually trigger the alarm is to use the `homematic.set_device_value` service with a payload like the following:

```yaml
address: 001122AABBCC
channel: 1
param: SMOKE_DETECTOR_COMMAND
value: 2
```

The value `2` turns the alarm on, `1` turns it of. This is for the _intrusion alarm_. To turn off the _smoke alarm_ you have to use the value `0`. The value `3` would start a _smoke alarm test_, but I don't know if this would automatically be forwarded to other devices, and how long it would stay active. Feel free to report your observation.

With that knowledge you can create an [imput_select](https://www.home-assistant.io/integrations/input_select/) to display the options you want to use, and then use the selected option within an automation the control the siren.

**Comment by cyablo** [comment]
I've tried 0, 1 and 2 which do work. As a feature request, I thought it might be easier if the interface would provide a dedicated switch device for turning the alarm on and off, like the ZigBee Smoke detectors with controllable siren do.

What about the warnings? Are they normal?

**Comment by danielperna84** [comment]
This should now be possible with the [new integration](https://github.com/danielperna84/custom_homematic).
