### ISSUE TITLE
Allow firing of PRESS_SHORT and PRESS_LONG events for devices

### ISSUE THREAD

**Issue by danielperna84** [danielperna84/pyhomematic#32]
It may make sense to allow firing of PRESS_SHORT and PRESS_LONG events. The CCU provides 50 virtual (by us currently not supported) buttons, which we could trigger manually to execute the programs assigned to these events.
This in turn would enable us to also emulate a physical button being pressed. Could be useful for some users.

**Comment by pvizeli** [comment]
Done with 0.1.9
