### ISSUE TITLE
Possible Support for HmIP-ASIR-2? :)

### ISSUE THREAD

**Issue by CineMAC-HA** [danielperna84/pyhomematic#320]
Hi, great job and many thanks for your Support! It is possible to integrate the Homematic IP Sirene (HmIP-ASIR-2)?

Thanks and Regards 

Frank

**Comment by danielperna84** [comment]
Please have a look at this issue regarding device support: https://github.com/danielperna84/pyhomematic/issues/28
Please also try to build the implementation yourself, as I currently don't have much time to spend on this project.
