### ISSUE TITLE
HmIP Cover issues with 0.114.0

### ISSUE THREAD

**Issue by leinich** [danielperna84/pyhomematic#322]
With the latest home assistant verision none of my hmip covers work after updating to Version 0.114.
Downgrading to the Verion 0.113 brings back the hmip covers  

**Home Assistant version:**
0.114.0

```yaml
Logger: homeassistant.components.cover
Source: components/homematic/cover.py:45
Integration: Abdeckung (documentation, issues)
First occurred: 16:41:34 (1 occurrences)
Last logged: 16:41:34

Error while setting up homematic platform for cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 192, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 301, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 397, in _async_add_entity
    supported_features=entity.supported_features,
  File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 219, in supported_features
    if self.current_cover_position is not None:
  File "/usr/src/homeassistant/homeassistant/components/homematic/cover.py", line 45, in current_cover_position
    return int(self._hm_get_state() * 100)
ValueError: invalid literal for int() with base 10: ''
```

**Comment by danielperna84** [comment]
Hm, I don't know why that happens. All that has been done is that a sensor was added [here](https://github.com/danielperna84/pyhomematic/commit/4a8a9ce291f254ad0841ca5d886c0023de264469#diff-65a409c22bde078571de4687b5d5e09eR60). Could you check if removing that line fixes the issue? It shouldn't, but since it's the only change in that regard I don't know what else to suggest. 🤷‍♂️

**Comment by leinich** [comment]
@danielperna84 
will have a look next week, when I have access to my personal computer.
One strange thing I noticed is that the cover works if it is closed and HA is restared. As soon as it is not closed I recieve the above error message.
Could also be possible that the issue appears already with 0.113

**Comment by leinich** [comment]
I meanwhile updated the CCU3 to firmware version 3.53.26

Unfortunatelly I was not able to reproduce the issue.
