### ISSUE TITLE
Add tests to PyPI release

### ISSUE THREAD

**Issue by fabaff** [danielperna84/pyhomematic#329]
**Describe the bug**
The source tarball published on PyPI doesn't contain the tests.

**Expected behavior**
Be able to run the tests during the RPM build process. The Fedora Packaging Guidelines recommend to run the tests to ensure that the module works with the available Python release. I will submit the review request without running the test suite but it would be nice to add them in the near future.

**Additional context**
Instead of adding the tests to the PyPi release, could it be solved if the GitHub and the PyPI release are in-sync.

Thanks

**Comment by danielperna84** [comment]
I have published 0.1.69, which includes the tests. For 0.1.68 I just forgot to add the release-tag. But that doesn't matter now anyways. Not it's in sync. 👍

**Comment by onkelbeh** [comment]
yep, installing a tests package at top level is forbidden. #334

**Comment by onkelbeh** [comment]
Just added a [patch for 0.1.69](https://github.com/onkelbeh/HomeAssistantRepository/commit/234239ed2cf061eb9ceb11f5f0d9d8731854a140) to keep it in the repo, some guys would miss it.
