### ISSUE TITLE
HMIP WHS2 - turn on/off

### ISSUE THREAD

**Issue by ronaldt80** [danielperna84/pyhomematic#330]
Hi Daniel, I'm running homeassistant in combination with debmatic. I would like to control my heating switch (HMIP-WHS2); would expect similar behaviour vs. the HMIP-MIOB. 

Tried the following input for homematic.set_device_value

```
address: 00195A498Bxxxx
channel: 2
param: STATE
value: true
```

This works - the actuator has 9 channels; 
- channels 2, 3, 4 operate switch 1 - channel 1 is the status report output for this switch
- channels 6, 7, 8 operate switch 2 - channel 5 is the status report output for this switch
- channel 9 is the week program

I am not a python expert but to check, is this simply a matter of adding this to the switch definition?

thanks for your help!

**Comment by danielperna84** [comment]
> I am not a python expert but to check, is this simply a matter of adding this to the switch definition?

It probably will be ok to just add channels 2 and 6 as the switch channels. The two additional channels per _switch_  are just used for internal logic with "Direktverknüpfungen". So als long as you don't use them it will probably work.

**Comment by ronaldt80** [comment]
Hi Daniel,

thanks but I am not sure I understand. I managed to get the output from get_device_data.py but I have no clue what the next step is. Is this simple to add HMIP-WHS2 as an IPSwitch?

eg:
`"HmIP-WHS2": IPSwitch`

Any pointers would be much appreciated!

Ronald

**Comment by danielperna84** [comment]
You have to do something similar to [this](https://github.com/danielperna84/pyhomematic/blob/4a8a9ce291f254ad0841ca5d886c0023de264469/pyhomematic/devicetypes/actors.py#L501) to assign the correct channels for the device.

**Comment by markus7811** [comment]
@danielperna84 2 questions:

do i have to change these switch?

https://github.com/danielperna84/pyhomematic/blob/43f8d4048760f7330b78fd47eba5f077d75975a8/pyhomematic/devicetypes/actors.py#L567

and add something like

```
 elif "HmIP-WHS2" in self.TYPE:
            channels = [2,6]
```

and add something like

```HmIP-WHS2: IPSwitch```

at the end?

can you give me a tipp for how to test this locally on my ha setup?

**Comment by danielperna84** [comment]
@markus7811 

Yes, that's how it would be done. Have a look [here](https://github.com/danielperna84/pyhomematic/wiki/Contributing-and-development-for-pyhomematic) for how to test this with a dedicated VM. It has a rather old Home Assistant installation, but it should still work.

**Comment by danielperna84** [comment]
I think that won't work as well. The dev-container relies on Docker. And I don't think there's Docker for M1 Macs yet.

If the Python Version of your Mac is recent enough, you could try manually using the [venv](https://www.home-assistant.io/installation/linux#create-the-virtual-environment) approach.

**Comment by markus7811** [comment]
Oh docker is somehow working on m1 macs, i managed to start the dev environment, but its crashing a lot... will look into this this evening :-)
