### ISSUE TITLE
"Device" Domain in home assistant missing

### ISSUE THREAD

**Issue by Fruchuxs** [danielperna84/pyhomematic#337]
**Is your feature request related to a problem? Please describe.**
I just got the entities in my home assistant and not the device with the entities. This means I can't assign a climate device to an area (we can't assign entities to an area). This is problematic, because If I sync my home assistant with google home, in google home, my climate device is not assigned to a room automatically. I can fix this in the google home app, but after a resync, the room information is lost again.

**Describe the solution you'd like**
Not sure if this is possible, because I didn't know much about the CCU API. But if the CCU API communicates the device with the possible sensors, I would like to see this in home assistant, like sensors over deconz (one sensor hast multiple entities).

**Describe alternatives you've considered**

**Additional context**
Example device to describe what I mean:
![image](https://user-images.githubusercontent.com/5205672/95013914-b984dd80-0643-11eb-9aab-bb31f9862ea4.png)

**Comment by danielperna84** [comment]
If I'm correct, this is a result of the HomeMatic integration not being a _modern_ one that can be configured via UI. So this is actually an inssue with the integration in Home Assistant. Pyhomematic just is the wrapper to let Home Assistant communicate with the CCU.

**Comment by Fruchuxs** [comment]
Okay, thank you for the answer. This means i'm in the wrong repository with my feature request. Assuming that the home assistant integration is not updated in the feature because of the small target group of users.

**Comment by danielperna84** [comment]
It will be updated some day. But I'm not directly involved in the process currently.
