### ISSUE TITLE
HMIP-PCBS2 not showing up in HA

### ISSUE THREAD

**Issue by manutoky** [danielperna84/pyhomematic#340]
I just added a HMIP-PCBS2 to my Homematic configuration but it didn't show up in HA.
Logs gave me this hint:
2020-10-11 16:22:23 DEBUG (SyncWorker_3) [pyhomematic._hm] RPCFunctions.createDeviceObjects: created 00199A4992F9BC  as UNSUPPORTED device for HmIP-PCBS2

After a quick look into the source there seems to be support for this type of device. Can you please check what's missing here?

HA Version is 0.116.2

**Comment by danielperna84** [comment]
You have to wait for the next release (0.117). There's always a 2-3 week delay until HA uses the latest pyhomematic version.
