### ISSUE TITLE
HmIP-WGC

### ISSUE THREAD

**Issue by regnets** [danielperna84/pyhomematic#342]
As described in #28, I created the necessary files for the homematic ip garage door opener.

Here is the gist:
https://gist.github.com/regnets/0e32da4f4622a59ab1b0190a53e77c89

**Comment by mwagner** [comment]
Is it different from mine? I haven't had a chance to look into the details

https://github.com/danielperna84/pyhomematic/issues/28#issuecomment-700953571

**Comment by regnets** [comment]
I am not sure, the first comment stated that I should open a new issue for any not supported device (certainly to keep track of the state of the project). Also, I didn't read all the comments as this issue is just that long.

**Comment by kayloehmann** [comment]
I'm also in need of this device to be supported. What help do you exactly need?

**Comment by danielperna84** [comment]
> What help do you exactly need?

Since I don't own the device it would take a lot of trial and error to 1. get it to work in pyhomematic, and 2. see how it should be integrated into Home Assistant. Hence someone who has the time to take care of it is needed, because I'm to too busy lately.

**Comment by kayloehmann** [comment]
Looks to me that channel 1 would be sufficient to start with!? 
![image](https://user-images.githubusercontent.com/34281638/104560474-39a8df00-5646-11eb-946a-f8656eb076af.png)

If not, is there some "instruction" that must be followed to find out?

**Comment by danielperna84** [comment]
I believe not. With those you would only see messages in Home Assistant that the buttons have been pressed. I don't know what this device is capable of, but I would expect a garage opener to be able to open garages. Or is this device usually paired with an actor that controls the garage doof? If so, why is support for this device needed in the first place? After all the actual actor would already reveal that it has been triggered, making the info that a button has been pressed useless. 🤷‍♂️

**Comment by kayloehmann** [comment]
I'm not sure how to respond to your comment.

This is the setup of the device with the motor.  [garagedooropener](https://user-images.githubusercontent.com/34281638/104812298-969cc480-5801-11eb-870a-ee00987d8b00.png)

I connected it with 2 cables on ports 1 and 2
<img width="1102" alt="grafik" src="https://user-images.githubusercontent.com/34281638/104812406-34908f00-5802-11eb-9f28-edb0b8d81da9.png">

Here is the picture how the cables are connected to the garagedoor switch.
<img width="896" alt="grafik" src="https://user-images.githubusercontent.com/34281638/104812472-a8329c00-5802-11eb-8595-3a8c181d3613.png">

This setup works great and i can open, close the garage with a mobile app / ccu3.
It would be great, if this device would also be visible in homeassistant.

Thanks. Kay.

**Comment by m4k5ym** [comment]
If somebody could give me instructions what to do for a proper implementation. I'm in for providing a pull request.

**Comment by mwagner** [comment]
I'm trying to implement this device now, the switch is kinda working now.
However, is there a helper function or something available for push button (on when pressed, off when released)? Currently when I press the button in homeassistant it stays 'on' and I need to press it again to 'release' it. Is there a way to send a combination of
```
setValue: address=VCU9870815:3, value_key=STATE, value=True, force=False
setValue: address=VCU9870815:3, value_key=STATE, value=False, force=False
```
?

**Comment by danielperna84** [comment]
@mwagner 

Buttons typically use [HelperEventPress](https://github.com/danielperna84/pyhomematic/blob/17903fa67fa8f512201ef1bb3ddf2f14a67f2cf5/pyhomematic/devicetypes/helper.py#L265) or [HelperEventRemote](https://github.com/danielperna84/pyhomematic/blob/17903fa67fa8f512201ef1bb3ddf2f14a67f2cf5/pyhomematic/devicetypes/helper.py#L273). With those in place Home Assistant will __not__ create entities for these buttons, but it will fire events like described [here](https://www.home-assistant.io/integrations/homematic/#devices-with-buttons) in the documentation.

If this is not how the button on the HmIP-WGC operates, please explain what it does and how you control it with `setValue`.

Be aware, that Home Assistant does not provide an entity type that behaves as you describe (stay _on_ while pressed, then go back to _off_ when released.
