### ISSUE TITLE
HmIP-SWD

### ISSUE THREAD

**Issue by regnets** [danielperna84/pyhomematic#344]
As described in #28, I created the necessary files for the homematic ip water sensor.

Here is the gist:
https://gist.github.com/regnets/a5c04809aa30e0690586f83f12c27f03

**Comment by danielperna84** [comment]
This too should already be supported: https://github.com/danielperna84/pyhomematic/blob/bf96419590881ba804246895b1d740d53332eadf/pyhomematic/devicetypes/sensors.py#L1098

**Comment by regnets** [comment]
Oh i am very sorry, this was a total oversight from me. I will close that ticket.
