### ISSUE TITLE
Help - HmIP-ASIR will not view in my Home Assistant

### ISSUE THREAD

**Issue by CineMAC-HA** [danielperna84/pyhomematic#346]
Hi, I have see you have implemented the HmIP-ASIR in pyhomematic. Great, and thanks for that! :)
But I can't find a sensor in my Home Assistant Instance. What I am doing wrong? Please can you help me?

Firmware CCU3: 3.53.26
HomeAssistant:  116.4

Thanks and Regards
Frank

**Comment by danielperna84** [comment]
@stefangries you did the implementation. Can you help?

**Comment by CineMAC-HA** [comment]
Yes, the implementation was in my configuration.yaml and I can see all my Homematic sensors. Only the HmIP-ASIR will not view by my entitylist.

**Comment by stefangries** [comment]
For me, my ASIR is working correctly in Home Assistant 117. So more information is needed to debug this.

**Comment by CineMAC-HA** [comment]
Yes, all other Sensors working perfect. that's wondering. I have reboot the CCU and the Home Assistant, but I can't find the ASIR in my entitys from HA. In the CCU I can see this.

**Comment by CineMAC-HA** [comment]
maybe I must delete the ASIR from my CCU and relearn? I will try this!

**Comment by CineMAC-HA** [comment]
Now I has relearn the ASIR Device in my CCU3, but not sensor for this in Home Assistant. Any Idea?

in my CCU I can see this device correct.

HmIP-ASIR 000AD5699C6A5E

**Comment by stefangries** [comment]
![Screenshot_20201101-122220](https://user-images.githubusercontent.com/10342151/97801429-f17c4200-1c3c-11eb-9c7e-8a8bc0a054f7.jpg)

The ASIR should appear in your CCU and should be named as shown in the picture, where "Alaemsirene" is the Name of the device set in the CCU.

**Comment by CineMAC-HA** [comment]
Thanks for your response, but no match in Home Assistant under "Alarmsirene" or the ID from the sirene. Strange! :-)

**Comment by leinich** [comment]
> Thanks for your response, but no match in Home Assistant under "Alarmsirene" or the ID from the sirene. Strange! :-)

The HmIP-ASIR is supported with pyhomematic 0.1.69 with is part of Home Assistant 117 or later.
Seems that you only need to update your HA instance, as you mentioned in the first post that you are using version 116

**Comment by CineMAC-HA** [comment]
Ah okay, Then I will Update my HA to 117. Sorry for the mistake from my Site. Thanks for the help! :-)
