### ISSUE TITLE
Using HMIP-PCBS2 over HA not working correctly

### ISSUE THREAD

**Issue by manutoky** [danielperna84/pyhomematic#348]
I have this observation after HMIP-PCBS2 became supported in HA 0.117.
I seems that updates to its states is not working correctly. I have a CCU3 program that is switching off both relays 2 sec after activation. This is not reflected in HA. 

**Home Assistant version (if applicable):**
0.117.1

**Comment by leinich** [comment]
@manutoky 
I added support for the HmIP-PCBS2 and currently I don't see any issues with it (at least for my usecases it is working as expected).
I can have a look into you issue, but I need help to reproduce the issue.
Does the switch stay on, or does the on state not arrive in HA?

**Comment by manutoky** [comment]
Thanks @leinich !
My CCU3 program is switching both relays off 2 seconds (30 for testing) after they are activated (I control my Roto roof window opener this way). If I trigger this via home assistant, I can see the activation in HA but the switch is staying active while CCU3 shows the the correct state (off after 2/30 secs). I can manually switch them off in HA (to no effect as they are already off) and re-trigger an activation which comes through. So it seems that the states are not updated. Also, an activation via CCU3 is not arriving in HA. Other devices are working fine for me (some thermostats, a HMIP-SWDO, a HMIP-PS).

**Comment by manutoky** [comment]
@leinich 
Can you maybe verify that the channels for HMIP_PCBS2 are indeed [4,8]? I'd assume that the correct values are [6,10]. At leaast these are the channels my CCU3 is showing me.

**Comment by manutoky** [comment]
Closed.
I solved it by activating "Virtuelle Kanäle" in my CCU3 and adding programms for channels 4 and 8. Sorry for the inconvenience.
