### ISSUE TITLE
Please Help for acoustic_alarm_active or optical_alarm_active from ASIR 

### ISSUE THREAD

**Issue by CineMAC-HA** [danielperna84/pyhomematic#350]
Hi, sorry for this question, but I don't understand this new binary_sensor. How can I activate this binary_sensor or change the state for this by automation? Please can you give me an Example? I would like the state from my binary_sensor.hmip_asir_000ad5699c6a5e_optical_alarm_active to state 'on' when the door is opened and turn_off when the alarm was disarmed.

Best regards
Frank

**Comment by CineMAC-HA** [comment]
I have try the following service in a script, but it doesn't work.

- service: homematic.set_device_value
      data:
        address: '000AD5699C6A5E'
        channel: 3
        param: 'OPTICAL_ALARM_SELECTION'
        value: 'BLINKING_BOTH_REPEATING'

**Comment by danielperna84** [comment]
You should ask such questions at https://community.home-assistant.io . Pretty much nobody will see your question here, and I don't provide Home Assistant support.
