### ISSUE TITLE
Support for HmIPW-WTH?

### ISSUE THREAD

**Issue by SlippySken** [danielperna84/pyhomematic#351]
Is there a way to add support for the HmIPW-WTH?
It's the wired wallmounted thermostat :).

**Comment by danielperna84** [comment]
Have a look at https://github.com/danielperna84/pyhomematic/issues/28 and https://github.com/danielperna84/pyhomematic/wiki/Contributing-and-development-for-pyhomematic

Once you got it working you can open a pull request to get your code merged into pyhomematic.

**Comment by danielperna84** [comment]
Should be added with 20e9e90f4486d2eb3aaa3a3ff3320e55e6cf6a1e
