### ISSUE TITLE
HmIP-DRSI1

### ISSUE THREAD

**Issue by malkie-hass** [danielperna84/pyhomematic#353]
Hello,
here are the files for the HmIP-DRSI1

https://gist.github.com/malkie-hass/45e5b35837141d065e3c38e0092f32c0

If somebody can help to integrate?

Best regards

Malkie

**Comment by leinich** [comment]
As my device will arrive in aprox. 11 Weeks, I'm willing to add support for the device ;-)
Seems that the device is almost the same as the HmIP-FSI16 expect from the form factor.

@malkie-hass Is there a change that you confirm my changes in a testenvironment on your side.
Daniel made a good testenvironment as descibed here: https://github.com/danielperna84/pyhomematic/wiki/Contributing-and-development-for-pyhomematic
You may simply change one file and skip the pydevccu part and use your CCU instead.

**Comment by malkie-hass** [comment]
@leinich I have no idea what you are talking about :)
I'm willing to help. Maybe we can do that together?
If you would have time for a remote session and you can run me through that would be great.

**Comment by lukasriegel** [comment]
As I received my HmIP-DRSI1 this week I created a pull request to add support for this device type

**Comment by danielperna84** [comment]
Support now is included in 0.1.71. Closing this issue.
