### ISSUE TITLE
Update position change between 2-99 for covers while opening/closing

### ISSUE THREAD

**Issue by nicx** [danielperna84/pyhomematic#354]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when using covers in the Apple Home app with Home Assistant HomeKit integration and Homematic covers, because the state is not reflecting "smoothly", so only the end state is correct, not the "opening" or "closing" state.

The covers don't update when the position changes between 2-99 (unless the cover stops), that's why the HA HomeKit integration don't have enough information to determine the position of the cover beyond open / closed (and opening/closing for the integrations that due report that). See the problem here: https://github.com/home-assistant/core/issues/42444#issuecomment-731838095

**Describe the solution you'd like**
I would like to have the homematic covers doing an optimistic set so the behavior is better. Other integrations like lutron_caseta, lutrion_caseta_pro (custom), somfy implement optimistic state as an option or by default.

**Comment by nicx** [comment]
what kind of help do you need? I could assist as a beta tester :)

**Comment by danielperna84** [comment]
_Help_ in the form of _someone who has time and the device has to do this_. 👍

**Comment by nicx** [comment]
Hey @danielperna84, maybe you could keep the in mind when adding more features to the successor [hahomematic](https://github.com/danielperna84/hahomematic) in future ;)

**Comment by danielperna84** [comment]
Covers now work pretty much perfectly with the [new integration](https://github.com/danielperna84/custom_homematic).
