### ISSUE TITLE
Expose FAULT_REPORTING

### ISSUE THREAD

**Issue by infernix** [danielperna84/pyhomematic#357]
**Describe the solution you'd like**
When radiator thermostats have issues, I would like to see that exposed in HomeAssistant so I can make that actionable.

**Describe alternatives you've considered**
Parsing homegear output logs, or getting this state through MQTT. Not really great.
Alternatively, this also seems to show under "Servicemeldungen" in things like Homematic Manager, but I can't see that being exposed anywhere either.

**Additional context**
```
12/13/20 15:26:56.156 Module HomeMatic BidCoS: Info: FAULT_REPORTING on channel 4 of HomeMatic BidCoS peer 12 with serial number NEQ0414407 was set to 0x07.
12/13/20 15:26:56.180 MQTT Client: MQTT Client Info: Publishing topic   homegear/1234-5678-9abc/json/12/4/FAULT_REPORTING
12/13/20 15:26:56.181 MQTT Client: MQTT Client Info: Publishing topic   homegear/1234-5678-9abc/plain/12/4/FAULT_REPORTING
```
This doesn't show up anywhere that I can find - not on the device nor on the homegear host. But this device does actually report a fault - probably calcification. It's visible in `config print` in homegear:
```
...
VALUES
{
	Channel: 4
	{
		[SET_TEMPERATURE]: 18 
		[PARTY_TEMPERATURE]: 28 
		[PARTY_STOP_YEAR]: 0c 
		[PARTY_STOP_TIME]: 00 
		[PARTY_STOP_MONTH]: 01 
		[COMFORT_MODE]: 01 
		[BOOST_STATE]: 00 
		[PARTY_STOP_DAY]: 01 
		[AUTO_MODE]: 01 
		[CONTROL_MODE]: 01 
		[BATTERY_STATE]: 04 
		[ACTUAL_TEMPERATURE]: 00 ba 
		[MANU_MODE]: 18 
		[VALVE_STATE]: 0f 
		[PARTY_MODE_SUBMIT]: 
		[LOWERING_MODE]: 01 
		[PARTY_START_DAY]: 01 
		[FAULT_REPORTING]: 07  <----
		[PARTY_START_TIME]: 00 
		[BOOST_MODE]: 01 
		[PARTY_START_MONTH]: 01 
		[PARTY_START_YEAR]: 0c 
	}
```

**Comment by danielperna84** [comment]
This can be done with the [new integration](https://github.com/danielperna84/custom_homematic) using the [unignore](https://github.com/danielperna84/custom_homematic#unignore-device-parameters) feature.
