### ISSUE TITLE
Homematic HmIP-RCV-50 not working with virtual key

### ISSUE THREAD

**Issue by heloman84** [danielperna84/pyhomematic#368]
Hello, 

for some time now the virtual keys HmIP-RCV-50 do not work. The same problem has already been described by other user in the HA forum: https://community.home-assistant.io/t/homematic-hmip-rcv-50-not-working-with-virtual-key-any-more/249000.

Anybody has an idea how to fix the problem?

Happy new year :-)

**Comment by p0l0** [comment]
I have the same problem, when trying to call the "homematic.virtualkey" service for HmIP-RCV-50 (with address HMIP-RCV-1), it always says "HMIP-RCV-1 not found for service virtualkey!".

I'm using (piV)CCU version 3.55.10. 

After doing some debug with pyhomatic, I have seen, that the "device" is provided correctly by the CCU and pyhomatic is detecting it correctly as a device:

> 'HmIP-RCV-1': <pyhomematic.devicetypes.misc.RemoteVirtual object at 0x7fc3f6967e80>}

@danielperna84 could the reason for the error be, that ATTR_ADDRESS in the HA Integration is uppercase, but the address provided by the CCU not? Maybe it needs to be handled like [BidCoS-RF](https://github.com/home-assistant/core/blob/dev/homeassistant/components/homematic/__init__.py#L612) or should pyhomatic force uppercase for device addresses to avoid this error in the future?

**Comment by DanielTheCoder** [comment]
I have the same problem as @p0l0 and was able to solve the issue handling case-sensitivity like `BidCos-RF` as mentioned by @p0l0.
