### ISSUE TITLE
HmIP-RF Support (homematic IP)

### ISSUE THREAD

**Issue by elajoie** [danielperna84/pyhomematic#37]
Is it possible and can I help in any way to add HmIP-RF devices to the supported device list?

Looks like CCU2's XML-RPC port 2001 only provides info for BidCos-RF devices where port 2010 provides HmIP-RF device info.  I've attached listDevices call on both port 2001 and 2010 for reference

<img width="443" alt="snap" src="https://cloud.githubusercontent.com/assets/5882853/18616266/ed4711be-7db8-11e6-8f51-a532c2f66923.png">
[XML-RPCport2001.txt](https://github.com/danielperna84/pyhomematic/files/478741/XML-RPCport2001.txt)
[XML-RPCport2010.txt](https://github.com/danielperna84/pyhomematic/files/478740/XML-RPCport2010.txt)

Looks like when I change the remote port from 2001 to 2010 in configuration.yaml in home assistant it connects but gets unidentified events as shown below:

```
16-09-18 16:10:12 INFO (Thread-1) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0001D3C98DD721:0, interface_id=homeassistant, key=DUTY_CYCLE, value=False
16-09-18 16:10:12 INFO (Thread-1) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0001D3C98DD721:0, interface_id=homeassistant, key=UNREACH, value=False
16-09-18 16:10:12 INFO (Thread-1) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0001D3C98DD721:2, interface_id=homeassistant, key=STATE, value=True
16-09-18 16:10:12 INFO (Thread-1) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0001D3C98DD721:2, interface_id=homeassistant, key=SECTION, value=2
16-09-18 16:10:12 INFO (Thread-1) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0001D3C98DD721:2, interface_id=homeassistant, key=PROCESS, value=0
16-09-18 16:10:12 INFO (Thread-1) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0001D3C98DD721:3, interface_id=homeassistant, key=STATE, value=True
16-09-18 16:10:12 INFO (Thread-1) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0001D3C98DD721:3, interface_id=homeassistant, key=SECTION, value=2
16-09-18 16:10:12 INFO (Thread-1) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0001D3C98DD721:3, interface_id=homeassistant, key=PROCESS, value=0
16-09-18 16:10:12 INFO (Thread-1) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0001D3C98DD721:4, interface_id=homeassistant, key=STATE, value=False
16-09-18 16:10:12 INFO (Thread-1) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0001D3C98DD721:4, interface_id=homeassistant, key=SECTION, value=0
16-09-18 16:10:12 INFO (Thread-1) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0001D3C98DD721:4, interface_id=homeassistant, key=PROCESS, value=0
16-09-18 16:10:12 INFO (Thread-1) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0001D3C98DD721:5, interface_id=homeassistant, key=STATE, value=False
16-09-18 16:10:12 INFO (Thread-1) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0001D3C98DD721:5, interface_id=homeassistant, key=SECTION, value=0
16-09-18 16:10:12 INFO (Thread-1) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0001D3C98DD721:5, interface_id=homeassistant, key=PROCESS, value=0
16-09-18 16:10:13 INFO (Thread-1) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0001D3C98DD721:6, interface_id=homeassistant, key=FREQUENCY, value=50.01
16-09-18 16:10:13 INFO (Thread-1) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0001D3C98DD721:6, interface_id=homeassistant, key=POWER, value=48.35
16-09-18 16:10:13 INFO (Thread-1) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0001D3C98DD721:6, interface_id=homeassistant, key=VOLTAGE, value=226.4
16-09-18 16:10:13 INFO (Thread-1) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0001D3C98DD721:6, interface_id=homeassistant, key=ENERGY_COUNTER, value=1454.2
16-09-18 16:10:13 INFO (Thread-1) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0001D3C98DD721:6, interface_id=homeassistant, key=CURRENT, value=280.0
16-09-18 16:10:13 INFO (Thread-1) [pyhomematic.devicetypes.generic] HMGeneric.event: address=0001D3C98DD721:6, interface_id=homeassistant, key=ENERGY_COUNTER_OVERFLOW, value=False

```

**Comment by danielperna84** [comment]
Thanks for investigating. This looks like it would actually be possible to use the IP devices without too much work. As you can see by switching the port, pyhomematic is already able to generally detect the devices (pyhomematic.devicetypes.generic is the base-class which all devices depend on) and receive their events.

To get this working two things need to be done:

1. Open a secondary XML-RPC proxy which connects to 2010 and have the listed devices added to the dictionary of devices with this secondary proxy.
2. Implement each device like it's done with all the others that are already implemented. For BidCos-RF we used the hm_devices_Endkunden PDF (which is the same as part 4 - Datenpunkte - of the HM-Script documentation) as a guide to implement the devices that currently are supported.

So I guess the first step would be to find some documentation for the HM-IP devices describing the available channels and their parameters. With those at hand you could start implementing the devices you have and can test them.
The very first thing you can try is to modify the dictionary at the bottom of [sensors.py](https://github.com/danielperna84/pyhomematic/blob/master/pyhomematic/devicetypes/sensors.py) and add a line ```"HMIP-SWDO": ShutterContact,```. Assuming the device internally does the same as the BidCos shutter contact, it might already work by just adding the device-descriptor and assigning a suitable class, in this case the ShutterContact class.
When you've done that, it's compatible and start HA with the 2010 port, the device should be visible in the HA UI. If so, open and close the door and see if the entity in the UI reacts the the events.

I'm curious if that would actually be all there is to implement IP.

**Comment by pvizeli** [comment]
@elajoie, If you can give me all data Points from you device and his name, so I can add the device to pyhomematic that should work on Home-Assistant. The part of XML Proxy, that Need help from @danielperna84

**Comment by elajoie** [comment]
I've asked e@-3 for documentation and will share what I receive.  

Would it be easy to allow the following config support?

homematic 1:
  local_ip: 192.168.0.2
  local_port: 8943
  remote_ip: 192.168.0.4
  remote_port: 2010
  username: Admin
  password: <password>
  resolvenames: json

homematic 2:
  local_ip: 192.168.0.2
  local_port: 8943
  remote_ip: 192.168.0.4
  remote_port: 2001
  username: Admin
  password: <password>
  resolvenames: json

**Comment by elajoie** [comment]
@pvizeli Pardon my lack of knowledge, how can I get you the data points and name from the device?

**Comment by danielperna84** [comment]
To get the datapoints have a look at this [link](http://homematic-forum.de/forum/viewtopic.php?f=31&t=30127).

The config you've written above could actually already work if you specify another local port. You can't bind to one port twice. But if you use 8944 instead for the second pyhomematic-server, this could work around implementing a secondary proxy in pyhomematic itself. Although I'm not sure about the name under which the services will become available. For that you could add the ```name: whatever``` parameter to your configuration. Can't test that though.

**Comment by danielperna84** [comment]
I've created a small script to get the data we need to implement the devices: [datapoints.py](https://github.com/danielperna84/pyhomematic/blob/master/datapoints.py)
This may be an easier and more flexible solution.

**Comment by elajoie** [comment]
https://gist.github.com/elajoie/218e93ae5b933ecc865041642900e148

**Comment by pvizeli** [comment]
thanks

**Comment by pvizeli** [comment]
@elajoie 
Can you try with HMIP-PS(M):
```
python3 test.py -l LOCAL_IP -r REMOTE_IP -rp 2001 -a DEV_ADDRESS --toggle
```
And for the HMIP-SCBO:
```
python3 test.py -l LOCAL_IP -r REMOTE_IP -rp 2001 -a DEV_ADDRESS
```

**Comment by elajoie** [comment]
I'll be back home Friday night CEST. Where is the test.py you are referring to?

**Comment by danielperna84** [comment]
It's in the base-folder of this repository: [test.py](https://github.com/danielperna84/pyhomematic/blob/master/test.py)

**Comment by elajoie** [comment]
@danielperna84 Which branch should I test with?

**Comment by danielperna84** [comment]
Use the master-branch.

**Comment by elajoie** [comment]
No luck so far with 
`python3 test.py -l 192.168.0.22 -r 192.168.0.4 -rp 2010 -a 0001D3C98DD73F:3 --toggle --debug`
https://gist.github.com/elajoie/49b464f697da52293144c02dc8e73d7f

![screenshot from 2016-10-05 21-11-58](https://cloud.githubusercontent.com/assets/5882853/19127712/7bef261a-8b40-11e6-9fba-41eb6165d909.png)

**Comment by danielperna84** [comment]
I belive it sould be:
`python3 test.py -l 192.168.0.22 -r 192.168.0.4 -rp 2010 -a 0001D3C98DD73F -c 3 --toggle --debug`
and
`python3 test.py -l 192.168.0.22 -r 192.168.0.4 -rp 2010 -a 0000D5698E44E1 -c 1`

**Comment by elajoie** [comment]
Same exception message:
https://gist.github.com/elajoie/69edfc1573ca935925bad9d3f81c50cd

**Comment by danielperna84** [comment]
Well, no, actually the script got further. You can ignore the Exception vor the variables, since that's not what we care about right now. Instead, the device got detected successfully:
```
******************************
* Show metadata from 0001D3C98DD73F
* Elements: [3] / Childs: 8
* Class: <class 'pyhomematic.devicetypes.actors.IPSwitchPowermeter'>
* Base: (<class 'pyhomematic.devicetypes.actors.IPSwitch'>, <class 'pyhomematic.devicetypes.sensors.HMSensor'>)
* Sensor datapoint: {'CURRENT': [6], 'POWER': [6], 'FREQUENCY': [6], 'ENERGY_COUNTER': [6], 'VOLTAGE': [6]}
* Binary datapoint: {}
* Write datapoint: {'STATE': [3]}
* Attribute datapoint: {'RSSI_DEVICE': [0]}
* Event datapoint: {}
* Action datapoint: {'ON_TIME': [3]}
******************************
```

Problem is, that the test does not currently support IP-switches. However, it at least get's detected properly.

**Comment by elajoie** [comment]
Excellent. Here is the shutter contact output:
`******************************
* Show metadata from 0000D5698E44E1
* Elements: [1] / Childs: 2
* Class: <class 'pyhomematic.devicetypes.sensors.IPShutterContact'>
* Base: (<class 'pyhomematic.devicetypes.sensors.HMBinarySensor'>, <class 'pyhomematic.devicetypes.helper.HelperBinaryState'>, <class 'pyhomematic.devicetypes.helper.HelperLowBat'>)
* Sensor datapoint: {}
* Binary datapoint: {'STATE': [1]}
* Write datapoint: {}
* Attribute datapoint: {'RSSI_DEVICE': [0], 'LOWBAT': [1]}
* Event datapoint: {}
* Action datapoint: {}
******************************
`

**Comment by danielperna84** [comment]
I've updated the test.py script. It now should be able to toggle the switch.

For the shutter contact: Have you tried opening and closing the contact while the script was running? There is a point in the script where it's waiting for events. During that you should manually trigger the device to emit events.

**Comment by elajoie** [comment]
Worked!

INFO:pyhomematic.devicetypes.generic:HMGeneric.event: address=000915698E4174:0, interface_id=test-pyhomatic, key=SABOTAGE, value=False
INFO:pyhomematic.devicetypes.generic:HMGeneric.event: address=000915698E4174:0, interface_id=test-pyhomatic, key=DUTY_CYCLE, value=False
INFO:pyhomematic.devicetypes.generic:HMGeneric.event: address=000915698E4174:0, interface_id=test-pyhomatic, key=LOW_BAT, value=False
INFO:pyhomematic.devicetypes.generic:HMGeneric.event: address=000915698E4174:0, interface_id=test-pyhomatic, key=ERROR_CODE, value=0
INFO:pyhomematic.devicetypes.generic:HMGeneric.event: address=000915698E4174:0, interface_id=test-pyhomatic, key=UNREACH, value=False
INFO:pyhomematic.devicetypes.generic:HMGeneric.event: address=000915698E4174:0, interface_id=test-pyhomatic, key=OPERATING_VOLTAGE, value=2.9
INFO:pyhomematic.devicetypes.generic:HMGeneric.event: address=000915698E4174:1, interface_id=test-pyhomatic, key=ILLUMINATION, value=0.0
INFO:pyhomematic.devicetypes.generic:HMGeneric.event: address=000915698E4174:1, interface_id=test-pyhomatic, key=MOTION, value=True
INFO:pyhomematic.devicetypes.generic:HMGeneric.event: address=000915698E4174:1, interface_id=test-pyhomatic, key=MOTION_DETECTION_ACTIVE, value=True
INFO:pyhomematic.devicetypes.generic:HMGeneric.event: address=0000D5698E44E1:0, interface_id=test-pyhomatic, key=SABOTAGE, value=False
INFO:pyhomematic.devicetypes.generic:HMGeneric.event: address=0000D5698E44E1:0, interface_id=test-pyhomatic, key=DUTY_CYCLE, value=False
INFO:pyhomematic.devicetypes.generic:HMGeneric.event: address=0000D5698E44E1:0, interface_id=test-pyhomatic, key=LOW_BAT, value=False
INFO:pyhomematic.devicetypes.generic:HMGeneric.event: address=0000D5698E44E1:0, interface_id=test-pyhomatic, key=ERROR_CODE, value=0
INFO:pyhomematic.devicetypes.generic:HMGeneric.event: address=0000D5698E44E1:0, interface_id=test-pyhomatic, key=UNREACH, value=False
INFO:pyhomematic.devicetypes.generic:HMGeneric.event: address=0000D5698E44E1:0, interface_id=test-pyhomatic, key=OPERATING_VOLTAGE, value=1.4
INFO:pyhomematic.devicetypes.generic:HMGeneric.event: address=0000D5698E44E1:1, interface_id=test-pyhomatic, key=STATE, value=0
INFO:pyhomematic.devicetypes.generic:HMGeneric.event: address=0000D5698E44E1:0, interface_id=test-pyhomatic, key=SABOTAGE, value=False
INFO:pyhomematic.devicetypes.generic:HMGeneric.event: address=0000D5698E44E1:0, interface_id=test-pyhomatic, key=DUTY_CYCLE, value=False
INFO:pyhomematic.devicetypes.generic:HMGeneric.event: address=0000D5698E44E1:0, interface_id=test-pyhomatic, key=LOW_BAT, value=False
INFO:pyhomematic.devicetypes.generic:HMGeneric.event: address=0000D5698E44E1:0, interface_id=test-pyhomatic, key=ERROR_CODE, value=0
INFO:pyhomematic.devicetypes.generic:HMGeneric.event: address=0000D5698E44E1:0, interface_id=test-pyhomatic, key=UNREACH, value=False
INFO:pyhomematic.devicetypes.generic:HMGeneric.event: address=0000D5698E44E1:0, interface_id=test-pyhomatic, key=OPERATING_VOLTAGE, value=1.3
INFO:pyhomematic.devicetypes.generic:HMGeneric.event: address=0000D5698E44E1:1, interface_id=test-pyhomatic, key=STATE, value=1

**Comment by danielperna84** [comment]
How about toggeling the switch? Have you tried out the new test-script?

**Comment by elajoie** [comment]
https://gist.github.com/elajoie/b38543246a68d6cbb0d1bdaee613a383

**Comment by danielperna84** [comment]
Could you please try it without using the -c parameter?

**Comment by elajoie** [comment]
It was with -c.

**Comment by elajoie** [comment]
Worked but no change:
python3 test.py -l 192.168.0.22 -r 192.168.0.4 -rp 2010 -a 0001D3C98DD73F:3 --toggle --debug

############################
{'0000D5698E44E1': <pyhomematic.devicetypes.sensors.IPShutterContact object at 0x7f4206b45cf8>, '000915698E4174': <pyhomematic.devicetypes.generic.HMDevice object at 0x7f4206b459e8>, '0001D3C98DD721': <pyhomematic.devicetypes.actors.IPSwitchPowermeter object at 0x7f4206b45f98>, '0001D3C98DD73F': <pyhomematic.devicetypes.actors.IPSwitchPowermeter object at 0x7f4206b45e80>, '0001D3C98DD70F': <pyhomematic.devicetypes.actors.IPSwitchPowermeter object at 0x7f4206b53160>, '000215698E4478': <pyhomematic.devicetypes.actors.IPSwitch object at 0x7f4206b45dd8>}
******************************
DEBUG:pyhomematic._hm:ServerThread.getAllSystemVariables: Exception: no element found: line 1, column 0
Read all: {}
******************************
Now waiting for events/callback
DEBUG:pyhomematic._hm:ServerThread.stop: Deregistering proxy
INFO:pyhomematic._hm:Shutting down server
DEBUG:pyhomematic._hm:ServerThread.stop: Stopping ServerThread
INFO:pyhomematic._hm:Server stopped

**Comment by danielperna84** [comment]
Don't include the channel in the address. The address always is just the part without the channel.

What I just saw is, that the IPSwitch implementation might be incomplete. I'm talking about the actors.py files.

Could you please replace the current IPSwitch-Class with this code and test again?

```python
class IPSwitch(HMActor, HelperActorState, HelperActionOnTime):
    """
    Switch turning attached device on or off.
    """

    @property
    def ELEMENT(self):
        return [3]

    def is_on(self, channel=1):
        """ Returns True if switch is on. """
        return self.get_state(channel)

    def is_off(self, channel=1):
        """ Returns True if switch is off. """
        return not self.get_state(channel)

    def on(self, channel=1):
        """Turn switch on."""
        self.set_state(True, channel)

    def off(self, channel=1):
        """Turn switch off."""
        self.set_state(False, channel)
```

**Comment by elajoie** [comment]
Output below. I also captured a manual toggle via CCU2 at the end of the link:
https://gist.github.com/elajoie/cc1fd063a4b30dd92f4649df56d0206e

**Comment by elajoie** [comment]
If the switch is off the test will toggle it on.

**Comment by danielperna84** [comment]
In that case the test was successful. And that only started working after patching the actors.py?

**Comment by elajoie** [comment]
Yes.

**Comment by danielperna84** [comment]
Ok, then I'll push that. This won't appear in the next HASS version (0.30). But at least the shutter should be working.

**Comment by elajoie** [comment]
Excellent, thanks @danielperna84 !

Please let me know where/if I can help.  My Python is horrible but functional so it would need reviewing.

**Comment by danielperna84** [comment]
Thinking of it, the switches may be visible in HASS. But you won't be able to switch them from there. But: the events are working. So you could see the actual status of them in HASS. That's just an optimistic theory, but better than nothing.

Since you are the first user we know of using IP devices, there probably will be some opportunities for testing. Soon we'll add support for multiple remotes to pyhomematic (the other branch you saw). I only use Homegear with RF devices, and pvizeli the CCU with RF devices. So we both can't really test if what I've done is working correctly.
But first we'll wait for the 0.30 HASS release and take care of your devices. If I'm not mistaken 0.30 will be released this weekend.

**Comment by bashmd** [comment]
Hi, ccu2 homematic ip user with thermostats here, let me know if i can be of use.

**Comment by danielperna84** [comment]
Hi @bashmd ,
yes you can. Depending on your skills you may either try to do the thermostat-implementation yourself and then create a pull request, or you can use the [datapoints.py](https://github.com/danielperna84/pyhomematic/blob/master/datapoints.py) script to retrieve the datapoints and post it via gist like elajoie did. For the script to work you should clone pyhomematic to use the latest code.

**Comment by danielperna84** [comment]
@elajoie 
Would it be possible for you to checkout the branch [this](https://github.com/danielperna84/pyhomematic/pull/42) pull request is about and report if you can get the regular devices and IP devices running in parallel?
From the python shell it would be done something like this:
```python
import logging
from pyhomematic import HMConnection

logging.basicConfig(level=logging.DEBUG)

def systemcallback(src, *args):
    print(src)
    for arg in args:
        print(arg)

pyhomematic = HMConnection(interface_id="myserver",
                           local="192.168.0.2",
                           localport=7080,
                           remotes={'hmrf': {'ip': '192.168.0.4', 'port': 2001}, 'hmip': {'ip': '192.168.0.4', 'port': 2010}}
                           autostart=True,
                           systemcallback=systemcallback)
print(pyhomematic.devices)
```

**Comment by danielperna84** [comment]
Meanwhile Home Assistant 0.34 has been released, which includes support for HomeMatic IP (at least a few devices). Can you confirm it is working?

**Comment by danielperna84** [comment]
I myself can now at least confirm, that the HMIP-PSM is working. With 0.35.1 as a switch, and as soon as my PR for HASS gets merged also as a powermeter.

**Comment by danielperna84** [comment]
I'll close this issue since in general HMIP support is available now. For specific requests for devices separated issues may be opened.
