### ISSUE TITLE
Allow to enable / disable SSL checks jsonRpcPost

### ISSUE THREAD

**Issue by danielperna84** [danielperna84/pyhomematic#372]
The `jsonRpcPost` method tries to verify SSL. This will fail with self-signed certificates. There should probably be an option to disable SSL checks.

Here's the related issue in the forum: https://community.home-assistant.io/t/homatic-ssl-certificate-verify-failed-ip-address-mismatch/263870

**Comment by GM-Alex** [comment]
Is there an estimate when the next version with this fix will be released. Since that happens I'm unable to read the system variables from raspberrymatic or do you have a suggestion for a workaround?

**Comment by danielperna84** [comment]
This might not be integrated at all. If [this](https://github.com/home-assistant/core/pull/47609) pull request doesn't get merged in Home Assistant, users won't be able to set the required port for my changes to work. I do have to release a new version anyways though. Thanks for reminding.

**Comment by GM-Alex** [comment]
Wouldn't it enough to change the version at the requirements_all.txt to the new release and run `pip install --upgrade -r requirements_all.txt`? Wouldn't that fix my `RPCFunctions.jsonRpcPost: Exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1125)>` error?

**Comment by danielperna84** [comment]
No, because currently it is hardcoded to port 80. Hence it will never connect to the correct SSL-port. That's why the change in Home Assistant is required to allow to configure a different port.

**Comment by GM-Alex** [comment]
I tested it and it works like expected if I'm setting the right port and disable the certificate check. Until the official release I now have at least a workaround. Thank you for your work and this project!
