### ISSUE TITLE
Support for device HB-WDS40-THP-O

### ISSUE THREAD

**Issue by SuperMasterPhoenix** [danielperna84/pyhomematic#373]
**Is your feature request related to a problem? Please describe.**
I would like to have support for the self-build device HB-WDS40-THP-O (temperature, humidity and air pressure sensor)

**Describe the solution you'd like**
Add the following line in `sensors.py` to the list of `DEVICETYPES`:
`"HB-WDS40-THP-O": WeatherStation,`

I have tested the changes in my Home Assistant installation and I get at least to correct values for temperature, humidity and air pressure. So now it would be perfect to also have the changes in the official version of pyhomematic.

**Comment by danielperna84** [comment]
> and I get at least to correct values for temperature, humidity and air pressure.

That sound as if other measurements are missing. And if the class provides datapoints which the device doesn't have, then this wouldn't be the correct solution as it would create disfunctional entities. Please post the device details you get by following the instructions from [this](https://github.com/danielperna84/pyhomematic/issues/28#issue-162335385) post.

**Comment by SuperMasterPhoenix** [comment]
Sorry, what I wrote was missleading. The device only delivers the mentioned three values.
Nevertheless I should have added the device descriptions from your script directly, so here they are: https://gist.github.com/SuperMasterPhoenix/0abe543ee50d66f6dfa967a25ea951fe
