### ISSUE TITLE
Not possible to control tilt

### ISSUE THREAD

**Issue by lukasvice** [danielperna84/pyhomematic#381]
**Home Assistant version (if applicable):**
2021.2.3

**Describe the bug**
I have a problem to set the tilt position with a HMIP-BBL blind actuator.
This could be related to issue #241.

It looks like currently it's not possible to `set_cover_tilt_position` or `close_cover_tilt`/`open_cover_tilt` if the position and tilt values are not correct. It seems when I `set_cover_tilt_position`, it moves to the (wrong) position value and sets the tilt position on that position.

**To Reproduce**
1. Close the blind
2. Open the blind with the wall switch and stop it at some time. The position value will be 100.
3. Run `close_cover_tilt`
4. The blind will move all the way up instead of just close the slats

**Expected behavior**
With `set_cover_tilt_position` / `close_cover_tilt` / `open_cover_tilt`, only the slats should be closed or opened, but the blind should remain at the current position.

**Comment by m4k5ym** [comment]
I confirm this issue.

Got seven BBL actors on latest firmware and they always drive up if any kind of tilt position is set.

**Comment by m4k5ym** [comment]
It might be related to pull request #365

**Comment by m4k5ym** [comment]
I downgrade to 2021.1.5 as it is using 0.1.70 of pyhomematic. It is latest version before #365 merged to 0.1.71

**Comment by danielperna84** [comment]
> I downgrade to 2021.1.5 as it is using 0.1.70 of pyhomematic regarding manifest.json in homematic core.
> 
> It is latest version before #365 have been merged to 0.1.71

And does it work there correctly?

**Comment by m4k5ym** [comment]
I can't say it for now. Next automation is triggered tomorrow morning. Then we will know more.

I'll keep you posted.

**Comment by m4k5ym** [comment]
Okay with Version 2021.1.5 tilting is functional.

**Comment by m4k5ym** [comment]
Now I might have the issue that cover.open_cover and cover.close_cover isn't working properly. Means I have to use cover.set_cover_position with absolute values to solve this.

**Comment by danielperna84** [comment]
This should be working with the [new integration](https://github.com/danielperna84/custom_homematic).
