### ISSUE TITLE
Support for the Alternative Open Source Firmware for HM_LC_Sw1PBU_FM

### ISSUE THREAD

**Issue by malfino** [danielperna84/pyhomematic#382]
It would be super nice, if the HM_LC_Sw1PBU_FM with the custom firmware ( https://github.com/jabdoa2/Asksin_HM_LC_Sw1PBU_FM/ ) could be supported by pyhomematic.

The  HM_LC_Sw1PBU_FM-Custom work fine under raspberrymatic (CCU3) with documentation from here: https://github.com/wiresio/CCU2

But pyhomematic doesn't know this custom device type and that's why it doesn't work in home-assistant. 

I tried to understand, how to modify the pyhomematic scripts in order to provide support for a custom device.

Even if I rename all the occurrences of HM_LC_Sw1PBU_FM to HM_LC_Sw1PBU_FM-Custom in the files /devicetypes/actors.py /devicetypes/json/device_descriptions.json and /devicetypes/json/device_details.json it doesn't work.

According to this module
https://github.com/jabdoa2/Asksin_HM_LC_Sw1PBU_FM/blob/master/fhem/99_Asksin_HM_LC_Sw1PBU_FM_CustomFW.pm
the device-type is F0A9. I guess, I need to enter this somewhere in the pyhomematic code, but I don't see any place where. 
Maybe someone can point me in the right direction, how to enable this custom device, so it shows up in home assistant?

Thank you!

So

**Comment by danielperna84** [comment]
You actually just have to add an extra line [here](https://github.com/danielperna84/pyhomematic/blob/0e4cf8bdddfd791bb456f4cf242561290148f048/pyhomematic/devicetypes/actors.py#L998) with the new name. This of course requires, that the device doesn't present itself as `HM-LC-Sw1PBU-FM`. If it does, I don't see a way how pyhomematic should know its different from the regular version.

**Comment by malfino** [comment]
Now, that you pointed me in the right direction, I noticed, that the exact name is written in capitals in homematic.
Once I inserted HM_LC_Sw1PBU_FM-CUSTOM instead of HM_LC_Sw1PBU_FM-Custom the devices were recognized and displayed in home assistant.

They are called switch.leq01234567, but they don't do anything. :-( 

The custom firmware creates 4 channels on the device:

Button_1	pressing the switch up (channel 1)
Button_2	pressing the switch down (channel 2)
Switch_1 Relais (channel 3)
Switch_2	virtual channel to toggle the device. it measures the power current in order to find out, if the lamp is currently on or off  (channel 4). used for multiway switching

I would like to issue a toggle to channel 4, if I control it from home assistant.
For that I would need to modify the helper functions in actors.py, right?

Thank you!

**Comment by malfino** [comment]
I got a lot further.

I can turn on and off the switches 

```
#!/usr/bin/python3
from xmlrpc.client import ServerProxy
p = ServerProxy("http://192.168.1.17:2001")
# turn on light
#p.setValue("xxxxxxxxxxxx:4", "STATE", True)
# turn off light
#p.setValue("xxxxxxxxxxxxx:4", "STATE", False)
```
I can also turn on and off from home assistant through this under action of an automation:

```
service: homematic.set_device_value
data:
  address: LEQxxxxx
  channel: 4
  param: STATE
  value: false

```

I could now build a switch. But I need to get the sensor data from that device, so I know, if the switch is on or off.
And here I struggle at the moment.

p.getValue("LEQxxxxxx:4", "STATE")
throws a strange state:
```
Traceback (most recent call last):
  File "./pyhomematic.py", line 4, in <module>
    p.getValue("LEQ0762556:4", "STATE")
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1169, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1341, in parse_response
    return u.close()
  File "/usr/lib/python3.8/xmlrpc/client.py", line 655, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -1: 'Failure'>

```
The param STATE is found, because if I change it, it says "xmlrpc.client.Fault: <Fault -5: 'Unknown parameter'>". 
So there must be something else going on, causing this Fault -1:'Failure' thing.

According to the xml file from the CCU3 (https://github.com/wiresio/CCU2/blob/master/rf_s_1conf_644_le_v1_5.xml ) 
it should expose the following PARAMs

```
<paramset_defs>
    <paramset id="switch_valueset">
      <parameter id="STATE" operations="read,write,event" control="SWITCH.STATE">
        <logical type="boolean" default="false"/>
        <physical type="integer" interface="command" value_id="STATE">
          <set request="LEVEL_SET"/>
          <get request="LEVEL_GET" response="INFO_LEVEL" process_as_event="true"/>
          <event frame="INFO_LEVEL" auth_violate_policy="get"/>
          <event frame="ACK_STATUS" auth_violate_policy="get"/>
          <event frame="INFO_POWERON" auth_violate_policy="get"/>
          <reset_after_send param="ON_TIME"/>
        </physical>
        <conversion type="boolean_integer" threshold="1" false="0" true="200"/>
      </parameter>
```

How can I see the raw reply, that was replied to the getValue method?

**Comment by malfino** [comment]
With a little modification in the helper function, the switch finally works in home-assistant. 

Maybe it can be included in the main repository or helps anyone else here:


```
--- actors.py.org       2021-02-23 08:50:45.961602811 +0000
+++ actors.py   2021-02-23 08:49:47.297814878 +0000
@@ -238,6 +238,8 @@
     def ELEMENT(self):
         if "LC-Sw2" in self.TYPE or "Sec-SFA-SM" in self.TYPE:
             return [1, 2]
+        elif "HM-LC-Sw1PBU-FM-CUSTOM" in self.TYPE:
+            return [4]
         elif "LC-Sw4" in self.TYPE:
             return [1, 2, 3, 4]
         elif "Re-8" in self.TYPE:
@@ -996,6 +998,7 @@
     "HM-LC-Sw1-Ba-PCB": Switch,
     "HM-LC-Sw1-SM-ATmega168": Switch,
     "HM-LC-Sw1PBU-FM": Switch,
+    "HM-LC-Sw1PBU-FM-CUSTOM": Switch,
     "HM-LC-Sw2-SM": Switch,
     "HM-LC-Sw2-FM": Switch,
     "HM-LC-Sw2-FM-2": Switch,

```

**Comment by danielperna84** [comment]
Should also be working with the [new integration](https://github.com/danielperna84/custom_homematic).
