### ISSUE TITLE
Temp-Offset missing in HmIP-eTRV-2 thermostat

### ISSUE THREAD

**Issue by filewalker1** [danielperna84/pyhomematic#384]
Hello!

i am using CCU3 with HmIP-etrv-2 heating thermostat. not all options are available within the HomeAssistant. I need especially the temperature-offset. iOBroker has all the values available - is there a possibility to get these values in HA?

now i can only get the following ones:
`hvac_modes:
  - auto
  - heat
  - 'off'
min_temp: 4.5
max_temp: 30.5
target_temp_step: 0.5
preset_modes:
  - boost
current_temperature: 21.5
temperature: 21
preset_mode: null
id: XXXXXXXXXXX
interface: hmip
battery: High
rssi_device: -65
valve: 4
level: 0.59
mode: null
voltage: 2.7
friendly_name: XXXXXXXX
supported_features: 17`

**Comment by danielperna84** [comment]
Sadly this can't be done with the current architecture. The `TEMPERATURE_OFFSET` parameter is a device setting. These settings reside within the `MASTER` Paramset. pyhomematic only works with paramters that are in the `VALUES` paramset.

This likely __won't__ change. Such values have to be fetched from the devices directly, which would produce a lot of RF-traffic, consuming a lot of the already limited duty cycle.

If there are other parameters within the `VALUES` paramset you think are useful, feel free to submit a pull request that adds it to the attibute node.

I also don't think exposing this setting is useful. You'll only set it to the correct value when deploying the device. Hence you already know what the value is, and it won't change without you doing that yourself.
