### ISSUE TITLE
Report LOW_BAT for HmIP-PCBS-BAT

### ISSUE THREAD

**Issue by SuperMasterPhoenix** [danielperna84/pyhomematic#386]
**Is your feature request related to a problem? Please describe.**
I've recognized that no LOW_BAT entity is reported the the actor HmIP-PCBS-BAT.

**Describe the solution you'd like**
I'd like to see it in Home Assistant when Homematic reports that the device battery is low.

**Describe alternatives you've considered**
For testing purpose I've extended the class `actors.py` like following from
`class IPSwitch(GenericSwitch, HelperActionOnTime):`
to
`class IPSwitch(GenericSwitch, HelperActionOnTime, HelperLowBatIP):`
plus the according import. I now get the LOW_BAT entity as expected in Home Assistant for this device.

**Additional context**
I'm not that deep into python programming so I don't know what side effects this change has on other devices. I also do not own other Homematic-IP devices to test this change. If you could get me some advice on what to consider I would create a PR to add LOW_BATT for HmIP-PCBS-BAT

**Comment by danielperna84** [comment]
By adding the helper to the `IPSwitch` class, non-battery devices would also get the parameter. That shouldn't be the case though, as that will query the device for the according value during startup. The correct solution would be to use a subclass of `IPSwitch` which only battery-powered devices make use of.
