### ISSUE TITLE
Support for HmIP-DLD (Homematic IP KeyMatic)

### ISSUE THREAD

**Issue by Havoc85** [danielperna84/pyhomematic#394]
Probably it will not be much different to HM-Sec-Key (https://github.com/danielperna84/pyhomematic/blob/b771ab8a0022ea4e6011fe433860a2b260a44891/pyhomematic/devicetypes/actors.py#L1100) --> https://github.com/danielperna84/pyhomematic/blob/b771ab8a0022ea4e6011fe433860a2b260a44891/pyhomematic/devicetypes/actors.py#L488

I already attached one to my Raspberrymatic CCU (3.57.4.20210320) and it's working nicely with a HmIP-KRCA. Is there any way to support you with logs/informations?

Also see German Community: https://homematic-forum.de/forum/viewtopic.php?f=58&t=66534 and Vendors Page with some Downloads: https://de.elv.com/homematic-ip-smart-home-tuerschlossantrieb-hmip-dld-154952

**Comment by danielperna84** [comment]
Please provide the device details as explained [here](https://github.com/danielperna84/pyhomematic/issues/28#issue-162335385).

**Comment by Havoc85** [comment]
> Please provide the device details as explained [here](https://github.com/danielperna84/pyhomematic/issues/28#issue-162335385).

Sorry. Of course: https://gist.github.com/Havoc85/7946740cfaa7af4c82adc05adec43b13

**Comment by leinich** [comment]
The relevant datapoints for the current state are:
Channel 1 - LOCK_STATE (UNKNOWN, LOCKED, UNLOCKED)

To controll the DLD the relevant datapoint is:
Channel 1 - LOCK_TARGET_LEVEL (LOCKED, UNLOCKED, OPEN)
 
 
To open the the lock you may use folling in HA until it is supported:
homematic.set_device_value
address: "SERIALRNR"
channel: 1
param: LOCK_TARGET_LEVEL
value: OPEN

Unforuntatelly I was not able to get my changes to work with an IPKeymatic class.
Can someone look into this?


Is this the right approach? @danielperna84 

```
class IPKeyMatic(HMActor, HelperInhibit, HelperRssiPeer, HelperLowBatIP):
    def __init__(self, device_description, proxy, resolveparamsets=False):
        super().__init__(device_description, proxy, resolveparamsets)
        self.ACTIONNODE.update({"OPEN": self.ELEMENT})
        self.ATTRIBUTENODE.update({"STATE_UNCERTAIN": self.ELEMENT,
                                   "ERROR": self.ELEMENT,
                                   "LOWBAT": self.ELEMENT})
    def is_unlocked(self, channel=None):
        if self.getAttributeData("LOCK_STATE ") == "UNLOCKED":
              return True
        return False

   def is_locked(self, channel=None):
        if self.getAttributeData("LOCK_STATE ") == "LOCKED":
              return True
        return False

    def unlock(self, channel=None):
         return self.setValue("LOCK_TARGET_LEVEL", "UNLOCKED")     

    def lock(self, channel=None):
        return self.setValue("LOCK_TARGET_LEVEL", "LOCKED")     

  def open(self):
        return self.setValue("LOCK_TARGET_LEVEL", "OPEN")     

    @property
    def ELEMENT(self):
        return [1]
```

**Comment by danielperna84** [comment]
@leinich 

I think this won't work with pyhomematic. Judging by the data you have provided, the actual state of the lock is handled with a different parameter. pyhomematic does not support that (we're already having the same issue with blinds, dimmers etc., basically all the new HmIP devices where the actual state and target states are on different parameters). That's why I'm currently working on the new library [hahomematic](https://github.com/danielperna84/hahomematic), where such scenarios shouldn't be a problem anymore when I'm done.

So I guess this device won't be supported in the near future as long as pyhomematic is still the way HomeMatic is provided in Home Assistant. 😕

**Comment by ProfDrYoMan** [comment]
Is #394 also included into home assistant already? There is no sensor reflecting the lock status showing up for me. There is only the battery status.

**Comment by danielperna84** [comment]
It's added [here](https://github.com/home-assistant/core/blob/c7c1d6000f2205710887de95cc41605c3e2a3096/homeassistant/components/homematic/const.py#L183), but as a binary_sensor. That's the problem I believe.

**Comment by ProfDrYoMan** [comment]
Well yes, it has 3 values and should be a sensor. Can you take care of it? I lack the knowledge here.

**Comment by NotSoFunnyClown** [comment]
I still just get a battery sensor and don't have any other sensors for the HmIP-DLD. Is this still an issue?
Is there any solution to lock and unlock the HmIP-DLD? The manufacturer recently added the function to lock/unlock by an external switch.

**Comment by danielperna84** [comment]
@NotSoFunnyClown 

As mentioned [here](https://github.com/danielperna84/pyhomematic#deprecation-warning), this project is being deprecated and therefore not worked on anymore. Check out the new (custom) integration. There the lock is working.

**Comment by NotSoFunnyClown** [comment]
@danielperna84

Ok thank you. I will give it a try. I've already installed it. But does it work with the Homematic IP Access Point or only CCU/RaspberryMatic?

**Comment by danielperna84** [comment]
The new integration and also the old integration this repository is about both require a CCU. If you are using the Access Point, then it is a totally different integration you are talking about. That being said, the cloud-integration is not being worked on anymore as well. So your best choice is to invest into a CCU based solution. So either a CCU itself, or RaspberryMatic, Debmatic or something similar. I think you should ask for help in the Homematic Forum for advice on what makes sense for you.

**Comment by ProfDrYoMan** [comment]
@NotSoFunnyClown , if you want to stick with the old setup you can check here:
https://www.home-assistant.io/integrations/homematic/#integrating-hmip-dld

Works for me flawless.

**Comment by danielperna84** [comment]
Device is working with the [new integration](https://github.com/danielperna84/custom_homematic). Therefore closing this issue.
