### ISSUE TITLE
proxy not available in devices

### ISSUE THREAD

**Issue by jazzaj** [danielperna84/pyhomematic#4]
Proxy for all HMDevices is "False" to me. 
Root cause seems to be that at time constructing RPCFunctions the function _server.connect() is not yet called. Only this function will create the proxy.
I tried to correct the order but this created hundreds of "HMDevice.updateParamset: Paramset empty." error messages.

**Comment by danielperna84** [comment]
Have a look at the 0.0.1 Tag of this repository. Back then this was handeled differently. Maybe looking at how it was done gives a hint on how to solve this.
I will test with the current version again. For me, using the library like in the example.py, everything worked until now.

**Comment by danielperna84** [comment]
You are correct. It seems like I am using an older version productively which works. I'll review the corresponding PR.

**Comment by danielperna84** [comment]
I have pushed my solution for the problem. Feel free to test and give feedback. If it works for you as well I'll close the two PRs.
Using the following script for testing works for me:

```python
#!/usr/bin/python3
import time, sys
import logging
logging.basicConfig(level=logging.DEBUG)

import homematic
homematic.create_server(interface_id="myserver",
                            local="ip.ad.dr.ess",
                            localport=7080,
                            remote="ip.ad.dr.ess",
                            remoteport=2001)

homematic.start()
while not homematic.devices:
    time.sleep(1)
device = next (iter (homematic.devices.values()))
print(device)
print(device._proxy)
homematic.stop()
sys.exit(0)
```
