### ISSUE TITLE
HmIPW-WTH & HmIPW-FAL230-C6 Integration

### ISSUE THREAD

**Issue by XDLUKE** [danielperna84/pyhomematic#402]
Good morning,

The following are the results of the script "get_device_data.py".

I have exported the following device types:

- [ ] HmIPW-WTH [https://gist.github.com/XDLUKE/c8c82ea972731c731dc6ca334216f899](url)

- [ ] HmIPW-FAL230-C6 [https://gist.github.com/XDLUKE/24fa1b437221a8425ee9752b783d6959](url)

Could someone please take a look at this when you get a chance and integrate it if possible?

If you need any further information, please do not hesitate to contact me.

Unfortunately, my background knowledge is not sufficient for me to dare to do this myself...

Many thanks in advance.

XDLUKE

--------------------------------------------------

Guten Morgen,

nachfolgend die Ergebnisse des Scripts "get_device_data.py".

Ich habe folgende Geräte Typen exportiert:

- [ ] HmIPW-WTH [https://gist.github.com/XDLUKE/c8c82ea972731c731dc6ca334216f899](url)

- [ ] HmIPW-FAL230-C6 [https://gist.github.com/XDLUKE/24fa1b437221a8425ee9752b783d6959](url)

Könnte sich das bitte mal jemand bei Gelegenheit anschauen und falls möglich integrieren?

Sollten noch weitere Informationen benötigt werden stehe ich gerne zur Verfügung.

Meine Hintergrund Kenntnisse reichen jedoch leider nicht aus, das ich mich hier selbst rantraue...

Vielen Dank vorab.

XDLUKE

**Comment by ChecksumDK** [comment]
Please add support for the following devices as well. Its just variants of HmIPW-FAL230-C6

- HmIPW-FAL230-C10
- HmIPW-FAL24-C6
- HmIPW-FAL24-C10

I can provide "get_device_data.py" for HmIPW-FAL230-C10 if needed.

**Comment by danielperna84** [comment]
The [new integration](https://github.com/danielperna84/custom_homematic) provides as much support for these types of devices as possible. There are certain features though, which cannot be controlled via Home Assistant. So for that there's no solution.
