### ISSUE TITLE
New version ETA

### ISSUE THREAD

**Issue by pannal** [danielperna84/pyhomematic#404]
Hey there, thank you for this great library.

I'm using it successfully with the latest Home Assistant docker version. I've got multiple HmIP-STH and would benefit greatly from the changes in develop, that will probably see the light of day in version 0.1.73.

Is there an ETA for 0.1.73? If not I'd try to get the development branch working with my HA instance. Are there any breaking changes/dependency changes in there?

Thanks in advance

**Comment by danielperna84** [comment]
I'll publish a new version once https://github.com/danielperna84/pyhomematic/pull/403 has been merged. 👍

**Comment by pannal** [comment]
Awesome. To change week profiles I currently use `homematic.set_device_value` with:
```
interface: ip
address: XXXXXXXXXXX
channel: 1
param: ACTIVE_PROFILE
value: 2
value_type: int
```

That works quite well - the documentation's example uses `put_paramset` which is more complicated.
