### ISSUE TITLE
Entity sabotage for HM-Sec-MDIR

### ISSUE THREAD

**Issue by wokiener** [danielperna84/pyhomematic#412]
HA integration for homematic provides the following entities for motion detection devices HM-Sec-MDIR: motion, brightness, lowbat. I would like to request an additional entity for sabotage for the HM-Sec-MDIR-3, HM-Sec-MDIR-2, and HM-Sec-MDIR.

**Comment by danielperna84** [comment]
This probably could be done by introducing a new class based on [Motion](https://github.com/danielperna84/pyhomematic/blob/17903fa67fa8f512201ef1bb3ddf2f14a67f2cf5/pyhomematic/devicetypes/sensors.py#L352), which also inherits from [HelperSabotage](https://github.com/danielperna84/pyhomematic/blob/17903fa67fa8f512201ef1bb3ddf2f14a67f2cf5/pyhomematic/devicetypes/helper.py#L6). This would add the `error` attribute to the entity. As this probably won't be used often I don't think generating a full entity is reasonable. By using the attribute only those who are interested in the sabotage-state have to use a template-sensor to be able to work with the state.

**Comment by wokiener** [comment]
understood, thanks for the background explanation and the direction forward.
