### ISSUE TITLE
HmIPW-FALMOT-C12 Integration

### ISSUE THREAD

**Issue by dieterguenter** [danielperna84/pyhomematic#413]
Hello,

i have attached device_description and paramset_description for HmIPW-FALMOT_C12.

Link: https://gist.github.com/dieterguenter/0107dbf362f3f445909de54e3cf13499

**Comment by danielperna84** [comment]
The [new integration](https://github.com/danielperna84/custom_homematic) provides as much support for these types of devices as possible. There are certain features though, which cannot be controlled via Home Assistant. So for that there's no solution.
