### ISSUE TITLE
Integration: HmIP-USBSM

### ISSUE THREAD

**Issue by maedball** [danielperna84/pyhomematic#414]
Please add support for the new USB Actor:

Description attached: 
[Description.zip](https://github.com/danielperna84/pyhomematic/files/6722259/Description.zip)

**Comment by danielperna84** [comment]
The files you have provided are empty. ☝

**Comment by maedball** [comment]
Hmm interesting... The script does not seem so see this device, I tried it with the serial number... other devices seem to work fine...

**Comment by danielperna84** [comment]
That usually is cause by old cache-files created by the script. Delete them and re-run the script, then the new device should be included.

**Comment by maedball** [comment]
Bingo ;-)

Here you go

[HmIP-USBSM.zip](https://github.com/danielperna84/pyhomematic/files/6728864/HmIP-USBSM.zip)

**Comment by danielperna84** [comment]
I believe this device should work if you add it as a `IPSwitchPowermeter` like [here](https://github.com/danielperna84/pyhomematic/blob/17903fa67fa8f512201ef1bb3ddf2f14a67f2cf5/pyhomematic/devicetypes/actors.py#L1163). To also get the sensor entities, you'd have to include it [here](https://github.com/danielperna84/pyhomematic/blob/17903fa67fa8f512201ef1bb3ddf2f14a67f2cf5/pyhomematic/devicetypes/actors.py#L761) as well.

**Comment by maedball** [comment]
Unfortunately i am to stupid to find any of the pyhomematic files on my homeassistant os 6 install. Are they in an underlying container or am i really to stupid? I tried already your suggestion from a 2017 post about the hassio os, but it seem to have moved. Also a find / actors.py did not find any files.

**Comment by maedball** [comment]
Just as a sideremark to everyone else that is searching for the pyhomematic folder in homeassistant os: 

https://developers.home-assistant.io/docs/operating-system/debugging/#:~:text=Home%20Assistant%20OS%20is%20a%20hypervisor%20for%20Docker.,all%20installed%20addons%20run%20in%20separate%20Docker%20containers.

1) SSH to Homeassistant installation
2) docker exec -it homeassistant /bin/bash

Took me a while to realize that homeassistant os is using docker inside *facepalm

**Comment by maedball** [comment]
It took me a while but I think I get the logic now :-) You helped a man help himselfs ;-)
