### ISSUE TITLE
HmIP-DRSI1 without RSSI

### ISSUE THREAD

**Issue by emufan** [danielperna84/pyhomematic#428]
Make sure you are running the latest version of pyhomematic (and Home Assistant) before reporting an issue.

**Home Assistant version (if applicable):**
2021.8.8

**Describe the bug**
I'm not sure, if this is related to only HmIP-DRSI1 or to all IPSwitch devices? Do they report RSSI to HA? From the coding, I think HmIP-DRSI1 should report and [here](https://gist.github.com/malkie-hass/45e5b35837141d065e3c38e0092f32c0) in [here](https://github.com/danielperna84/pyhomematic/issues/353). is seems, that the attributes are there.

So is it related only to HmIP-DRSI1 or to all IPSwitch devices or a special cause, that it is not there and I only didn't find the discussion about this? I would volunteer to add HelperRssiDevice to IPSwitch, if this is related to all of them or create a new one with this.

**Expected behavior**
RSSI value in HA for HmIP-DRSI1

**Comment by danielperna84** [comment]
I don't think `IPSwitch` devices report RSSI currently. Adding the helper would be the correct approach to fix this. 👍
Just test it locally and see if it works as expected.

**Comment by emufan** [comment]
Would like to do so, but unfortunately do not know, how. 😥

I'm on HAOS and familiar with manipulating of the core files from components and integrations via the custom_component-trick, but not how to manipulate the site-packages/requirements like pyhomatic in this docker in docker in whatever structure form HAOS.

**Comment by danielperna84** [comment]
I'm not that familiar with HAOS. Maybe [this](https://community.home-assistant.io/t/editing-component-files-in-hassio/24273/24) thread can help you find the files. 👍

**Comment by emufan** [comment]
I have already searched and find this thread before. Till now without success.

But if I have some time at one of the next weekends, I'll setup a core-docker on NAS and try it there.

But if other ones having any clue how to modify site-packages/requirements like pyhomatic in HAOS, I would be very interested in this.

**Comment by emufan** [comment]
Et voila:

![image](https://user-images.githubusercontent.com/22775515/131555362-b6eb49ec-d328-4416-b279-4a2475c857c9.png)

The question is now, is this only related to the HmIP-DRSI1 or to all devices of the class IPSwitch? So either:

1. I will create a new class with HelperRssiDevice, e.g. IPSwitchRssi and assign this only to HmIP-DRSI1 or
2. add HelperRssiDevice to the existing class IPSwitch and this is then relevant for all devices of this class. 

I do not know, what will happen if I would go way 2 and another device is not returning this? Error or n/a for this attribute?

**Comment by danielperna84** [comment]
Go with approach 1. When going with 2 there could be devices that don't support it, and then users will complain about the warnings. 👍
