### ISSUE TITLE
Support particulate matter sensor HmIP-SFD

### ISSUE THREAD

**Issue by hzpz** [danielperna84/pyhomematic#438]
First of all: thank you for this great library! I've been using it (indirectly) with Home Assistant for a while now and it integrates my HomeMatic devices perfectly.

Unfortunately I realised that is has to explictly support each device and that the particulate matter sensor HmIP-SFD is not supported yet. Let's change that :-) 

I already ran `get_device_data.py` and created a gist: https://gist.github.com/hzpz/e204fd93481731f335e155291849cb52

Would it be wise to try to integrate the device in my "production" instance of Home Assistant or is the virtual machine the way to go?

**Comment by hzpz** [comment]
Thanks for merging my PR so quickly 👍 What are the next steps? I can create the PR for the Home Assistant integration, but I guess, you'll need to release a new version of pyhomematic first, right?

**Comment by danielperna84** [comment]
Yes, the PR for HA would be the next step. But as you say, I first have to release the new version of pyhomematic, for which I myself have to create a PR for HA anyways. So I guess it would be best if you post a diff of what has to be changed in `HM_UNIT_HA_CAST` and `HM_DEVICE_CLASS_HA_CAST`. But before doing that I'd actually wait until https://github.com/home-assistant/core/pull/57396 has been merged, as it drastically changes the code and I don't want to inject a conflict. Apart from that I want to wait a bit if something else will be contributed. I don't want to ship a new release that only adds support for a single device. But I'll release it anyways after a few weeks, even if nothing else will be added.

**Comment by hzpz** [comment]
You're right, the long-term statistics PR does change the code significantly and will create a conflict with my current patches. Once the PR is merged I'll post updated patches.

And I totally understand that you don't want to create a new release for every little change. I guess in the meantime I have to figure out, how to patch my production instance of Home Assistant 😃

**Comment by danielperna84** [comment]
> You're right, the long-term statistics PR does change the code significantly and will create a conflict with my current patches. Once the PR is merged I'll post updated patches.

👍

> And I totally understand that you don't want to create a new release for every little change. I guess in the meantime I have to figure out, how to patch my production instance of Home Assistant

I know there are ways to modify the system, even with container-based installations. I always forget how it's done because I only use the core installation. But the forum has topics that will help you with that. 👍

**Comment by hzpz** [comment]
It got merged! 🥳 

Here's a gist with the updated patches: https://gist.github.com/hzpz/a29eae015a1521cdadf8d5c79b8ba161

**Comment by danielperna84** [comment]
I guess that patch isn't correct anymore because of even more changes there. But in any case, feel free to create a PR for Home Assistant. 👍

This issue here can be closed as in regards to pyhomematic there's nothing more to be done, right?

**Comment by hzpz** [comment]
> feel free to create a PR for Home Assistant

I'll try to find some time between the holidays.

> This issue here can be closed as in regards to pyhomematic there's nothing more to be done, right?

Yes indeed ✅

**Comment by hzpz** [comment]
Just fyi @danielperna84: HmIP-SFD is missing from the changelog for 1.77.

**Comment by danielperna84** [comment]
Yeah, I'll add that once I release the new version. I'll plan to do that early in January. Maybe until then some other things will be contributed. AFAIK the next Home Assistant release will be delayed, so early January should be finde to be included in the next HA release.

**Comment by hzpz** [comment]
> I'll plan to do that early in January.

Great 👍 I just realized that I'll have to wait for that release before I can submit a PR to Home Assistant.


> AFAIK the next Home Assistant release will be delayed

Indeed:
> We are skipping the January release because of the holidays. So, the first release in 2022, will be Wednesday, 2 February 2022.

(Source: https://www.home-assistant.io/blog/2021/12/11/release-202112/)

**Comment by danielperna84** [comment]
@hzpz 

I have created the PR for the dependency upgrade here: https://github.com/home-assistant/core/pull/63848

Could you please verify the changes work? I couldn't directly apply your patch as the code in HA has changed in the meantime.

**Comment by hzpz** [comment]
Sorry for being veeery late but I just wanted to confirm, that the HmIP-SFD works perfectly in vanilla Home Assistant now 🙂
