### ISSUE TITLE
Nach Update auf core-2021.11.0 ist der Wert illumination vom HmIP-SMI nicht verfügbar

### ISSUE THREAD

**Issue by EduardSarjadjuk** [danielperna84/pyhomematic#442]
Hallo, 

ich habe das Problem, dass nach dem Update auf den Core-2021.11.0 der Wert (illumination) von dem HmIP-SMI nicht verfügbar ist.
Ich habe 4 Stück von den Sensoren und es tritt bei allen auf.

In den Logs taucht auch nichts auf.

Gibt es eine Möglichkeit dies wieder herzustellen ?

Vielen Dank im Voraus !

**Comment by danielperna84** [comment]
@emufan das kam von dir. Hast du das Problem auch? Also ich habe nicht vergessen die neue Klasse [hier](https://github.com/home-assistant/core/blob/96c03aec06a24f8bb6f1957c19fb4bed9ca2175e/homeassistant/components/homematic/const.py#L157) hinzuzufügen. Insofern kann ich mir das Problem gerade nicht erklären.

**Comment by emufan** [comment]
Ja. Hatte ich hier ja auch:
https://github.com/danielperna84/pyhomematic/pull/425#issuecomment-940109052

Lokal hatte ich es hier ja so behoben, wie dann auch im Core PR hier:
https://github.com/home-assistant/core/pull/57521

Ich update nachher mal auf 2021.11 und teste und vergleiche mal.

**Comment by emufan** [comment]
home-assistant/core#57521 steht im Status Merged, aber die Änderungen sind nicht drin, zumindest nicht

![image](https://user-images.githubusercontent.com/22775515/140282756-379bc524-314d-4083-a291-2e3152205da7.png)

links .11, rechts mein local und der PR der const.py

Same here für die binary_sensor.py im PR

![image](https://user-images.githubusercontent.com/22775515/140282980-bc7f0605-06a3-473a-88a8-dc9290beceeb.png)

**Comment by emufan** [comment]
Update: Jo. Damit geht es auch in 2021.11. Habe den 2021.11 Stand genommen und nur die Dinge aus dem PR manuell eingebaut. Geht wie vorher.

**Comment by EduardSarjadjuk** [comment]
Danke für das schnelle Feedback !
Könntet ihr mir noch sagen wie ich das bei mir anpassen könnte ?

**Comment by emufan** [comment]
Wenn Du es schnell brauchst, lade Dir https://github.com/home-assistant/core/archive/refs/tags/2021.11.0.zip kopiere nur das Verzeichnis core-2021.11.0\homeassistant\components\homematic bei Dir ins config\custom_components Verzeichnis, sodass dann das homematic Verzeichnis ein Unterverzeichnis von custom_components ist.

Dann dort die drei Dateien const.py, binary_sensor.py und manifest.json mit den dreien aus dem beigefügten zip ersetzen, HA neu starten und es sollte passen.

[homematic.zip](https://github.com/danielperna84/pyhomematic/files/7474089/homematic.zip)

**Comment by SukramJ** [comment]
Der PR wurde erst vor 3 Tagen nach DEV ge-merged, also 4 Tage nach dem letzten HA Beta-Cut.
Damit dieser PR in das nächste minor Release aufgenommen wird musst du um einen Cherry-Pick bitten, am Besten mit verweis auf den Fehler.

**Comment by EduardSarjadjuk** [comment]
@emufan: Wenn ich das nach deiner Anleitung anpasse, muss ich dann etwas für zukünftige updates beachten ?
Bzw. habe ich durch diese Anpassung irgendwelche Nachteile in der Zukunft?

**Comment by emufan** [comment]
Wenn Du das Verzeichnis wieder löschst (z.B. wenn der Fehler durch das nächste Release wann auch immer behoben wird), wird wieder die "interne Version" genommen. Mehr passiert da eigentlich nicht.

**Comment by EduardSarjadjuk** [comment]
Danke dir für die Rückmeldung!

**Comment by danielperna84** [comment]
Sollte nun gefixt sein mit HA 2021.12.
