### ISSUE TITLE
Homematic HmIP-SRH "Sensor [...] entity description is missing."

### ISSUE THREAD

**Issue by hzpz** [danielperna84/pyhomematic#443]
I just took Home Assistant for a spin after home-assistant/core#57396 was merged and was greeted with the following warning:
> 2021-11-08 19:36:54 WARNING (SyncWorker_2) [homeassistant.components.homematic.sensor] Sensor (0007DA49A7XXXX STATE) entity description is missing. Sensor state (STATE) needs to be maintained

I know this is an issue of the Home Assistant integration and not pyhomematic, but I hope that @danielperna84 will handle it 🙂 

The entity is question is the STATE parameter of my HmIP-SRH rotary handle sensor. It still works fine in Home Assistant, but there is just no `STATE` in the new `SENSOR_DESCRIPTIONS` `dict`. Adding the following snippet to `SENSOR_DESCRIPTIONS` gets rid of the warning for me, but I'm unsure if it breaks anything else:
```
    "STATE": SensorEntityDescription(
        key="STATE"
    ),
```

**Comment by danielperna84** [comment]
Since this is a _bug_ in Home Assistant, it should also be tracked as an issue there. 👍

**Comment by hzpz** [comment]
Alright then: home-assistant/core#59400
