### ISSUE TITLE
HmIP-SCTH230 - Missing temperature value

### ISSUE THREAD

**Issue by eikowagenknecht** [danielperna84/pyhomematic#448]
**Home Assistant version (if applicable):**
2021.11.5

**Describe the bug**
The device has a temperature sensor, but it's not discovered. I see the following:

![image](https://user-images.githubusercontent.com/1475672/144466440-8d12b960-d20a-4f29-9e5f-13ddd3d13af1.png)
(the 2nd is disabled by me since I don't need it)

**Expected behavior**
Temperature sensor should be available as well

**Screenshots**
![image](https://user-images.githubusercontent.com/1475672/144466624-189b49e7-abc5-49a3-83b6-aeb6ae7ff497.png)
It's on Channel 4 in the CCU

**Comment by danielperna84** [comment]
This is a Home Assistant issue, not pyhomematic. The parameter is already defined [here]((https://github.com/danielperna84/pyhomematic/blob/97e1a4114845bafdbf791db19fdeaffe5a9fa2f6/pyhomematic/devicetypes/sensors.py#L209). The class probably has to be added [here](https://github.com/home-assistant/core/blob/7d3fcfbd30422e2fca40aab3031af13710d0a3b6/homeassistant/components/homematic/const.py#L200) in the Home Assistant code.

Please re-create this issue in the Home Assistant Repository.

**Comment by eikowagenknecht** [comment]
Thank you for the analysis, I recreated the issue.
