### ISSUE TITLE
HmIPW-SMI55 + HmIPW-WRC6

### ISSUE THREAD

**Issue by meks007** [danielperna84/pyhomematic#452]
Hi,

would it be possible for  you to add the 2 devices? SMI55 for motion, WRC6 for LED indication (on/off/blink/pulse, ..)?

Thanks!

**Comment by danielperna84** [comment]
https://github.com/danielperna84/pyhomematic/issues/28#issue-162335385

**Comment by meks007** [comment]
Thanks for the directions.
I have created the JSON's for both devices:

HmIPW-SMI55:
https://gist.github.com/meks007/dfc063a185f61760b24e32069ca0f5ca

HmIP-WRC6:
https://gist.github.com/meks007/2b3e3e1a4a9e41299fec4dfe9fb738c9

Not used to Git, I hope everything's OK.

**Comment by danielperna84** [comment]
I have tried to implement the devices from the files you have provided. For the HmIPW-WRC6 there won't be control for the lights, but you will (hopefully) get the events for the button presses.

**Comment by meks007** [comment]
thanks, is there any way i can test this right now or do i have to wait for the next HA release?

**Comment by danielperna84** [comment]
I will create a new pyhomematic release shortly, along with the PR that adds the required changes to Home Assistant. If you know how to modify the sourcecode of your HA installation, then you can manually patch this.

**Comment by danielperna84** [comment]
Here's the PR in Home Assistant which you may apply to your installation manually: https://github.com/home-assistant/core/pull/63848
