### ISSUE TITLE
HmIPW-SPI no support for presence detection? 

### ISSUE THREAD

**Issue by Brewery-GIT** [danielperna84/pyhomematic#454]
Hello;

First of, thanks for all the hard work on pyhomematic!

I currently have evrything running, but I do get an issue with the PRESENCE_DETECTION state for the HmIPW-SPI. I found some reference to this in another issue:
https://github.com/home-assistant/core/issues/53859

Could this please be added? I can provide the output for HmIPW-SPI device_descriptions+ paramset_descriptions :

https://gist.github.com/Brewery-GIT/3063114e88df88e3ec9e9d1c7f5c00e2

Many thanks in advance!

**Comment by danielperna84** [comment]
I now had a deeper look at this, and I don't see why this shouldn't work. The HmIP-SPI (non wired) had less sensors. But the wired version shouldn't be a problem. 🤔

**Comment by ivo7B4** [comment]
Thank you @danielperna84 for looking into this.
As I've also tested openhab with the homematic binding to compare whether I prefer openhab or home assistant, I can confirm that the HMIPW-SPI device has the corresponding sensor and exposes this functionaliy over the API (as I get the corresponding presence detection information in openhab).
With home assistant however, I also only get access to current_illumination and illumination for this device. I also don't get access to presence detection, same as @Brewery-GIT has described.
P.S.: My preference is with home assistant, thank you for this and the future integration.

**Comment by ivo7B4** [comment]
@danielperna84 , thank you for your great contributions, for analyzing this issue and for fixing it!
I look forward to the next release that includes this fix.
