### ISSUE TITLE
Add support for HM-RC-2-PBU-FM

### ISSUE THREAD

**Issue by cdjm** [danielperna84/pyhomematic#460]
Hello!

Can you please add support for HM-RC-2-PBU-FM?
Using HAHM the device currently is added but has only the two RSSI sensors.

This is the gist for the device and paramset description:
[HM-RC-2-PBU-FM Gist](https://gist.github.com/cdjm/2bf2f84f4962befa0ec5cc5045093bc2)

Many thanks in advance.

**Comment by cdjm** [comment]
Okay. I just found (https://github.com/danielperna84/custom_homematic#devices-with-buttons).
Using the blueprint from that page works great in Home Assistant.

Sorry for bothering.

Maybe you could move the contribution and button stuff onto the Wiki pages so you don't have to answer the same questions over and over :-)

**Comment by danielperna84** [comment]
This is not the correct repository. The correct repo for the new integration is here: https://github.com/danielperna84/hahomematic.

Having it this way allows us to identify users who don't read the documentation. 😅
