### ISSUE TITLE
Support for HMIP-PS-2

### ISSUE THREAD

**Issue by tucka** [danielperna84/pyhomematic#463]
Hi,

I just bought a new HMIP-PS-2 Pluggable Switch ("version 2") which seems to be the successor of HMIP-PS.

It seems that this plug is not supported by either pyhomematic and as a result within Home Assistant.

Are there any plans to support that device? I could assist with technical information and even coding skills ;-)

Thanks
Tucka

**Comment by danielperna84** [comment]
This project is not being worked on anymore. Please switch to the new custom integration if you need support for new devices: https://github.com/danielperna84/custom_homematic
