### ISSUE TITLE
HM-MOD-Re-8 – only channel one is working!

### ISSUE THREAD

**Issue by HollyGhos** [danielperna84/pyhomematic#467]
Hi - I'm a newbie when it comes to 'using Homematic within Homeassistant'.
I recently moved over from FHEM to HomeGear/Homeassistant with some blind actors, dimmers and this 8-channel switch. HomeMatic devices setup in HomeGear showed up in HassIO as they should.

The HM-MOD-Re-8 causes some issues and I’d like to check back with others to see how they come around. The 8 different channels of the PCBmodul have been detected as switch.neqXXXXXXX_1 - switch.neqXXXXXXX_8. Unfortunately, only channel one could be switched on/off. Channel 2-8 switch back to off in the GUI after switching them on. Error message for channel 2:

`2023-05-19 15:10:41.137 ERROR (SyncWorker_15) [pyhomematic.devicetypes.generic] HMDevice.setNodeData: STATE not found with value True on 2`

The state of channel 2-8 is not detected in HassIO either if any of these channels is switch manually.
For me it looks like channel 2-8 is not mapped / linked between HomeGear and HassIO. Or a wrong ‘name setting’ is used for the channel 2-8. Is there any chance to debug the communication between HassIO and HomeGear?
I appreciate any further tips and tricks here.
Thanks
Holger

**Comment by danielperna84** [comment]
Should be working with the [new integration](https://github.com/danielperna84/custom_homematic).

**Comment by HollyGhos** [comment]
Hi Daniel - I've update to the Beta 1.41.1 but still got just one switch. Is there a need to ´reload´ the configuration from homegear or any other advise how to access the missing switches 2-8?
Thx
Holger

**Comment by danielperna84** [comment]
Apart from properly installing and configuring the new integration, nothing else should be required.

Please open an issue here: https://github.com/danielperna84/hahomematic/issues

And include all the information the issue template is asking for (logs, version information etc.)
