### ISSUE TITLE
add support for "HmIP-eTRV-2 I9F"

### ISSUE THREAD

**Issue by NeoIsHappy** [danielperna84/pyhomematic#469]
Hi Daniel,
The thermostat is not necessarily new, but it is not added in Home Assistant (new entity), because it does not appear under the device types. In the logs of Home Assistant it is already recognized as a new device.

Device Data json file:
https://gist.github.com/NeoIsHappy/cc02638ed67e7093408f91a2a17985a1

**Comment by danielperna84** [comment]
This library is [not being maintained](https://github.com/danielperna84/pyhomematic#deprecation-warning) anymore. Please switch to the [new integration](https://github.com/danielperna84/custom_homematic) if you need support for new(er) devices.
