### ISSUE TITLE
HM-CFG-LAN -> Cant connect

### ISSUE THREAD

**Issue by Heimatplan** [danielperna84/pyhomematic#48]
**Description of problem:**

I cannot bring Home Assistant to work with HM-CFG-LAN  - Error is interface proxyInit: Exception: HHM-LAN-IF

Wie muss der Sicherheitsschlüssel angegeben werden und ist es korrekt die AES-Verschlüsselung abzuschalten?

Mit HomeMatic-Lan-Interface konfigurieren bekomme ich eine Verbindung und der Status ist Online mit Version 0.965 auf DHCP mit der IP 10.0.1.41

Eine Anbindung mit FHEM hatte funktioniert.

**Traceback or log (if applicable):**
```bash
16-12-22 18:56:30 pyhomematic._hm: ServerThread.__init__
16-12-22 18:56:30 pyhomematic._hm: __init__: Creating proxies
16-12-22 18:56:30 pyhomematic._hm: Creating proxy ip. Connecting to http://10.0.1.41:1000
16-12-22 18:56:30 pyhomematic._hm: LockingServerProxy.__init__: Getting local ip
16-12-22 18:56:30 pyhomematic._hm: LockingServerProxy.__init__: Got local ip 10.0.1.26
16-12-22 18:56:30 pyhomematic._hm: RPCFunctions.__init__
16-12-22 18:56:30 pyhomematic._hm: RPCFunctions.__init__: iterating proxy = homeassistant-ip
16-12-22 18:56:30 pyhomematic._hm: RPCFunctions.__init__: devices_raw = []
16-12-22 18:56:30 pyhomematic._hm: RPCFunctions.createDeviceObjects: iterating interface_id = ip
16-12-22 18:56:30 pyhomematic._hm: ServerThread.__init__: Setting up server
16-12-22 18:56:30 pyhomematic._hm: ServerThread.__init__: Registering RPC functions
16-12-22 18:56:30 pyhomematic._hm: Starting server at http://0.0.0.0:34693
16-12-22 18:56:30 pyhomematic._hm: ServerThread.proxyInit: init('http://10.0.1.26:34693', 'homeassistant-ip')
16-12-22 18:56:30 pyhomematic._hm: proxyInit: Exception: HHM-LAN-IF,03C5,LEQ010****,26EF0F,26EF0F,00075B6E,0000,00

16-12-22 18:56:30 pyhomematic._hm: Failed to initialize proxy
16-12-22 18:56:30 pyhomematic.connection: Failed to start server
16-12-22 18:56:30 pyhomematic.connection: 
16-12-22 18:56:30 pyhomematic._hm: ServerThread.stop: Deregistering proxy for server 10.0.1.26
16-12-22 18:56:30 pyhomematic._hm: Failed to deregister proxy
16-12-22 18:56:30 pyhomematic._hm: stop: Exception: [Errno 111] Connection refused
16-12-22 18:56:30 pyhomematic._hm: Shutting down server
16-12-22 18:56:30 pyhomematic._hm: ServerThread.stop: Stopping ServerThread
16-12-22 18:56:30 pyhomematic._hm: Server stopped
16-12-22 18:56:30 pyhomematic._hm: ServerThread.getServiceMessages: Exception: 'homeassistant-ip'

_If you encounter the problem when using Home Assistant, please fill out the following information_

**Home Assistant version (if applicable):**
0.35.2

**Problem-relevant `configuration.yaml` entries and steps to reproduce:**
``homematic:
  hosts:
    ip:
      ip: 10.0.1.41
      port: 1000
#      resolvenames: metadata

**Comment by danielperna84** [comment]
Man kann den HM-CFG-LAN nicht direkt benutzen. Du brauchst beispielsweise Homegear als Service der dazwischen hängt und die XML-RPC API zur Verfügung stellt. Der HM-CFG-LAN alleine hat die nämlich nicht.

**Comment by Heimatplan** [comment]
Dankeschön, aus der Anleitung unter https://home-assistant.io/components/homematic/ war dies nicht heraus zu lesen. Ich google micht mal weiter durch, dankeschön!

**Comment by danielperna84** [comment]
Naja, in der HASS Doku steht:
> The Homematic component provides bi-directional communication with your CCU/Homegear
Der HM-CFG-LAN wird weiter unten nur im Zusammenhang mit Homegear erwähnt.

Die Doku von Homegear ist leider eher dürftig. Und das Wiki ist glaube ich nicht mehr auf dem aktuellsten Stand. Lieber mal im Homegear Forum schauen oder generell nach Tutorials die nicht allzu alt sind. Die meisten beziehen sich noch auf eine ältere Version, und irgendwann im Laufe diesen Jahres gab's einen größeren Sprung. Der hatte bei mir dann alles zerschossen und ich musste alle Geräte neu anlernen. Normalerweise bin ich ein Freund von Updates. Aber Homegear habe ich immer nur im äußersten Notfall aktualisiert, weil's immer irgendwie Probleme gab hinterher.

**Comment by Heimatplan** [comment]
Es klappt jetzt, vielen Dank noch mal!
