### ISSUE TITLE
Change name "homematic"

### ISSUE THREAD

**Issue by jazzaj** [danielperna84/pyhomematic#5]
As the convention in "home assistant" seems to be to use the vendor name for components/platforms it would help to avoid name confustion if this component could be called different (e.g. pyhomematic)

**Comment by danielperna84** [comment]
I don't think the library should be modified to fit a specific projects namespace usage. If there are conflicts, Python allows to do:
```python
import homematic as pyhomematic
```

And using **py**homematic within Python seems a little redundant to me.

**Comment by jazzaj** [comment]
Your arguments seems valid. Unfortunatly I'm not able to impor the homematic module from pyhomematic. Instead it seems to open always the thermostat homematic module. Most likely this can be easily solved by someone more experienced.

**Comment by danielperna84** [comment]
If you installed pyhomematic via pip, then usually you do ```import homematic``` to use it. To import it using a different name, you would do ```import homematic as pyhomematic```. I did just try it and it works for me.
