### ISSUE TITLE
Shutter Contact BC-SC-Rd-WM / Remote BC-PB-2-WM-2

### ISSUE THREAD

**Issue by tringler** [danielperna84/pyhomematic#50]
Hello,

should I expect, that device type BC-SC-Rd-WM should display as sensor in Homeassistant? I paired all my thermostats and shutter contacts in HomeGear, but only the thermostats are shown up in HomeAssistant.

I'm running HA 0.34.0 and pyhomematic-0.1.18.

Thanks in Advance!

**Comment by jannau** [comment]
@tringler no, I only added BC-SC-Rd-WM-2 in 6279ba9322311d09a78e3402b50cba9b8b887b1a

Please try adding
`
    "BC-SC-Rd-WM": ShutterContact,
`
to  pyhomematic/devicetypes/sensors.py

**Comment by tringler** [comment]
Added, but no change in HomeAssistant. Should that work out of the box and displayed as a sensor?

**Comment by jannau** [comment]
@tringler yes, it should work out of the box. Are you sure home-assistant uses the modified version (please check ~/.homeassistant/deps/ of the user running hass)?

**Comment by tringler** [comment]
@jannau Thanks a lot! - It's working now after I manually copied the content of the folder /usr/local/lib/python3.4/dist-packages/pyhomematic to my configuration dir/deps - Should I send a PR for that one line?

**Comment by pvizeli** [comment]
That would be nice

**Comment by tringler** [comment]
I have the same question for device BC-PB-2-WM - Should this device shown in HA? It's this device: [ECO Switch](http://www.eq-3.de/Downloads/eq3/downloads_produktkatalog/max/bda/BC-PB-2-WM-2_UM_DE.pdf) - I tried to add as switch: It's shown as a switch, but not working (status is not changing). I tried to add as a remote, but it's not shown up at all in HA. It looks like `BC` it's just the vendor code for the MAX! devices, because we have already this HomeMatic device in the list: `HM-PB-2-WM": Remote`

**Comment by danielperna84** [comment]
The `BC-PB-2-WM` is not a switch, event though it looks like one. It's actually a remote control, just like you found out. The closest one from the HomeMatic devices would be the `HM-PB-2-WM55`, which is implemented in [misc.py](https://github.com/danielperna84/pyhomematic/blob/master/pyhomematic/devicetypes/misc.py).

These types of devices don't show up as entities in HASS. They only fire `homematic.keypress` events. The [documentation](https://home-assistant.io/components/homematic/) has an example on how to use them. So as long as you don't have automations assigned to such an event, you'll only see something happening when setting HASS' loglevel to INFO.

**Comment by tringler** [comment]
@danielperna84 Thanks a lot for that hint! If I understand it correctly it should work if I add an automation like this:

```
automation:
   trigger:
     platform: event
     event_type: homematic.keypress
     event_data:
       name: Kitchen Switch
       channel: 1
       param: PRESS_SHORT
   action:
     service: switch.turn_on
     entity_id: switch.Kitchen_Ambience
```

I will test it and send the PR with both new device IDs if it's working like expected.

**Comment by danielperna84** [comment]
Yes, that's how it should work.

**Comment by danielperna84** [comment]
@jannau 
BC-SC-Rd-WM now should be working with HASS 0.36.0 without patching the code. Can you confirm it's working? If so, @tringler 's PRs would be pretty straightforward and should work out of the box, as soon as he pushes the code.

**Comment by tringler** [comment]
I will push the "code" this evening.

**Comment by tringler** [comment]
https://github.com/danielperna84/pyhomematic/pull/53

**Comment by jannau** [comment]
@danielperna84 HASS 0.36.1 / pyhomematic 0.1.19 works unmodified
