### ISSUE TITLE
Module MAX: CUL "My-MAX-CUL": Warning: Too short packet received: LOVF

### ISSUE THREAD

**Issue by tringler** [danielperna84/pyhomematic#52]
Hello,

more a generic question than an issue, but it there a working approach to get rid of `Module MAX: CUL "My-MAX-CUL": Warning: Too short packet received: LOVF` errors due to too many requests?

Thanks in Advance!

**Comment by danielperna84** [comment]
That seems to be a problem specific to MAX. With my HomeMatic setup I've never seen such an error.

**Comment by tringler** [comment]
My understanding is that this is caused by the "1% rule" which is built in in the CUL firmware.

[https://github.com/openhab/openhab/wiki/MAX!-CUL-Binding](https://github.com/openhab/openhab/wiki/MAX!-CUL-Binding)

```
Number txCredit { maxcul="CreditMonitor" } - Will be updated with the latest value for the TX credit whenever it receives an update or command to a maxcul binding item. This number is used to adhere to the 1% transmission time rule. The 1% rule is enforced by the CUL USB device firmware.
```

Am I wrong again? :)

**Comment by danielperna84** [comment]
At least I can't say anything about that. Let's wait and see if someone who uses MAX too has something to say about that.

**Comment by jannau** [comment]
Yes, I see that too from time to time. It is caused by the %1 rule and not really MAX specific. It's much easier to trigger with MAX devices though since the MAX radio protocol is inferior and requires much more transmission time to send commands.

**Comment by tringler** [comment]
@jannau Can you explain how this 1% rule is exactly working and how can I customize my HASS config to get rid of the problem?

**Comment by jannau** [comment]
@tringler there is no way around it (except adding another CUL to homegear). If you understand german this [link](https://forum.homegear.eu/t/Max-oder-Homematic/944/9) explains why the 1% rule is such a problem for the Max! radio protocol. In short: the MAX! protocol uses 1 second long Wake-on-Radio packets to send commands to devices. One percent of 1 hour is 36 seconds so that means that at most 36 commands can be sent per hour. Iirc the CUL firmware enforces the 1% rule over a 15 minute window.

**Comment by tringler** [comment]
@jannau Thanks for the explanation! Yes I'm speaking German. I'm just writing in English if someone else non-German have the same problem and wants to figure out. On the other hand I think the MAX! Devices are only distributed in Germany, but I'm not sure.

Nevertheless I need to verify I'm send ingless than 10 commands per 15 minutes right?

On HASS a possible solution would be:

* Writing a script, which is setting the temperature and mode and increases a counter which is stored in a template sensor
* If the sensor is reaching the value 9 the script will be delayed with 15 minutes
* The template sensor will be reset every 15 minutes

Right?

**Comment by jannau** [comment]
@tringler I don't think there's a need to do anything. Homegear queues the commands and will send them later if the 1% rule prevents to send them .

**Comment by tringler** [comment]
Ok - Sorry! It's not the case for me, but I will close the topic.

**Comment by danielperna84** [comment]
If you need some workaround you could also use the [AppDaemon](https://home-assistant.io/ecosystem/appdaemon/) for really flexible automations. With those you wouldn't need an extra sensor to keep track of the sent messages.

**Comment by jannau** [comment]
@tringler I never fully verified it but I've seen 'delayed' commands. If you see lost commands that's probably a bug in homegear. Trying to fix it in pyhomematic or even a layer above pyhomematic won't work well. Please bring your issue to [homegear's](https://github.com/Homegear/Homegear) attention.
