### ISSUE TITLE
state low battery info

### ISSUE THREAD

**Issue by buxit** [danielperna84/pyhomematic#75]
it seems that some code for low battery warnings has been added to helper.py. but still many battery powered homematic devices lack information about battery state. of all the devices i own, currently only the shutter sensors appear with battery attributes.

how can i help to improve this situation?
some devices can report more than just full / empty. is there some home assistant standard for battery state that should be followed?
would it be enough to add HelperLowBat class to all classes in question?
with some instructions i would volunteer to implement / test improvements in this area.

are there any tools you use to query attributes / values from the ccu directly? is there some debugging switch i can use to see which python classes get used for which device in home assistant?

**Comment by danielperna84** [comment]
You are correct, the battery-state is only implemented for a few devices, even though there are a lot more.

Yes, inheriting from the HelperLowBat is the correct way for devices that report a boolean battery state. For devices with actual values you can have a look at the thermostats. I believe the radiator-thermostats expose the battery-level as an attribute. However, this probably also requires on the HASS side.
In the beginning I would just focus devices with the boolean battery state and just add the additional class. This can be done without changing anything in HASS, and if it's working you should get the state the device reports.

No, there is no tool. In some way pyhomematic is the tool that's used to query that information. Have a look at [example.py](https://github.com/danielperna84/pyhomematic/blob/master/example.py) if you are willing to query the information manually.

**Comment by danielperna84** [comment]
Closing this since a a lot has happened in this regard. For devices where it's missing separate issues will probably opened.
