### ISSUE TITLE
Desired function: _devices.HMDevice.is_reachable()

### ISSUE THREAD

**Issue by jazzaj** [danielperna84/pyhomematic#8]
Should provide information if device can be contacted by the CPU. Required at start-up to compensate for missed "UNREACH" events.

**Comment by danielperna84** [comment]
I assume you men CCU.
Since I don't know about that state, could you explain in more detail? Does this happen when the battery of a paired device is dead or the device out of range?
A sample of such an event from the logs would be helpful as well.

**Comment by jazzaj** [comment]
Yes. CCU.
The problem occurs when their is any communication issue between CCU and device (e.g. bad reception, unplugged plug, maybe battery low as well)

In the log you can see at the start of the issues:
`INFO:pyhomematic._devices:HMDevice.event: address=LEQXXXXXXX:0, interface_id=pyhomematic, key=UNREACH, value=True`
`INFO:pyhomematic._devices:HMDevice.event: address=LEQXXXXXXX:0, interface_id=pyhomematic, key=STICKY_UNREACH, value=True`

And when the connection is restored:
`INFO:pyhomematic._devices:HMDevice.event: address=LEQXXXXXXX:0, interface_id=pyhomematic, key=UNREACH, value=False`

This is the part I can handle. I was hoping you have some idea on how do handle devices with an "unreach" condition at the start-up of the software. In this cased the RPC has missed the event...

**Comment by danielperna84** [comment]
Well, that sounds like the HMDevice class would simply need another property (unreachable), which would be easy to implement. I assume the unreachable-state has no effect on the presence of the device within the CCU, so the the device on the pyhomeatic-side will be created even if the device is unreachable, and would start working as soon as the device is working again.

What we could do in pyhomeatic is, prior to switching a switch etc., to check if the device is unreachable, and the setValue methods etc. would return a failure to the consuming piece of software (like home assistant). Although that probably would require that software to be able to handle failures. I don't know if HA does that.

I can implement the property. What I would like to know: if the device is unreachable at startup, is that information provided within the paramsets?
