### ISSUE TITLE
HM-LC-Dim1T-DR missing in actors.py

### ISSUE THREAD

**Issue by LeonVos** [danielperna84/pyhomematic#81]
Hi Daniel, missing also is the DIN dimmer HM-LC-Dim1T-DR, how can i edit this in HASS.io?
I have HASS.IO 0.53.1
Thx

**Comment by LeonVos** [comment]
hhmmm its a KEYDIMMER ?? in actors.py
I have 4 off them in my CCU but i can't see them in HA ?
Leon

**Comment by danielperna84** [comment]
I don't think it is a keydimmer. Keydimmers are the ones with button where you can directly control the brightness. So it probably will work as a regular dimmer.
You can't add it in hass.io I believe. The place where pyhomematic is stored is read only as far as I know. If you want to have it added please set up some sort of development environment wit ha regular HASS installation. There you can edit the actors.py and verify its functionality.

**Comment by LeonVos** [comment]
Daniel, 
so i can't put it in hassio\config\custom_components\actors.py  ? (or ...onents\pyhomematic\...  )

**Comment by danielperna84** [comment]
No, I don't think so. pyhomematic is a library that is being imported by Home Assistant, and it is expecting the actors.py to be at a specific path (where all the other pyhomematic related code is stored). It is not a HASS component. HASS components import these libraries to do the work.
hass.io is not the right choice is you want to manually make changes to the code that is being used. hass.io is like a closed system. The only things you can change are those that are designed to be changed (configuration, custom components, images etc).

**Comment by LeonVos** [comment]
Daniel, 
setup the DEV HA, and edited ..../light/actors.py ( "HM-LC-Dim1T-DR": Dimmer, ) i can see it react in the terminal but not in the frontend (should that be in dev modes?)
HM-LC-Dim1T-DR with ser# NEQ1742981 & NEQ1742998.

Is This enough ??

Leon Vos

![hm-lc-dim1t-dr](https://user-images.githubusercontent.com/25909271/31097311-288c819c-a7bf-11e7-8a86-247e21598337.jpg)
[HM-LC-Dim1T-DR.txt](https://github.com/danielperna84/pyhomematic/files/1350250/HM-LC-Dim1T-DR.txt)

**Comment by danielperna84** [comment]
Adding `"HM-LC-Dim1T-DR": Dimmer,` to _pyhomematic/devicetypes/actors.py_ (NOT in the lights-folder of HASS!) should provide you a fully functional light-entity in Home Assistant. As long as you don't have that it's not correct.

**Comment by LeonVos** [comment]
Thats deep ;-)
I will use that tonight

**Comment by LeonVos** [comment]
Daniel, works great.
I used my live install for it now, and all is well.
Tomorrow i will add it in the dev, and upload to git.

Thx

**Comment by danielperna84** [comment]
I have now added it myself to include it in the next version. Thanks for testing.
