### ISSUE TITLE
Support for HM-PB-4DIS-WM-2

### ISSUE THREAD

**Issue by Gomez** [danielperna84/pyhomematic#82]
Hi,

dieser Wandtaster wird leider nicht von HASS erkannt. In Homegear ist er erfolgreich angemeldet:

`  3 │                           │   51368C │    NEQ1487615 │ 00DD │           HM-PB-4Dis-WM-2 │      1.5 │             No │      No │      No`

Kann ich ähnlich wie hier vorgehen um in "bekannt" zu machen?
https://github.com/danielperna84/pyhomematic/issues/77

**Comment by danielperna84** [comment]
Im Prinzip ja. Der HM-PB-4DIS-WM (ohne -2) steht ja schon drin. Es sollte also ausreichen -2 noch hinzuzufügen.
Aber bitte bedenken: hier kann man nicht wirklich mit dem Display arbeiten. Es werden nur die Events registriert.

**Comment by Gomez** [comment]
Ok, danke. Ich versuch es und erstelle dann ein PR.

Ich möchte es in HASS verwenden, wie hier beschrieben: https://home-assistant.io/components/homematic/#devices-with-buttons

Das ginge dann?

**Comment by danielperna84** [comment]
Ja, das würde gehen. Also z.B. eine Automation starten wenn Du den Taster drückst.

**Comment by Gomez** [comment]
Getestet und funktioniert :)
