### ISSUE TITLE
Support Homematic IP Access Point

### ISSUE THREAD

**Issue by mammuth** [danielperna84/pyhomematic#88]
I just found the following Python wrapper for the communication with the Homematic IP access point: https://github.com/coreGreenberet/homematicip-rest-api

Maybe this could be used to support the IP Access Point beside CCU/Homegear? Especially for HomeAssistant that'd be a great addition in my opinion 😊 

If it's nothing that you want to have integrated in _pyhomeatic_, does it make sense to create a separate HA component for Homematic IP Access Point that uses _homematicip-rest-api_?

**Comment by danielperna84** [comment]
This seems totally different than how pyhomematic works. So I think it would make more sense to have a separate component for this. Integrating this into pyhomematic would make everything much more complicated.

**Comment by mammuth** [comment]
Alright, thanks!
