### ISSUE TITLE
Desired function: _sever.ServerThread.is_all_devices_created()

### ISSUE THREAD

**Issue by jazzaj** [danielperna84/pyhomematic#9]
Creation of devices (at least with an CCU) takes a couple of seconds (2-3 in my situation). I would love to know if creation of all devices has been finalized.

**Comment by danielperna84** [comment]
You can evaluate the state of homeatic.devices with the same effect. For example:

```python
...
while not homematic.devices:
    time.sleep(1)
```
While no devices are created, homematic.deivces is an empty list. Lists (and many other objects) can be tested like bools. So an empty list is False, one with content is True. The desirend function would essentially do nothing else than ```return bool(homematic.devices)```.
I admit, that this way results in a race condition if this is tested while creation is still in progress.

If this is really needed, I would see the solution in adding a class-variable like "working", which is True while the device-creation is in progress, and set to False afterwards.

So in that case we could do
```python
...
while homematic._server.working:
    time.sleep(1)
```

Would that be a solution that fixes your requirement?

**Comment by jazzaj** [comment]
Your proposal sounds great. As the whole creation process takes a couple of seconds within the home assistant enviroment the later solution would be great help...
