### ISSUE TITLE
HM-PB-6-WM55 ??

### ISSUE THREAD

**Issue by LeonVos** [danielperna84/pyhomematic#92]
Hi Daniel,

I see the support for HM-PB-6-WM55 (6 button RF wall switch) in https://github.com/danielperna84/pyhomematic/blob/master/pyhomematic/devicetypes/misc.py.
I have 3 off them here, but i can't see them in my HA ?? (0.52.1)
Do i need to do some extra for it ?

regards Leon Vos

**Comment by danielperna84** [comment]
You won't see any entities for that device. Have a look at the [Devices with buttons](https://home-assistant.io/components/homematic/#devices-with-buttons) part of the Home Assistant documentation. Such devices operate with events, not states.
