### ISSUE TITLE
Support for HmIP-SPI

### ISSUE THREAD

**Issue by BGoll** [danielperna84/pyhomematic#93]
Hi there,

first of all thank you for your awesome project!

I recently started in the Homematic world and bough an indoor presence sensor (HmIP-SPI).  Since it is not supported yet, I added the line

`"HmIP-SPI": MotionIP,`

to `sensors.py`.
After restarting home assistant, I now have a new entity called sensor.<address>_illumination which also works fine. However there is no binary_sensor for the motion detection. So I write a small script to test everything and got the following errors:

`print(pyhomematic.devices['ip']['<address>'].is_motion())`
`HMGeneric.getValue: MOTION on <address>:1 Exception: <Fault -5: 'Unknown Parameter for value key: MOTION'>`
`False`

and

`print(pyhomematic.devices['ip']['<address>'].is_motion_detection_active())`
`HMGeneric.getValue: MOTION_DETECTION_ACTIVE on <address>:1 Exception: <Fault -5: 'Unknown Parameter for value key: MOTION_DETECTION_ACTIVE'>`
`False`

Could you give me a hint how to fix that? I am totally new to all this stuff :-)

Thanks!

**Comment by danielperna84** [comment]
IP devices are very different from the regular wireless devices. With those there's usually a boolean `STATE` parameter on one channel that is either true or false. When motion is detected, the state changes from false to true, and depending on how the device is configured stays at that state until te motion is done. Just like the classic motion-detectors for lights that just turn on for some amount of time once motion has been detected.

It may however be, that this behaviour has changed and they are now just using events (like button presses on remote controls). Today I received the same device you are talking about and I'll have a look at it shortly.

**Comment by BGoll** [comment]
Great, thank you very much! Looking forward to using this device!

I would like to be a tester for your changes, if that's okay for you. Just comment here as soon as there is something to test.

**Comment by danielperna84** [comment]
I have created a PR: https://github.com/danielperna84/pyhomematic/pull/95
Take the sensors.py from there and also apply the changes in the HASS-files I have mentioned there.

The motion detection can actually be turned on and off. But I chose not to include that. It can be done when needed using the `set_dev_value` service in HASS.

**Comment by BGoll** [comment]
Wow, that was fast and it works like a charm! Thank you very much! :-)
